#!/usr/bin/env python3
"""Generate ~22 tutorials — Cloud, Languages, Architecture, Storage, More."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === CLOUD (8) ===
    ("AWS Fundamentals", "aws-fundamentals.html", "Amazon Web Services -- EC2, S3, VPC, IAM, Lambda, and core services.", "Cloud", "fab fa-aws", [
        Q("Compute & Storage", "<p>EC2: virtual servers -- instance types (t3.micro for free tier, m5 general, c5 compute, r5 memory), AMIs (Amazon Linux, Ubuntu, Windows), security groups (instance firewall), key pairs (SSH), EBS volumes (gp3, io2). Auto Scaling: launch templates, scaling policies, health checks. S3: object storage -- buckets (globally unique name), objects (key, value, metadata, version ID), storage classes (Standard, IA, Glacier, Deep Archive). S3 features: versioning, lifecycle policies, replication, presigned URLs, static website hosting. Lambda: serverless functions -- triggers (S3, API Gateway, DynamoDB, SQS), runtimes (Python, Node, Java, Go), concurrency, environment variables, layers. Pricing: per request + duration (1ms increments).</p>"),
        Q("Networking & IAM", "<p>VPC: virtual network -- subnets (public/private), route tables, internet gateway, NAT gateway, security groups (stateful), NACLs (stateless, subnet-level). VPC flow logs: traffic logging. IAM: users, groups, roles, policies (JSON -- Effect, Action, Resource, Condition). Policy types: AWS managed, customer managed, inline. Roles: assume by EC2, Lambda, cross-account. Best: least privilege, use roles not keys. RDS: managed databases -- MySQL, PostgreSQL, MariaDB, SQL Server, Oracle, Aurora. Multi-AZ (HA), read replicas. DynamoDB: NoSQL key-value/document -- on-demand vs provisioned capacity, auto-scaling, DAX (cache). Global tables: multi-region replication. Route 53: DNS hosting, routing (simple, weighted, latency, geolocation, failover), health checks. CloudFront: CDN -- edge locations, origins, behaviors, Lambda@Edge. CloudWatch: metrics, logs, alarms, dashboards. CloudFormation: IaC (YAML/JSON templates).</p>"),
    ],[F("AWS Docs","https://docs.aws.amazon.com/","Official AWS documentation"),F("AWS Well-Architected","https://aws.amazon.com/architecture/well-architected/","AWS best practices")]),
    ("Azure Fundamentals", "azure-fundamentals.html", "Microsoft Azure -- VMs, storage, networking, Entra ID, and core services.", "Cloud", "fab fa-microsoft", [
        Q("Compute & Storage", "<p>Azure VMs: series (B-series burstable, D-series general, E-series memory), availability sets (fault/update domains), availability zones, scale sets. Azure Blob Storage: containers, tiers (hot, cool, cold, archive), access tiers, lifecycle. Azure Files: SMB file shares. Azure Functions: serverless -- triggers (HTTP, timer, blob, queue, event grid), plans (consumption, premium, dedicated). App Service: web apps (Windows/Linux, containers), auto-scale, deployment slots.</p>"),
        Q("Networking & Entra ID", "<p>Azure VNet: address space, subnets, peering, VPN gateway, ExpressRoute. NSG: network security groups (stateful rules). Azure Firewall: managed firewall. Entra ID (Azure AD): identity, SSO, MFA, Conditional Access. RBAC: roles (Owner, Contributor, Reader), custom roles. Managed identities: for Azure resources (no secrets). Azure SQL Database: managed SQL, elastic pools, geo-replication. Cosmos DB: globally distributed NoSQL, multi-API (SQL, MongoDB, Cassandra, Gremlin, Table). Azure DevOps: Boards, Repos, Pipelines, Artifacts. ARM templates: IaC (JSON template + parameter files). Bicep: simplified ARM DSL.</p>"),
    ],[F("Azure Docs","https://learn.microsoft.com/en-us/azure/","Official Azure documentation"),F("Azure Architecture","https://learn.microsoft.com/en-us/azure/architecture/","Azure architecture center")]),
    ("Google Cloud Platform", "google-cloud-platform.html", "Google Cloud -- Compute Engine, GKE, Cloud Storage, BigQuery, and IAM.", "Cloud", "fab fa-google", [
        Q("Compute & Storage", "<p>Compute Engine: VMs -- machine families (E2, N2, C2, M2), custom machine types, sole-tenant nodes, preemptible/spot VMs. GKE: Kubernetes Engine -- clusters, node pools, auto-scaling, auto-upgrade, Workload Identity (GCP IAM for K8s). Cloud Storage: buckets, storage classes (Standard, Nearline, Coldline, Archive), object versioning, retention policies, signed URLs. Cloud Functions: serverless -- triggers (HTTP, Pub/Sub, Cloud Storage, Firestore), runtimes, 2nd gen (Eventarc). App Engine: PaaS -- standard (sandboxed) vs flexible (containers), auto-scaling.</p>"),
        Q("Networking & IAM", "<p>VPC: global networking, subnets (regional), firewall rules, Cloud NAT, Cloud VPN, Cloud Interconnect (dedicated). Cloud Load Balancing: global HTTP(S), SSL proxy, TCP/UDP, internal. Cloud CDN: global content delivery. IAM: roles (primitive, predefined, custom), service accounts, policies (bind roles to members). BigQuery: serverless data warehouse -- SQL queries, partitioned/clustered tables, BI Engine. Cloud SQL: managed MySQL, PostgreSQL, SQL Server. Firestore: NoSQL document DB (serverless). Pub/Sub: messaging (push/pull, exactly-once). Cloud Run: serverless containers (Knative-based). Deployment Manager: IaC (YAML + Python/Jinja templates). Terraform: GCP provider. Cloud Build: CI/CD.</p>"),
    ],[F("GCP Docs","https://cloud.google.com/docs","Official Google Cloud docs"),F("GCP Architecture","https://cloud.google.com/architecture","GCP architecture")]),
    ("AWS EC2 & Compute", "aws-ec2-compute.html", "Deep dive into AWS EC2 -- instance types, storage, networking, and optimization.", "Cloud", "fab fa-aws", [
        Q("Instances & AMIs", "<p>EC2 instance types: naming (m5.xlarge -- family, generation, size). Families: general (t3, m5, m6i), compute (c5, c6i), memory (r5, r6i, x2gd), storage (i3, d2), GPU (p3, p4, g5). Pricing: On-Demand, Reserved (1/3yr, partial/upfront), Spot (up to 90% off, interruptions). Placement groups: cluster (low latency), spread (hardware isolation), partition (distributed). AMI: Amazon Machine Image -- EBS-backed vs instance-store. User data: scripts run at launch (cloud-init). Hibernate: preserve RAM state. Nitro: next-gen hypervisor (better perf, security).</p>"),
        Q("EBS & Networking", "<p>EBS: block storage -- gp3 (baseline 3000 IOPS, 125 MB/s), io2 (provisioned IOPS, 64k max), st1 (throughput, HDD), sc1 (cold HDD). Snapshots: incremental, EBS Snapshots Archive. Instance store: ephemeral, lost on stop/terminate. ENI: elastic network interface -- separate subnets, failover. ENA: enhanced networking (up to 100 Gbps). EFA: elastic fabric adapter (HPC/ML, OS bypass). Elastic IP: static public IPv4. EC2 Auto Scaling: launch template, min/max/desired, scaling policies (target tracking, step, simple). Lifecycle hooks: pause instances during scale events. EC2 Image Builder: automate AMI creation. Instance metadata: http://169.254.169.254/latest/meta-data/. Systems Manager: SSM agent, Run Command, Patch Manager, Session Manager.</p>"),
    ],[F("EC2 Docs","https://docs.aws.amazon.com/ec2/","EC2 documentation"),F("AWS Compute Blog","https://aws.amazon.com/blogs/compute/","Compute updates and best practices")]),
    ("AWS S3 & Storage", "aws-s3-storage.html", "Deep dive into S3 -- storage classes, security, lifecycle, and performance.", "Cloud", "fab fa-aws", [
        Q("S3 Basics & Classes", "<p>S3: objects in buckets (flat namespace, max 100 buckets/account soft). Objects: key (path), version ID, metadata, tags. Storage classes: S3 Standard (frequent access), Intelligent-Tiering (auto-tier), Standard-IA (infrequent), One Zone-IA (lower cost), Glacier Instant Retrieval (archive ms), Glacier Flexible (min 90 days), Glacier Deep Archive (min 180 days). Lifecycle policies: transition objects between classes, expire (delete). Multipart upload: large objects >100MB. S3 Transfer Acceleration: global upload speed. Pre-signed URLs: temporary access. SSE: server-side encryption (SSE-S3, SSE-KMS, SSE-C). Bucket policies: resource-based IAM policies. Block Public Access: account/bucket settings.</p>"),
        Q("Advanced & Performance", "<p>S3 Event Notifications: SQS, SNS, Lambda triggers. S3 Replication: CRR (cross-region), SRR (same-region), batch replication, delete marker replication. S3 Object Lock: WORM (write once read many) -- retention period, legal hold. S3 Select: SQL-like queries on objects. S3 Glacier Select: query archived data. S3 Batch Operations: bulk actions (copy, invoke Lambda, restore). S3 Inventory: audit object metadata. S3 Access Points: named network endpoints with policies. Performance: 3500 PUT/5500 GET per prefix per second. Multi-region access points: global endpoint with routing. VPC endpoint: S3 Gateway endpoint (free) or Interface endpoint (PrivateLink). Requester Pays: bucket owner transfers costs. S3 on Outposts: on-prem S3.</p>"),
    ],[F("S3 Docs","https://docs.aws.amazon.com/s3/","S3 documentation"),F("AWS Storage Blog","https://aws.amazon.com/blogs/storage/","Storage best practices")]),
    ("Cloud Networking & VPC", "cloud-networking-vpc.html", "Cloud networking -- VPC design, peering, VPN, Direct Connect, and CDN.", "Cloud", "fas fa-network-wired", [
        Q("VPC Design & Peering", "<p>VPC: virtual data center -- CIDR (e.g., 10.0.0.0/16). Subnets: public (IGW), private (NAT for outbound). Route tables: explicit subnet associations. Internet Gateway: attach to VPC, routes 0.0.0.0/0 -> igw. NAT Gateway: private subnets access internet (not inbound). NAT Instance: cheaper, less available. VPC Peering: connect VPCs (same or cross-account), transitive routing not supported. Transit Gateway: hub for multiple VPCs/on-prem, route tables, attachments. AWS PrivateLink: expose services privately within VPC. VPC Endpoints: Gateway (S3, DynamoDB) vs Interface (many services). DHCP option sets: domain name, DNS. Elastic IP: static IPv4. ENI: attached to instances.</p>"),
        Q("VPN & CDN", "<p>Site-to-Site VPN: IPSec tunnels to on-prem. VPN CloudHub: multiple sites via VPN. Direct Connect: dedicated fiber (1Gbps/10Gbps), private VIF, public VIF, transit VIF. Direct Connect Gateway: connect to multiple VPCs/accounts. AWS Global Accelerator: anycast IP, traffic optimization, health checks. CloudFront: CDN -- origins (S3, ALB, custom), behaviors (path patterns), geo-restriction, signed URLs/cookies, Lambda@Edge, Origin Shield. Route 53: DNS service -- routing policies (simple, weighted, latency, geolocation, failover, multivalue). Alias records: route to AWS resources (free). Health checks: monitor endpoints, DNS failover. WAF: web application firewall -- rules (SQL injection, XSS, rate-based, IP sets). Shield: DDoS protection (Standard free, Advanced $3k/mo).</p>"),
    ],[F("AWS Networking Docs","https://docs.aws.amazon.com/vpc/","VPC documentation"),F("CloudFront Docs","https://docs.aws.amazon.com/cloudfront/","CDN documentation")]),
    ("Serverless & Event-Driven", "serverless-event-driven.html", "Serverless architecture -- Lambda, event-driven patterns, and best practices.", "Cloud", "fas fa-bolt", [
        Q("Lambda & Event Sources", "<p>AWS Lambda: function-as-a-service. Triggers: S3 (object created), API Gateway (HTTP/REST), DynamoDB Streams, Kinesis, SQS, SNS, EventBridge, Cognito. Integration: directly invoke (sync), event source mapping (async poll). Event source mapping: batches, partial batch response, filter criteria, destinations (DLQ, success). Lambda@Edge: run at CloudFront edge. Lambda layers: shared dependencies. Lambda SnapStart: faster cold starts (Java). Provisioned concurrency: pre-warmed environments. Reserved concurrency: guaranteed capacity. Runtimes: Node, Python, Java, Go, .NET, Ruby, custom (Rust via provided.al2). Limits: 15 min timeout, 10GB memory, 512MB /tmp, 6MB request/response. Observability: CloudWatch Logs, X-Ray tracing (distributed tracing with segments/subsegments). Powertools: Lambda best practices libraries.</p>"),
        Q("Event-Driven Patterns", "<p>EventBridge: event bus -- schemas, rules, targets (Lambda, SQS, SNS, Step Functions). Events: AWS services, custom apps, SaaS partners (Shopify, Datadog). EventBridge Pipes: point-to-point integration (source -> filter/enrich -> target, with optional DLQ and enrichment Lambda). SQS: queues -- standard (at-least-once, high throughput), FIFO (exactly-once, 300 txn/s). Dead-letter queues: failed messages. SNS: pub/sub -- topics, subscriptions (SQS, Lambda, email, SMS, HTTP). Step Functions: state machine -- tasks, choices, parallel, map, wait, error handling. Express vs Standard workflows. API Gateway: REST, HTTP, WebSocket APIs -- stages, usage plans, API keys, caching, request/response transformation. SAM: Serverless Application Model (simplified CloudFormation for serverless). CDK: Infrastructure as Code (TypeScript, Python, Java, C#, Go). Amplify: full-stack app framework. Best practices: idempotency, DLQ for failures, structured logging, least privilege IAM. Cold start mitigation: SnapStart (Java), provisioned concurrency, interpreted languages (Node/Python) start fast.</p>"),
    ],[F("Lambda Docs","https://docs.aws.amazon.com/lambda/","Lambda developer guide"),F("EventBridge Docs","https://docs.aws.amazon.com/eventbridge/","EventBridge documentation")]),
    ("Cloud Cost Optimization", "cloud-cost-optimization.html", "Reduce cloud costs -- right-sizing, reserved instances, spot instances, and FinOps.", "Cloud", "fas fa-dollar-sign", [
        Q("Compute & Storage", "<p>Right-sizing: match instance to workload -- CloudWatch metrics (CPU, memory, network), AWS Compute Optimizer (ML recommendations). Reserved Instances: 1yr/3yr, Standard/Convertible, partial/full/no upfront. Savings Plans: flexible discount (compute or EC2 instance). Spot Instances: up to 90% off, use for fault-tolerant, stateless, flexible workloads. Spot Fleet/EC2 Fleet: diversified across pools. EBS gp3: baseline 3000 IOPS included, only pay extra provisioned. S3 lifecycle: transition to IA/Glacier. S3 Intelligent-Tiering: auto savings. Data transfer: expensive (use CloudFront, VPC endpoints, same-AZ).</p>"),
        Q("Monitoring & FinOps", "<p>AWS Cost Explorer: visualize spend, cost trends, usage. AWS Budgets: alerts at threshold (cost, usage, RI coverage). Cost allocation tags: track by project/team/environment. Trusted Advisor: cost optimization checks (idle instances, underutilized). Compute Optimizer: right-sizing, auto-scaling recommendations. S3 Storage Lens: storage usage, optimization. FinOps: culture + practice -- track, optimize, operate. Graviton: ARM-based instances (20-40% cheaper). Serverless: Lambda no cost when idle. Container right-sizing: adjust CPU/memory requests. RDS: use Reserved Instances, Aurora Serverless. NAT Gateway: expensive for high bandwidth (use NAT instance or VPC endpoints). Savings: commitments (RI/SP) 30-60% off, spot (60-90% off), right-sizing (10-20%). Multi-cloud: cost comparison across clouds. Kubernetes: cluster autoscaler, node pools, spot/preemptible nodes. Commitments: most savings come from commitments.</p>"),
    ],[F("AWS Cost Optimization","https://aws.amazon.com/aws-cost-management/","Cost management tools"),F("FinOps Foundation","https://www.finops.org/","FinOps best practices")]),

    # === PROGRAMMING LANGUAGES (4) ===
    ("Rust Programming", "rust-programming.html", "Systems programming with Rust -- ownership, borrowing, lifetimes, and concurrency.", "Programming Languages", "fab fa-rust", [
        Q("Ownership & Borrowing", "<p>Rust: memory-safe without GC. Ownership: each value has one owner. Move: assigning transfers ownership. Borrowing: &T (immutable reference), &mut T (mutable reference, exclusive). Lifetimes: 'a -- annotate how long references are valid. Lifetime elision: compiler infers common patterns. String vs &str: String (owned, heap), &str (slice, reference). Struct: struct User { name: String, age: u32 }. Enum: enum Option<T> { None, Some(T) }, enum Result<T,E> { Ok(T), Err(E) }. Pattern matching: match, if let. Methods: impl User { fn new(name: &str) -> Self { ... } }.</p>"),
        Q("Concurrency & Eco", "<p>Threads: std::thread::spawn, channels (std::sync::mpsc), Mutex, Arc (atomic reference counting). Send + Sync traits: auto-implemented for types safe to transfer/share between threads. Async: async/await with tokio or async-std. Cargo: package manager -- cargo new, build, run, test, clippy (linter), rustfmt (formatter). Crates: crates.io -- community packages. serde: serialization/deserialization. rayon: data parallelism. error handling: Result<T,E>, ? operator. panic! vs Result. Testing: #[test], assert!, #[should_panic]. Popular crates: clap (CLI), actix-web/axum (web), diesel/sqlx (DB), tokio (async). Unsafe: unsafe code for FFI, raw pointers. FFI: extern C. Build systems: Cargo workspaces, build.rs. Embedded: no_std for bare-metal. WASM: wasm-pack for web.</p>"),
    ],[F("Rust Book","https://doc.rust-lang.org/book/","The Rust Programming Language"),F("Rust by Example","https://doc.rust-lang.org/stable/rust-by-example/","Learn Rust through examples")]),
    ("Go Programming", "go-programming.html", "Go language -- concurrency, interfaces, tooling, and web development.", "Programming Languages", "fab fa-golang", [
        Q("Concurrency & Types", "<p>Goroutines: go func() -- lightweight thread. Channels: ch := make(chan int) -- communicate between goroutines. Select: wait on multiple channel operations. WaitGroup: sync.WaitGroup. Mutex: sync.Mutex. Struct: type User struct { Name string; Age int }. Methods: func (u User) Greet() string. Interfaces: type Greeter interface { Greet() string }. Satisfied implicitly. Error: type error interface { Error() string }. Multiple return: func div(a,b int) (int, error). Defer: deferred function calls (cleanup). Pointers: *T vs T. Slice: dynamic array. Map: map[string]int. Range: for k, v := range map.</p>"),
        Q("Tooling & Web", "<p>Go tool: go build, test, fmt, vet, mod, get. go mod: modules (go.mod, go.sum). Testing: _test.go files, go test -v, sub tests, table-driven tests. Benchmarks: func BenchmarkXxx(b *testing.B). pprof: profiling. net/http: ServeMux, Handler, middleware. Popular frameworks: Gin, Echo, Fiber (web), GORM (ORM), sqlx (DB), chi (router). json: encoding/json. Context: request-scoped values, cancellation, deadlines. Template: text/template, html/template. io.Reader/Writer: interface patterns. CLI: os.Args, flag, cobra. HTTP client: net/http client with timeout, transport. Graceful shutdown: signal.Notify, server.Shutdown. Microservices: standard lib + protobuf/gRPC. Docker: scratch or distroless base images. Cross-compile: GOOS=linux GOARCH=amd64. Static binary: CGO_ENABLED=0.</p>"),
    ],[F("Go Docs","https://go.dev/doc/","Official Go documentation"),F("Go by Example","https://gobyexample.com/","Learn Go through examples")]),
    ("Python Advanced", "python-advanced.html", "Advanced Python -- decorators, generators, context managers, async, and metaprogramming.", "Programming Languages", "fab fa-python", [
        Q("Advanced Features", "<p>Decorators: @decorator, wraps(f), decorator with args. Use: logging, timing, auth, caching. Generators: yield, generator expressions, send(), throw(), close(). Use: streaming, infinite sequences, coroutines. Context managers: with statement, __enter__/__exit__, contextlib.contextmanager. Use: file handles, locks, DB connections. Metaclasses: type() as metaclass, __new__, __init_subclass__. Use: ORMs (SQLAlchemy), validation. Descriptors: __get__, __set__, __delete__ -- property, classmethod, staticmethod. Abstract base classes: ABC, @abstractmethod. Operator overloading: __add__, __eq__, __repr__, __str__, __getitem__. Slots: __slots__ for memory optimization. Dataclasses: @dataclass (auto __init__, __repr__, __eq__). Typing: type hints, generics (List[T]), Protocol (structural subtyping), TypedDict, Literal, Final.</p>"),
        Q("Async & Performance", "<p>asyncio: async/await, event loop, tasks, futures. Coroutines: async def, await. awaitable: await coroutine, task, future. Async context managers: async with. Async iterators: async for. asyncio.gather: run concurrently. aiohttp: async HTTP. asyncpg: async PostgreSQL. Celery: distributed task queue (Redis/RabbitMQ broker). Performance: cProfile, py-spy (sampling profiler), memory_profiler. C extensions: Cython, cffi, C extension modules. Numba: JIT compiler for numeric code. Multiprocessing: Process, Pool, shared memory, Queue. Threading: GIL limits CPU-bound threads, use for I/O. Subprocess: run external commands. Packaging: setuptools, pyproject.toml, wheel. uv: fast Rust-based pip. pytest: fixtures, parametrize, mock monkeypatch. GIL: Global Interpreter Lock -- use multiprocessing for CPU work.</p>"),
    ],[F("Python Docs","https://docs.python.org/3/","Official Python documentation"),F("Real Python","https://realpython.com/","Python tutorials")]),
    ("Bash & Shell Scripting", "bash-shell-scripting.html", "Advanced shell scripting -- POSIX, Zsh, Fish, and shell automation patterns.", "Programming Languages", "fas fa-terminal", [
        Q("POSIX & Portable Scripts", "<p>Shebang: #!/bin/sh for POSIX, #!/bin/bash for bash-specific. Strict mode: set -euo pipefail. Parameter expansion: ${var:-default}, ${var:?error}, ${var#prefix}, ${var%suffix}, ${var/pattern/replacement}. Arithmetic: $((expr)). Arrays: arr=(a b c), ${arr[@]}, ${#arr[@]} (bash/zsh). Brace expansion: {a,b,c}, {1..10}. Process substitution: diff <(cmd1) <(cmd2). Here-docs: cat << EOF ... EOF. Here-strings: cat <<< \"string\". IFS: Internal Field Separator control splitting. Read: while IFS= read -r line; do done < file. Trap: trap 'cleanup' EXIT ERR SIGINT. Test: [[ condition ]] (bash) vs [ condition ] (POSIX). Globbing: **, extended glob (shopt -s extglob). Regular expressions: [[ $var =~ regexp ]] (bash).</p>"),
        Q("Zsh & Fish", "<p>Zsh: oh-my-zsh, zgen, powerlevel10k prompt. Features: autocd, extended glob (x, s), completion system, shared history, suffix aliases. Associative arrays: declare -A arr. Fish: fish shell -- different syntax (if ... end, for ... end), web-based config (fish_config), autosuggestions. Nushell: structured shell (data as tables). Shellcheck: static analysis. Shell style: use functions, avoid subshells, quote variables, use local scope. fzf: fuzzy finder (ctrl+R, ctrl+T, alt+C). ripgrep/ag: fast grep. fd: find replacement. bat: cat with syntax highlighting. htop: process viewer. jq: JSON query CLI. yq: YAML/XML/TOML query. Script patterns: argument parsing (getopts, argparse), logging functions, exit codes, temp files (mktemp). Shell vs Python: Python for complex, shell for simple file/process tasks.</p>"),
    ],[F("Bash Reference","https://www.gnu.org/software/bash/manual/","Bash reference manual"),F("ShellCheck","https://www.shellcheck.net/","Shell script linting")]),

    # === ARCHITECTURE (5) ===
    ("Microservices Architecture", "microservices-architecture.html", "Microservices -- design, communication, data management, and deployment.", "Architecture", "fas fa-cubes", [
        Q("Design & Communication", "<p>Microservices: single responsibility, independently deployable. Bounded context: domain-driven design (DDD). Service boundaries: align to business capabilities (orders, payments, inventory). Inter-service communication: Synchronous (REST, gRPC -- request/reply). gRPC: Protocol Buffers, HTTP/2, streaming -- stub/skeleton generation. Asynchronous: message queues (Kafka, RabbitMQ), event-driven. API Gateway: single entry point -- auth, routing, rate limiting, aggregation (BFF pattern -- Backend For Frontend). Service discovery: DNS, Consul, Kubernetes DNS. Resiliency: circuit breaker (Resilience4j, Hystrix), retry, timeout, bulkhead. Observability: distributed tracing (Jaeger, Zipkin -- trace ID propagation). Health checks: /health, /ready liveness probes.</p>"),
        Q("Data & Deployment", "<p>Database per service: each service owns its data (no shared DB). Eventual consistency: Saga pattern (choreography -- events, orchestration -- coordinator). CQRS: separate read/write models. Event sourcing: store events, derive current state. API composition: aggregate data from multiple services. Strangler Fig pattern: gradually migrate monolith to microservices. Deployment: containers (Docker), orchestration (K8s, Nomad). CI/CD: each service has its own pipeline. Canary deployments: gradual rollout. Blue/green: switch between environments. Service mesh: Istio, Linkerd -- traffic management, mTLS, observability, circuit breaker. Challenges: network latency, distributed transactions, testing complexity, debugging, data consistency. Monolith-first: start with monolith, extract microservices when needed. When NOT to use: small team, simple domain, early stage, no scaling need.</p>"),
    ],[F("Microservices.io","https://microservices.io/","Patterns by Chris Richardson"),F("Building Microservices","https://samnewman.io/books/building-microservices/","Sam Newman's book")]),
    ("Event-Driven Architecture", "event-driven-architecture.html", "Event-driven design -- events, brokers, CQRS, and event sourcing.", "Architecture", "fas fa-bolt", [
        Q("Events & Brokers", "<p>Event-driven: services communicate via events (not direct calls). Event: something that happened (OrderPlaced, PaymentReceived). Event schema: CloudEvents specification (id, source, specversion, type, datacontenttype). Brokers: Apache Kafka (partitioned, persistent, replay, high throughput), RabbitMQ (AMQP, flexible routing, low latency), AWS SQS/SNS, Google Pub/Sub, Azure Event Hubs. Kafka: topics, partitions, consumer groups, offset management, log compaction, exactly-once semantics. Producer: sends to topic (key -> partition). Consumer: reads from partition, advances offset. Schema Registry: Avro, Protobuf -- schema evolution, compatibility. Dead letter topic: failed messages. Idempotent consumers: handle duplicate events. Event ordering: partition key ensures per-key ordering. Exactly-once: idempotent producer + transactional API. KStreams/KSQL: stream processing, queries. Debezium: CDC (change data capture) from databases to Kafka.</p>"),
        Q("CQRS & Event Sourcing", "<p>CQRS: Command Query Responsibility Segregation -- separate write model (commands) from read model (queries). Commands: change state (CreateOrder). Queries: read state without side effects. Benefits: optimize read/write independently, scale separately. Event sourcing: store all changes as events, current state = aggregate of events. Event store: append-only log (Kafka, EventStoreDB). Aggregate: entity that applies events to rebuild state. Projections: read models built from event stream. Snapshots: periodic state save for faster rebuild. Sagas: distributed transactions -- sequence of local transactions with compensating actions. Choreography saga: each service publishes events, others react. Orchestration saga: coordinator tells services what to do. Axon Framework: Java CQRS/ES framework. Eventuate: CQRS/ES for microservices. Challenges: eventual consistency, complexity, replay, schema evolution. When to use: audit trails, complex state, temporal queries, collaborative domains.</p>"),
    ],[F("Kafka Docs","https://kafka.apache.org/documentation/","Apache Kafka documentation"),F("CQRS by Martin Fowler","https://martinfowler.com/bliki/CQRS.html","CQRS explained")]),
    ("Domain-Driven Design", "domain-driven-design.html", "DDD -- ubiquitous language, bounded context, aggregates, and tactical patterns.", "Architecture", "fas fa-sitemap", [
        Q("Strategic Design", "<p>DDD: focus on domain model (not data) -- Eric Evans. Ubiquitous language: common terms shared by devs and domain experts. Bounded context: explicit boundary where model applies. Context map: relationships between contexts (partnership, shared kernel, customer-supplier, conformist, anti-corruption layer, open-host service, published language). Core domain: most important, competitive advantage. Supporting subdomain: essential but not core. Generic subdomain: off-the-shelf (auth, payments). Strategic design: identify bounded contexts, define relationships, focus on core domain. Anti-corruption layer: translate between contexts (adapter pattern). Continuous integration: keep models in sync within context.</p>"),
        Q("Tactical Patterns", "<p>Entity: identity, mutable (User, Order id). Value Object: immutable, equality by value (Money, Address, Color). Aggregate: cluster of entities/VOs with a root (Order -> OrderItems, root = Order). Aggregate root: only root can be referenced, consistency boundary. Repository: collection-like abstraction for aggregates (interface). Domain service: stateless operations that don't belong to entity/VO. Domain events: events within the domain (OrderPlaced). Factory: create complex aggregates. Specification: business rules (isEligibleForDiscount). Application service: orchestrate use cases (thin layer). Infrastructure: persistence, messaging, external services. Layered architecture: Presentation -> Application -> Domain -> Infrastructure. Hexagonal (ports & adapters): domain at core, adapters for I/O. Event storming: collaborative workshop to model domain. DDD + microservices: each bounded context = possible microservice. Ubiquitous language in code: class names match domain terms.</p>"),
    ],[F("DDD by Eric Evans","https://www.domainlanguage.com/","Domain-Driven Design book"),F("DDD Quickly","https://www.infoq.com/minibooks/domain-driven-design-quickly/","Free DDD mini-book")]),
    ("REST API Design Patterns", "rest-api-design-patterns.html", "REST API patterns -- HATEOAS, pagination, filtering, error handling.", "Architecture", "fas fa-plug", [
        Q("Resource Design", "<p>REST: representational state transfer. Resources: nouns (/users, /orders/{id}). Naming: plural, lowercase, kebab-case (order-items). Actions: HTTP methods (POST, GET, PUT, PATCH, DELETE). Relationships: /users/{id}/orders (sub-resources). Status: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 409 Conflict, 422 Unprocessable, 429 Too Many, 500 Internal. Pagination: cursor-based (next_token, preferred for consistency) vs offset/limit (page, per_page). Filtering: ?status=active&created_after=2024-01-01. Sorting: ?sort=created_at,-name (desc with -). Sparse fields: ?fields=id,name,email (reduce payload). HATEOAS: links in responses -- rel: self, next, prev, related. Content negotiation: Accept header (application/vnd.api+json). Versioning: URL (/v1/users), header (Accept: version=1), or no version (evolve API).</p>"),
        Q("Error Handling & Docs", "<p>Error response (RFC 7807 Problem Details): { type, title, status, detail, instance }. Validation: JSON Schema request/response validation. Idempotency: Idempotency-Key header for POST/PATCH (retry safety). Bulk operations: batch endpoints (POST /batch), bulk creation via array. Async operations: 202 Accepted + Location header pointing to status endpoint. Webhooks: event callbacks -- register URL, POST event payload, retry on failure. Rate limiting: headers (X-RateLimit-Limit, Remaining, Reset), 429 response. Cache: ETag, Last-Modified, Cache-Control. Security: HTTPS, CORS, CSP, rate limiting. Documentation: OpenAPI 3.0 (YAML/JSON), Swagger UI, ReDoc, Stoplight. OpenAPI: paths, methods, parameters, request bodies, responses, schemas (JSON Schema). Code generation: OpenAPI Generator, Swagger Codegen. Testing: contract testing (Pact), integration tests, Postman collections. SDKs: auto-generate client SDKs from OpenAPI.</p>"),
    ],[F("OpenAPI Spec","https://spec.openapis.org/oas/v3.0.3/","OpenAPI specification"),F("RESTful API Design","https://restfulapi.net/","REST API design principles")]),
    ("GraphQL in Practice", "graphql-practice.html", "GraphQL -- schema design, resolvers, subscriptions, and performance.", "Architecture", "fas fa-project-diagram", [
        Q("Schema & Queries", "<p>GraphQL: query language, single endpoint. Schema: type Query { users: [User!]! user(id: ID!): User type User { id: ID! name: String posts: [Post!]! } }. Queries: { users { id name } }. Arguments: { user(id: \"1\") { name email } }. Mutations: mutation { createUser(input: { name: \"Alice\" }) { id name } }. Input types: input CreateUserInput { name: String! email: String! }. Subscriptions: real-time via WebSocket. Fragments: reusable field sets. Variables: query($id: ID!) { user(id: $id) { name } }. Directives: @include(if:), @skip(if:), @deprecated. Interfaces: shared fields across types. Unions: type SearchResult = User | Post. Enums: enum Role { ADMIN USER }.</p>"),
        Q("Resolvers & Perf", "<p>Resolvers: functions per field -- root types (Query, Mutation, Subscription) and field resolvers. DataLoader: batching + caching (solve N+1 problem). Batching: DataLoader loads multiple keys in one batch. Caching: per-request cache. Mutations: return updated data. Error handling: errors array in response, partial success. Auth: context (auth token), field-level permissions (directives or wrapper). Complexity analysis: limit query depth/complexity to prevent abuse. Query cost: weight fields, reject expensive queries. Pagination: connection pattern (edges, node, pageInfo, cursor). Relay spec: global IDs, cursor-based pagination, mutations. Persisted queries: whitelist allowed queries. Apollo: client (cache, optimistic UI, subscriptions), server (schema stitching, federation). Federation: compose multiple GraphQL services. GraphQL vs REST: GraphQL (client-specified fields, single endpoint), REST (server-defined responses, multiple endpoints). Tools: GraphiQL, Apollo Studio, GraphQL Playground. Codegen: generate TypeScript types from schema. Security: depth limiting, rate limiting, auth, validation.</p>"),
    ],[F("GraphQL Docs","https://graphql.org/learn/","GraphQL learning resources"),F("Apollo Docs","https://www.apollographql.com/docs/","Apollo GraphQL platform")]),

    # === CONTAINER IMAGE OPTIMIZATION (2) ===
    ("Dockerfile Best Practices", "dockerfile-best-practices.html", "Build efficient Docker images -- multi-stage, caching, security, and size optimization.", "DevOps", "fab fa-docker", [
        Q("Multi-Stage & Caching", "<p>Multi-stage builds: multiple FROM statements -- build stage (SDK, compilers) and runtime stage (minimal base). Example: FROM golang:1.22 AS builder; WORKDIR /app; COPY go.mod go.sum .; RUN go build -o app .; FROM alpine:3.20; COPY --from=builder /app/app .; CMD ['./app']. Layer caching: order matters -- put infrequently changed layers first (package installs, dependency downloads). Combine RUN commands with && and cleanup in same layer. Use .dockerignore: exclude node_modules, .git, __pycache__, build artifacts. Base images: Alpine (5MB), distroless (Google -- no shell, no package manager), scratch (empty). Slim images: reduce size by removing unnecessary files. Use --link for COPY/ADD (better caching, independent layers). Use --chown for permissions. Use ARG for build-time variables. Use LABEL for metadata. BuildKit: newer builder (DOCKER_BUILDKIT=1) -- parallel, cache mounts, secrets, SSH mounts. COPY vs ADD: COPY preferred (just copies), ADD supports tar auto-extraction and URLs.</p>"),
        Q("Security & Images", "<p>Run as non-root: USER appuser; RUN addgroup -S appgroup && adduser -S appuser -G appgroup. Avoid latest tag: use specific version tags (alpine:3.20). Scan: docker scout, Trivy, Snyk, Grype. Minimal packages: apk add --no-cache, apt-get install --no-install-recommends. Security: HEALTHCHECK instruction (Docker checks container health), --read-only rootfs, drop capabilities (--cap-drop=ALL --cap-add=NET_BIND_SERVICE). Distroless: gcr.io/distroless/base (glibc), distroless/static (no libs). Use --squash (experimental) to flatten layers. Secrets: --mount=type=secret in BuildKit. Cache mounts: --mount=type=cache,target=/root/.cache/pip. Export: docker save/load, docker push/pull to registry. Image naming: registry/image:tag. OCI artifacts: store arbitrary files in registry. Multi-architecture: docker buildx build --platform linux/amd64,linux/arm64. SBOM: software bill of materials. Attestations: in-toto provenance. Image signing: cosign (Sigstore), Docker Content Trust. Base image updates: dependabot, Renovate for Dockerfile. Reducing layers: RUN commands combined, but don't over-optimize (more layers = worse cache invalidation).</p>"),
    ],[F("Dockerfile Best Practices","https://docs.docker.com/develop/dev-best-practices/","Official Dockerfile guide"),F("Docker Scout","https://docs.docker.com/scout/","Container security scanning")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials (p3f)!")
