#!/usr/bin/env python3
"""Generate ~23 tutorials — More Windows, More Mobile, Extras."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === MORE WINDOWS (4) ===
    ("Windows Deployment (MDT/SCCM)", "windows-deployment.html", "Deploy Windows at scale -- MDT, SCCM, imaging, PXE boot.", "Windows", "fab fa-microsoft", [
        Q("MDT", "<p>MDT: free Windows deployment automation. Components: Deployment Workbench, task sequences, drivers, apps, boot images. Process: import WIM -> drivers -> task sequence -> update share -> boot ISO. WinPE: boot from PXE or USB. CustomSettings.ini: config database. Driver management: total control drivers by model. PXE boot: WDS to network boot WinPE. USMT: migrate user profiles. Refresh: reinstall while preserving data. Zero-touch: fully automated. Lite-touch: minimal interaction.</p>"),
        Q("SCCM & Imaging", "<p>SCCM (MECM): enterprise deployment. OS deployment: task sequences, PXE, software center. Boot images: WinPE with drivers. Thick vs thin images: pre-installed apps vs default WIM. Driver packages: auto-apply by model. State migration: USMT capture/restore. PXE: DHCP + WDS + IP helpers. Multicast: deploy to many clients. SMSTS.log: deployment logs. Windows ADK: deployment tools. Autopilot: cloud-native zero-touch. Intune: MDM. Co-management: SCCM + Intune. Provisioning packages: Windows Configuration Designer.</p>"),
    ],[F("MDT Docs","https://learn.microsoft.com/en-us/windows/deployment/deploy-windows-mdt/","MDT guide"),F("SCCM Docs","https://learn.microsoft.com/en-us/mem/configmgr/","SCCM docs")]),
    ("Windows Performance & Troubleshooting", "windows-performance.html", "Windows performance tuning, diagnostics, and recovery tools.", "Windows", "fas fa-gauge-high", [
        Q("Performance Tools", "<p>perfmon: data collector sets, counters, alerts. resmon: real-time CPU, memory, disk, network. Process Explorer: detailed process info, handles, DLLs. procmon: file, registry, network, process activity. XPerf/WPR: ETW traces (CPU, disk, DPC, power). WPA: analyze ETW traces. RAMMap: memory breakdown. Sysinternals Suite: 70+ tools. powercfg: powercfg /energy, /batteryreport. SFC: sfc /scannow. DISM: dism /online /cleanup-image /restorehealth. chkdsk: chkdsk c: /f /r.</p>"),
        Q("Troubleshooting", "<p>WinRE: recovery drive, advanced startup. Safe mode: minimal drivers. Driver verifier: verifier.exe. BSOD: analyze minidump with WinDbg, BlueScreenView. Common codes: CRITICAL_PROCESS_DIED, SYSTEM_SERVICE_EXCEPTION, MEMORY_MANAGEMENT. Memory diag: mdsched.exe, MemTest86. System restore: restore points. Reset: keep files or clean. Clean install: boot USB, fresh install. Network: ipconfig, netsh winsock reset, nslookup. Windows Update: Disk Cleanup, check log.</p>"),
    ],[F("Sysinternals","https://learn.microsoft.com/en-us/sysinternals/","Windows utilities"),F("WinDbg","https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/","Debugger docs")]),
    ("Windows Automation (PowerShell DSC)", "windows-automation.html", "Windows automation -- PowerShell remoting, DSC, scheduled tasks.", "Windows", "fab fa-microsoft", [
        Q("PowerShell Remoting", "<p>WinRM: Enter-PSSession (interactive), Invoke-Command (script block). JEA: constrained endpoints. PSJobs: background jobs. ScheduledJob: Register-ScheduledJob. Profiles: $PROFILE per user/host. Script signing: Set-ExecutionPolicy, Authenticode. Modules: .psm1, manifests. PowerShellGet: Find/Install/Publish-Module. PS7: cross-platform, ForEach-Object -Parallel, ternary, null coalescing. Error: try/catch, -ErrorAction. Best: verbose/debug streams, WhatIf support.</p>"),
        Q("DSC", "<p>DSC: declarative config. LCM: push or pull mode. Config: Configuration WebServer { Node localhost { WindowsFeature IIS { Ensure = 'Present' } } }. Resources: File, Registry, Service, WindowsFeature, User, Script, Environment. Pull server: central, nodes pull config. Push: Start-DscConfiguration. Azure Automation: cloud pull + reporting. DSC logging: event log. MOF: compiled config. Test: Test-DscConfiguration. xDscResources: community extensions. DevOps: CI/CD apply config. Chocolatey: package management. winget: Microsoft package manager.</p>"),
    ],[F("DSC Docs","https://learn.microsoft.com/en-us/powershell/dsc/","DSC documentation"),F("PowerShell Gallery","https://www.powershellgallery.com/","Community modules")]),
    ("Windows Intune & Endpoint Manager", "windows-intune.html", "Cloud device management -- Microsoft Intune, Autopilot, compliance.", "Windows", "fab fa-microsoft", [
        Q("Intune MDM", "<p>Intune: cloud MDM/MAM. Enrollment: Azure AD join, Autopilot, BYOD. Config profiles: WiFi, VPN, email, certs, restrictions. Compliance: BitLocker, password, firewall, Defender, OS version. Conditional Access: only compliant devices. Apps: required, available, managed (App Protection Policies). Updates: Windows Update for Business rings. Endpoint security: antivirus, firewall, BitLocker, ASR. Scripts: PowerShell via Intune. Proactive remediations: detect/fix issues. Autopilot: user-driven, self-deploying, pre-provisioned. ESP: block use until ready.</p>"),
        Q("Endpoint Manager", "<p>MEM: Intune + ConfigMgr unified. Co-management: split workloads. Tenant attach: ConfigMgr in cloud. Cloud attach: enable cloud features. Autopilot: hardware hash upload. Group tagging: dynamic profiles. Windows 365: Cloud PC. Microsoft Tunnel: VPN gateway. Endpoint analytics: boot perf, app reliability. Security baselines: CIS, NIST. Defender for EDR: integrated. Graph API: manage via REST. Licensing: Intune Plan 1 (E3/E5), Plan 2.</p>"),
    ],[F("Intune Docs","https://learn.microsoft.com/en-us/mem/intune/","Intune docs"),F("Autopilot","https://learn.microsoft.com/en-us/autopilot/","Autopilot guide")]),

    # === MORE MOBILE (4) ===
    ("Mobile Game Dev (Unity Mobile)", "mobile-game-dev.html", "Develop mobile games -- Unity optimization, touch controls, publishing.", "Mobile", "fab fa-unity", [
        Q("Mobile Optimization", "<p>Target 30-60 FPS mid-range. Rendering: reduce draw calls, texture atlases, LODs, occlusion culling. Lighting: baked lightmaps, no real-time shadows. Shaders: mobile variants. Poly count: <100k tris on screen. Resolution: adaptive scaling. Post-processing: minimal/off. Profiling: Unity Profiler, Xcode Instruments, Android Studio. Memory: ASTC/ETC2 compression, asset bundles, object pooling. Battery: reduce CPU/GPU, targetFrameRate. Install size: <150MB initial. Screen: safe areas, notch, aspect ratios.</p>"),
        Q("Touch & Publishing", "<p>Touch: Unity Input System, multi-touch, gestures (tap, swipe, pinch). On-screen: virtual joystick, buttons. UI: Canvas scaling, safe area. Orientation: portrait or landscape. Build: Android (IL2CPP, ARM64), iOS (Metal, provisioning). Ads: AdMob, Unity Ads. IAP: Unity IAP. Push: FCM, APNs. Testing: TestFlight, internal track. ASO: screenshots, keywords. Rating: In-app review prompts. Performance: Application.targetFrameRate.</p>"),
    ],[F("Unity Mobile Optimization","https://learn.unity.com/tutorial/performance-optimization","Unity mobile guide"),F("Unity Mobile Touch","https://docs.unity3d.com/Manual/MobileTouch.html","Touch input docs")]),
    ("Mobile DevOps (Fastlane)", "mobile-devops-fastlane.html", "Mobile CI/CD -- Fastlane, automated signing, testing, deployment.", "Mobile", "fas fa-repeat", [
        Q("Fastlane Setup", "<p>Fastlane: automate mobile builds. Install: gem install fastlane. Lanes: gradle(task: 'assembleRelease'), gym (build iOS), scan (test), match (signing), pilot (TestFlight), supply (Play Store), deliver (App Store). Android signing: upload_to_play_store. iOS signing: match (cert + profiles in Git repo). Environment: .env for secrets. Plugins: fastlane add_plugin. Build numbers: increment_build_number. Screengrab: localized screenshots. Frameit: device frames.</p>"),
        Q("CI Integration", "<p>GitHub Actions: setup-ruby, fastlane lane. GitLab CI: bundle exec fastlane. CircleCI: orb. Bitrise: mobile CI. Match: iOS code signing in Git (encrypted). API keys: App Store Connect API (p8), Google Play service account. Artifacts: APK, AAB, IPA. Versioning: git tag + semantic. CI runners: macOS (iOS), Linux (Android). Dependency cache: CocoaPods, Gradle. Release: fastlane + CI + changelog. Testing: unit, UI, Firebase Test Lab.</p>"),
    ],[F("Fastlane Docs","https://docs.fastlane.tools/","Mobile automation"),F("Match","https://docs.fastlane.tools/actions/match/","iOS code signing")]),
    ("Mobile Analytics & Crash Reporting", "mobile-analytics-crash.html", "App analytics and crash reporting -- Firebase, Sentry.", "Mobile", "fas fa-chart-bar", [
        Q("Analytics", "<p>Firebase Analytics: free unlimited events. Events: predefined (purchase, login) and custom. User properties: language, country, subscription. Audiences: segment users. Funnels: user flow analysis. Retention: D1, D7, D30. Revenue: IAP, subs, ads. DAU/MAU. Mixpanel: product analytics. Amplitude: behavioral. Privacy: GDPR consent, data retention, anonymize IP. BigQuery: raw export. Attribution: install source. A/B testing: Firebase Remote Config.</p>"),
        Q("Crash Reporting", "<p>Crashlytics: real-time crash reporting. Custom keys/logs: context before crash. User identifiers: setUserId. Issues: grouped by stack trace, frequency. Sentry: cross-platform. dSYM: iOS symbol upload. ProGuard mapping: Android. ANR: Android Not Responding. OOM: iOS Jetsam. Breadcrumbs: user actions before crash. Performance: Firebase Performance (network, screen render). Crash rate target: <0.1%. Alerts: email, Slack, PagerDuty. Session replay: LogRocket, Smartlook.</p>"),
    ],[F("Firebase Crashlytics","https://firebase.google.com/docs/crashlytics","Crash reporting"),F("Sentry","https://docs.sentry.io/","Error monitoring")]),
    ("Mobile Accessibility", "mobile-accessibility.html", "Make mobile apps accessible -- screen readers, contrast, touch targets.", "Mobile", "fas fa-universal-access", [
        Q("Screen Readers", "<p>iOS VoiceOver: isAccessibilityElement, accessibilityLabel, hint, value, traits. SwiftUI: .accessibilityLabel(), .accessibilityHint(), .accessibilityAddTraits(). Grouping: .accessibilityElement(children: .combine). Rotor: custom navigation. Android TalkBack: contentDescription, importantForAccessibility, focusable. Live regions: accessibilityLiveRegion. Flutter: Semantics widget, label, hint, button, header. React Native: accessibilityLabel, accessibilityRole. Keyboard: tab order, focus indicators.</p>"),
        Q("Visual & Motor", "<p>Contrast: WCAG AA 4.5:1 normal, 3:1 large. Dynamic Type: UIFontMetrics, SP units. Touch targets: 44x44pt iOS, 48x48dp Material. prefers-reduced-motion: disable parallax. Reduced transparency: adapt designs. Bold text: adjust layout. Error: clear messages, not just red. Focus: move to new content. Testing: XCTest, Espresso, Accessibility Scanner, Accessibility Inspector. WCAG 2.1 POUR: Perceivable, Operable, Understandable, Robust. Captions: video content.</p>"),
    ],[F("Apple Accessibility","https://developer.apple.com/accessibility/","iOS accessibility"),F("Android Accessibility","https://developer.android.com/guide/topics/ui/accessibility","Android accessibility")]),

    # === EXTRAS (15) ===
    ("Quantum Computing", "quantum-computing.html", "Quantum computing -- qubits, gates, algorithms, and quantum programming.", "Extras", "fas fa-atom", [
        Q("Qubits & Gates", "<p>Qubit: superposition of |0> and |1>. Bloch sphere: qubit state. Gates: Pauli X/Y/Z, Hadamard, CNOT, Toffoli, SWAP. Superposition: probability amplitude. Entanglement: EPR pair, correlated qubits. Measurement: collapse to 0 or 1. No-cloning: cant copy quantum state. Decoherence: environmental interaction. Error correction: Shor code, surface code. NISQ: 50-1000 noisy qubits. Physical qubits: superconducting (IBM), trapped ions (IonQ), photonic (Xanadu).</p>"),
        Q("Algorithms & Tools", "<p>Shor: factor large numbers (break RSA). Grover: search sqrt speedup. QFT: period finding. Applications: crypto, drug discovery, optimization, ML. Hybrid: VQE, QAOA (quantum + classical). Programming: Qiskit (IBM), Cirq (Google), PennyLane, Q#, Amazon Braket. Simulators: run on classical. Quantum-safe: post-quantum crypto (CRYSTALS-Kyber, Dilithium). Timeline: error-corrected 2030s.</p>"),
    ],[F("IBM Quantum","https://quantum-computing.ibm.com/","IBM Quantum"),F("Qiskit","https://qiskit.org/documentation/","Quantum SDK")]),
    ("Blockchain & Web3", "blockchain-web3.html", "Blockchain -- smart contracts, DeFi, consensus, Web3 apps.", "Extras", "fab fa-bitcoin", [
        Q("Blockchain", "<p>Blocks: header + transactions, SHA-256 hash chain. Consensus: PoW (Bitcoin), PoS (Ethereum), DPOS, PBFT. Mining: ASIC (BTC), GPU (pre-merge ETH). Forks: hard (BTC/BCH), soft (SegWit). Accounts: EOA (private key) vs contract. Gas: Ethereum fees, EIP-1559. L2: Rollups (Optimistic, ZK), sidechains (Polygon), Lightning Network. L1: Solana, Avalanche, Polkadot, Cosmos.</p>"),
        Q("Smart Contracts", "<p>Solidity: contract MyContract { }. EVM: bytecode execution. ERCs: ERC-20 (tokens), ERC-721 (NFTs), ERC-1155. OpenZeppelin: audited contracts. Hardhat/Foundry: dev tools. ethers.js/wagmi: frontend. Web3: MetaMask, WalletConnect. DeFi: Aave (lending), Uniswap (DEX). Stablecoins: USDC, DAI. Oracles: Chainlink. DAO: governance tokens. IPFS/Arweave: decentralized storage. Security: reentrancy, flash loans. Regulation: SEC, MiCA.</p>"),
    ],[F("Solidity Docs","https://docs.soliditylang.org/","Solidity language"),F("Ethereum Docs","https://ethereum.org/en/developers/docs/","Ethereum docs")]),
    ("Machine Learning Basics", "machine-learning-basics.html", "ML fundamentals -- supervised, unsupervised, neural networks.", "Extras", "fas fa-brain", [
        Q("Supervised Learning", "<p>Regression: linear, random forest, gradient boosting. Classification: logistic regression, SVM, decision trees, KNN, Naive Bayes. Overfitting: cross-validation, regularization (L1/L2), more data. Train/test split: 80/20, k-fold. Metrics: accuracy, precision, recall, F1, ROC AUC (classification); MSE, MAE, R2 (regression). Libraries: scikit-learn, XGBoost, LightGBM. Feature engineering: scaling, one-hot, TF-IDF. Bias-variance tradeoff.</p>"),
        Q("Deep Learning", "<p>Neural nets: input -> hidden -> output. Activation: ReLU, sigmoid, tanh, softmax. Loss: MSE, cross-entropy. Optimizers: SGD, Adam, RMSprop. Regularization: dropout, batch norm. CNN: images (conv, pool, FC). RNN/LSTM: sequences. Transformers: attention (BERT, GPT). PyTorch: tensor, autograd, nn.Module. TensorFlow/Keras. GPU: CUDA (NVIDIA), TPU, MPS. Transfer learning: fine-tune pretrained. MLOps: MLflow. LLMs: LoRA fine-tuning, RAG.</p>"),
    ],[F("scikit-learn","https://scikit-learn.org/stable/","Python ML"),F("PyTorch","https://pytorch.org/tutorials/","Deep learning")]),
    ("Cybersecurity Red Team", "cybersecurity-red-team.html", "Red team -- pentesting, social engineering, adversary emulation.", "Extras", "fas fa-skull-crossbones", [
        Q("Pentesting", "<p>Recon: OSINT, Shodan, Google dorking, theHarvester. Scanning: nmap, masscan, rustscan. Vuln scan: OpenVAS, Nessus. Web: Burp Suite, OWASP ZAP, sqlmap, ffuf. Exploit: Metasploit, searchsploit. Priv esc: Linux (SUID, sudo, cron), Windows (unquoted path, tokens). AD: BloodHound, CrackMapExec, Mimikatz, Kerberoasting. Pivoting: Chisel, Ligolo-ng. Exfil: DNS tunneling. Reporting: executive + technical + remediation.</p>"),
        Q("Social Engineering", "<p>Phishing: GoPhish. Payload: macro, lnk, HTML smuggling. C2: Cobalt Strike, Sliver, Mythic, Havoc. MITRE ATT&CK: tactics/techniques. Purple team: red+blue. Evasion: obfuscation, AMSI bypass, ETW patching, unhooking EDR. OpSec: proxies, separate infra. Emulation: mimic APT groups. Detection: Sigma, YARA. Labs: Hack The Box, TryHackMe. Certs: OSCP, PNPT, CRTP, OSEP. Kali: pentest distro. Cloud: Pacu (AWS).</p>"),
    ],[F("MITRE ATT&CK","https://attack.mitre.org/","Adversary tactics"),F("OWASP Testing Guide","https://owasp.org/www-project-web-security-testing-guide/","Web security testing")]),
    ("Home Lab", "home-lab.html", "Build a home lab -- servers, networking, virtualization, self-hosted services.", "Extras", "fas fa-server", [
        Q("Hardware", "<p>Hardware: old server (Dell R720), mini PC (NUC), Raspberry Pi. Hypervisor: Proxmox (KVM+LXC), ESXi free, XCP-ng. Storage: TrueNAS SCALE (ZFS), Unraid. Networking: managed switch, pfSense, UniFi AP. UPS: APC, NUT for graceful shutdown. Remote: IPMI (iDRAC, iLO), PiKVM. Proxmox cluster: HA with Ceph. Backups: Proxmox Backup Server, Veeam. Automation: Ansible, Terraform.</p>"),
        Q("Self-Hosted", "<p>Reverse proxy: NPM, Traefik, Caddy. DNS: Pi-hole, AdGuard Home, Unbound. Dashboard: Heimdall, Homer, Homepage. Media: Jellyfin, Sonarr, Radarr, Prowlarr. File: Nextcloud, Syncthing. Passwords: Vaultwarden. Monitoring: Uptime Kuma, Grafana+Prometheus, Netdata. CI/CD: Gitea, Jenkins. Home assistant: Home Automation. Cloud: MinIO (S3). VPN: WireGuard, Tailscale. Wiki: Bookstack, Outline. Identity: Authentik, Authelia. Security: Crowdsec, Fail2ban. Backup: restic, Borg, rclone.</p>"),
    ],[F("r/HomeLab","https://www.reddit.com/r/homelab/","Home lab community"),F("Awesome Selfhosted","https://github.com/awesome-selfhosted/awesome-selfhosted","Self-hosted list")]),
    ("Internet of Things (IoT)", "internet-of-things.html", "IoT -- sensors, MQTT, ESP32, edge computing, and security.", "Extras", "fas fa-microchip", [
        Q("Hardware & Protocols", "<p>MCUs: ESP32, ESP8266, Raspberry Pi Pico W. Sensors: DHT22, BME280, PIR, HC-SR04, BH1750. Actuators: relays, servo, DC motor. Protocols: I2C, SPI, UART, 1-Wire. Wireless: WiFi, BLE, Zigbee, Z-Wave, LoRaWAN, Thread, Matter. MQTT: pub-sub broker (Mosquitto, EMQX), QoS 0/1/2. CoAP: REST-like UDP. Matter: smart home standard.</p>"),
        Q("Platforms & Security", "<p>Platforms: AWS IoT Core, Azure IoT Hub, ThingsBoard, Home Assistant. Firmware: Arduino IDE, PlatformIO, ESP-IDF. OTA: ESP32 OTA, Mender. Edge ML: TensorFlow Lite Micro, Edge Impulse. Security: X.509 certs, secure boot, encrypted storage, signed OTA. Power: ESP32 deep sleep ~10uA. RTOS: FreeRTOS, Zephyr. Connectivity: mesh (Zigbee, Thread). Time: NTP. Data: InfluxDB (time-series). Solar: MPPT, LiFePO4. Pentesting: binwalk, UART, JTAG.</p>"),
    ],[F("ESP-IDF","https://docs.espressif.com/projects/esp-idf/","ESP32 dev framework"),F("MQTT","https://mqtt.org/","MQTT specification")]),
    ("Robotics", "robotics.html", "Robotics -- ROS 2, kinematics, SLAM, navigation, computer vision.", "Extras", "fas fa-robot", [
        Q("ROS 2 & Hardware", "<p>ROS 2: robot middleware. Nodes, topics, services, actions. TF: coordinate frames. URDF: robot model. RViz2: 3D visualization. Gazebo: physics sim. Micro-ROS: for MCUs. DDS: Fast DDS, Cyclone DDS. Robot types: differential drive, mecanum, manipulator. Kinematics: forward/inverse. Sensors: LiDAR, IMU, encoders, camera. Motors: DC+encoder, stepper, BLDC, servo. PID: tune for smooth control. Motor drivers: L298N, ODrive, Dynamixel.</p>"),
        Q("Navigation & Vision", "<p>SLAM: GMapping, Cartographer, RTAB-Map. Nav2: global/local planner, costmap, AMCL. Behavior trees: BT.CPP. Path planning: A*, RRT. Computer vision: OpenCV, YOLO, depth cameras (RealSense, OAK-D). Visual odometry. Manipulation: MoveIt 2 (motion planning, IK). Pick and place. Autonomous driving: Autoware. Simulation: Isaac Sim. Safety: emergency stop. Single-board: Jetson, Raspberry Pi. OS: Ubuntu + ROS 2.</p>"),
    ],[F("ROS 2 Docs","https://docs.ros.org/en/rolling/","Robot Operating System"),F("Nav2","https://navigation.ros.org/","ROS 2 navigation")]),
    ("API Security", "api-security.html", "Secure REST and GraphQL APIs -- auth, rate limiting, OWASP top 10.", "Extras", "fas fa-shield-halved", [
        Q("Auth & Rate Limiting", "<p>Auth: API keys, JWT, OAuth 2.0, mTLS. JWT: short exp (15 min), signed (RS256), validate claims. OAuth flows: Auth Code+PKCE, Client Credentials, Device. Authorization: RBAC, ABAC, scope-based. Rate limiting: token bucket, sliding window. Headers: X-RateLimit-*, Retry-After. API gateway: Kong, APISIX, Tyk, Envoy. CORS: specific origins. CSRF: SameSite, tokens. Idempotency: Idempotency-Key. Input validation: JSON Schema. HSTS: Strict-Transport-Security. Versioning: URL or header.</p>"),
        Q("OWASP Top 10", "<p>API1: BOLA (broken object level auth). API2: Broken Auth. API3: Mass assignment. API4: Resource consumption. API5: Broken function auth. API6: Sensitive business flows. API7: SSRF. API8: Misconfiguration. API9: Shadow APIs. API10: Unsafe consumption. GraphQL: depth limiting, cost analysis. Introspection: disable in prod. Injection: SQL (parameterized), NoSQL, command. WAF: ModSecurity+CRS, Cloudflare, AWS. Secrets: Vault, env vars. Logging: auth failures, denied access. Audit: log all API changes.</p>"),
    ],[F("OWASP API Top 10","https://owasp.org/API-Security/","API security risks"),F("JWT Best Practices","https://auth0.com/blog/10-things-you-should-know-about-tokens/","Token best practices")]),
    ("Web Scraping", "web-scraping.html", "Web scraping -- HTTP requests, HTML parsing, anti-bot bypass.", "Extras", "fas fa-spider", [
        Q("Scraping Tools", "<p>HTTP: requests, aiohttp, httpx. HTML: BeautifulSoup, lxml, selectolax. CSS selectors, XPath. JS rendering: Selenium, Playwright, Puppeteer. Scrapy: spiders, pipelines, middlewares. Async: aiohttp+asyncio. Headers: rotate User-Agent. Rate limiting: polite delays, respect robots.txt. Retries: tenacity, exponential backoff. Sessions: requests.Session for cookies. API scraping: find XHR endpoints. Downloads: stream=True. Caching: requests-cache.</p>"),
        Q("Anti-Bot & Ethics", "<p>CAPTCHA: 2Captcha, Anti-Captcha. reCAPTCHA: v2/v3, Turnstile. Proxies: datacenter (cheap), residential (reliable), mobile. Proxy providers: Bright Data, Oxylabs. Cloudflare: cloudscraper, flare-solverr. Fingerprint: canvas, WebGL, header order. Ethics: check robots.txt, throttle, identify yourself, respect copyright. Legal: public data scraping OK (hiQ vs LinkedIn). Storage: CSV, JSON, SQLite. Dedup: hash content. Pagination: pages, scroll, cursors. Visual scrapers: Octoparse, Portia. Change detection: git diff.</p>"),
    ],[F("BeautifulSoup","https://www.crummy.com/software/BeautifulSoup/bs4/doc/","HTML parser"),F("Scrapy","https://docs.scrapy.org/","Scraping framework")]),
    ("Regex", "regex.html", "Regular expressions -- patterns, groups, lookaheads, applications.", "Extras", "fas fa-code", [
        Q("Patterns", "<p>Literals, metaclasses: . \\d \\w \\s \\b ^ $. Negations: \\D \\W \\S [^a]. Classes: [abc] [a-z] [0-9]. Quantifiers: * + ? {3} {2,5} {3,}. Greedy vs lazy: * vs *?. Anchors: ^ $ \\b \\B. Alternation: cat|dog. Grouping: (abc) capture, (?:abc) non-capture, (?P<name>) named. Backreference: \\1 (?P=name). Flags: g, i, m, s, x, U. Escaping: \\. \\+.</p>"),
        Q("Lookaheads & Use", "<p>Lookahead: (?=pattern), (?!=pattern). Lookbehind: (?<=pattern), (?<!pattern). Common: email (^[\\w.-]+@[\\w.-]+\\.\\w{2,}$), URL, phone, IP, HTML tag, hex color, date. Catastrophic backtracking: avoid nested quantifiers. Atomic groups: (?>pattern). Tools: regex101.com, regexr.com. Applications: validation, parsing, search/replace (sed, grep). Engines: PCRE, POSIX, RE2. In code: Python re, JS RegExp, Java Pattern, Rust regex.</p>"),
    ],[F("Regex101","https://regex101.com/","Regex tester"),F("Regular-Expressions.info","https://www.regular-expressions.info/","Regex reference")]),
    ("Markdown", "markdown.html", "Markdown syntax -- formatting, extended features, documentation.", "Extras", "fab fa-markdown", [
        Q("Core Syntax", "<p>Headings: # to ######. Bold/italic: **text** *text*. Links: [text](url). Images: ![alt](url). Lists: unordered (- * +), ordered (1.). Code: inline (`), block (```). Quotes: >. HR: ---. Tables: | col | col |. Tasks: - [x]. Footnotes: [^1]. Emoji: :smile:. Math: $..$ $$..$$. YAML frontmatter. Strikethrough: ~~. Highlight: ==. Sub/superscript: H~2~O.</p>"),
        Q("Tools & Docs", "<p>Editors: VS Code, Typora, Obsidian, IA Writer. Preview: live, split pane. Extensions: Markdown All in One, markdownlint. SSGs: MkDocs, Docusaurus, Hugo. Docs-as-code: write docs like code, Git, CI/CD. Mermaid diagrams: flowchart, sequence, class, Gantt. Pandoc: convert markdown to PDF, HTML, DOCX, LaTeX. MDX: JSX in markdown. Pandoc: universal converter. Lint: markdownlint. CI: check formatting. Readme: project documentation.</p>"),
    ],[F("Markdown Guide","https://www.markdownguide.org/","Markdown reference"),F("MkDocs","https://www.mkdocs.org/","Markdown documentation")]),
    ("Docker Compose Deep Dive", "docker-compose-deep-dive.html", "Master Docker Compose -- multi-service apps, networking, secrets, production.", "Extras", "fab fa-docker", [
        Q("Compose Features", "<p>Compose file: services, networks, volumes, configs, secrets. Service: image, build, ports, volumes, environment, depends_on. Networks: custom bridge, aliases, IPAM. Volumes: named, bind, tmpfs. Configs: read-only files. Secrets: /run/secrets/. Env vars: ${VAR:-default}, .env file. Extends: share config. Profiles: selective services (--profile debug up). Healthcheck: interval, timeout, retries. Deploy (swarm): replicas, resources, restart_policy.</p>"),
        Q("Production Patterns", "<p>Multi-stage builds: reduce image size. Init containers: wait for deps. depends_on: condition service_healthy. Networking: connect to external networks. Entrypoint scripts: wait for DB. Logging: json-file, gelf, fluentd. Resource limits: cpus, memory. Restart: unless-stopped, always. Docker Compose watch: hot reload. Secrets vs env: prefer secrets. Multi-file: docker compose -f docker-compose.yml -f production.yml up. Profiles: separate dev/staging/prod. Config validation: docker compose config. Container orchestration: docker stack deploy.</p>"),
    ],[F("Compose Docs","https://docs.docker.com/compose/","Docker Compose docs"),F("Compose File Reference","https://docs.docker.com/compose/compose-file/","Compose specification")]),
    ("Linux Server Hardening", "linux-server-hardening.html", "Secure Linux servers -- SSH, firewall, audits, and CIS benchmarks.", "Extras", "fas fa-shield-halved", [
        Q("SSH & Access", "<p>SSH hardening: disable root login (PermitRootLogin no), disable password auth (PasswordAuthentication no), use ed25519 keys, change port (obscurity), fail2ban (rate limit). SSH config: /etc/ssh/sshd_config, allow specific users/groups. MFA: Google Authenticator, U2F. SSH certificates: signed host/user keys. Audit: auditd (watch /etc/passwd, /etc/shadow). Access control: sudoers (least privilege), /etc/security/limits.conf, PAM modules. Kernel hardening: sysctl settings (kernel.kptr_restrict=2, kernel.dmesg_restrict=1, net.ipv4.tcp_syncookies=1).</p>"),
        Q("Firewall & CIS", "<p>Firewall: nftables or iptables -- default deny, allow SSH, HTTP, HTTPS. ufw: easy rules. Fail2ban: jails for SSH, HTTP auth. AppArmor/SELinux: mandatory access control. Auditd: monitor file changes, system calls. AIDE/Tripwire: file integrity monitoring. CIS Benchmarks: Level 1 (basic), Level 2 (defense in depth). Tools: Lynis (security auditing), rkhunter (rootkit), chkrootkit, ClamAV (antivirus). Updates: unattended-upgrades (security only). Docker security: no privileged containers, read-only rootfs, AppArmor profiles, seccomp. Kernel: kernel.kptr_restrict=2, kernel.dmesg_restrict=1, net.ipv4.conf.all.rp_filter=1, net.ipv4.tcp_syncookies=1, net.ipv6.conf.all.disable_ipv6=1 (if not used). /etc/security/limits.conf: prevent fork bombs.</p>"),
    ],[F("CIS Benchmarks","https://www.cisecurity.org/cis-benchmarks","Security benchmarks"),F("Lynis","https://cisofy.com/lynis/","Security auditing tool")]),
    ("Personal Knowledge Management", "personal-knowledge-management.html", "PKM -- second brain, Zettelkasten, dashboards, and knowledge synthesis.", "Extras", "fas fa-brain", [
        Q("Systems & Methods", "<p>PKM: manage and synthesize knowledge. Zettelkasten: atomic notes, linked, own words. PARA (Tiago Forte): Projects, Areas, Resources, Archives. Second brain: capture, organize, distill, express (CODE). Progressive summarization: bold -> highlight -> executive summary -> remix. MOCs: Maps of Content (hub notes). Daily notes: capture ideas, log work. Weekly review: process inbox, update projects. Evergreen notes: permanent, refined, linked. Spaced repetition: Anki for long-term retention.</p>"),
        Q("Tools & Workflow", "<p>Tools: Obsidian (local, graph, backlinks), Notion (databases, collaboration), Logseq (outliner, open-source), Roam (block-based). Obsidian: graph view, Dataview (SQL-like queries), Kanban, Calendar, Excalidraw, Readwise. Notion: databases (table, board, gallery), templates, relation/rollup, formula, API. Capture: Readwise (web highlights), browser extensions, mobile quick capture. Templates: daily note, meeting notes, project tracker. Archive: old projects, reference material. Dashboard: overview of active projects, goals, tasks. Weekly review: process inbox, update progress, plan. Knowledge synthesis: connect ideas across domains. Working out loud: share knowledge, get feedback.</p>"),
    ],[F("Obsidian","https://help.obsidian.md/","Knowledge base"),F("Notion Guide","https://www.notion.so/help","Notion help")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials (p3e)!")
