#!/usr/bin/env python3
"""Generate ~50 tutorials — DevOps, Linux, Windows, Mobile."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === DEVOPS (14) ===
    ("Docker Deep Dive", "docker-deep-dive.html", "Master Docker — images, containers, networks, volumes, multi-stage builds, and Compose.", "DevOps", "fab fa-docker", [
        Q("Images & Dockerfile", "<p>Docker images are read-only templates. Dockerfile: FROM, RUN, COPY, ADD, CMD, ENTRYPOINT, EXPOSE. Multi-stage builds: use multiple FROM statements to copy artifacts between stages — reduces final image size. Layer caching: ORDER matters — put infrequently changing layers first (apt-get, pip install). Best practices: use .dockerignore, prefer specific tags over :latest, use --no-cache for apt, combine RUN commands with &&.</p>"),
        Q("Networking & Volumes", "<p>Docker networks: bridge (default per-container), host (shared with host network), overlay (multi-host swarm), macvlan (assign MAC to container). Port mapping: -p 8080:80. Volumes: named volumes (docker volume create), bind mounts (absolute host path), tmpfs (in-memory). Volume drivers: local, NFS, cloud (rexray, cloudstor). Backup: docker run --rm -v myvolume:/data -v $(pwd):/backup alpine tar czf /backup/volume.tar.gz -C /data .</p>"),
        Q("Docker Compose", "<p>Compose defines multi-container apps in YAML. docker-compose.yml: services, networks, volumes. Service config: image, build, ports, environment, volumes, depends_on, restart, healthcheck. Profiles: selective service activation (docker compose --profile debug up). Watch: docker compose watch — auto rebuild on file change. Scaling: docker compose up --scale web=3. Extends: share common config across services via YAML anchors.</p>"),
    ],[F("Docker Docs","https://docs.docker.com/","Official Docker documentation"),F("Docker Cheat Sheet","https://dockerlabs.collabnix.com/docker/cheatsheet/","Docker CLI reference")]),
    ("Kubernetes Architecture", "kubernetes-architecture.html", "Kubernetes cluster architecture — control plane, nodes, scheduling, and resource management.", "DevOps", "fas fa-ship", [
        Q("Control Plane Components", "<p>Control plane: kube-apiserver (REST gateway, auth, admission control), etcd (distributed key-value store — cluster state), kube-scheduler (pod placement — resource requirements, affinities, taints/tolerations), kube-controller-manager (replication, endpoints, service account, node controllers), cloud-controller-manager (cloud-specific: load balancers, nodes, routes). High availability: multiple control plane replicas, etcd quorum (3 or 5 nodes).</p>"),
        Q("Worker Nodes & Scheduling", "<p>Worker node: kubelet (pod lifecycle manager), kube-proxy (network rules — iptables, IPVS), container runtime (containerd, CRI-O). Pod: smallest deployable unit — one or more containers sharing network namespace. Scheduling: nodeSelector, nodeAffinity, podAffinity, podAntiAffinity, taints (node can repel: NoSchedule, PreferNoSchedule, NoExecute) and tolerations (pod can tolerate). Resource QoS: Guaranteed (limits = requests), Burstable (requests < limits), BestEffort (no requests/limits).</p>"),
    ],[F("K8s Documentation","https://kubernetes.io/docs/","Official Kubernetes docs"),F("K8s Learning Path","https://kubernetes.io/learn/","Interactive K8s tutorials")]),
    ("GitHub Actions CI/CD", "github-actions-cicd.html", "Automate workflows with GitHub Actions — CI/CD, matrix builds, artifacts, and deployment.", "DevOps", "fab fa-github", [
        Q("Workflow Fundamentals", "<p>GitHub Actions: YAML workflows in .github/workflows/. Trigger: push, pull_request, schedule, workflow_dispatch, release. Jobs: run in parallel by default, dependencies via needs:. Steps: uses (actions/checkout@v4), run (shell commands), name, id, with (inputs). Matrix: strategy.matrix: { os: [ubuntu-latest, windows-latest], node: [18, 20] } — generates NxM job combinations. Runners: GitHub-hosted (ubuntu, windows, macos) or self-hosted (scale sets).</p>"),
        Q("Artifacts & Deployment", "<p>Artifacts: actions/upload-artifact@v4 (upload build outputs), actions/download-artifact@v4 (download in later jobs). Caching: actions/cache@v4 — cache node_modules, pip, Maven ~/.m2. Environments: deployment environments with protection rules, secrets, and approval gates. OIDC: authenticate to cloud providers without static secrets. Composite actions: reusable step groups (action.yml in subdirectory). GitHub-hosted runner specs: 2-4 vCPU, 7-14GB RAM, 14-70GB SSD.</p>"),
    ],[F("Actions Docs","https://docs.github.com/en/actions","Official GitHub Actions docs"),F("Actions Marketplace","https://github.com/marketplace?type=actions","Community actions marketplace")]),
    ("Ansible Automation", "ansible-automation.html", "Configuration management and automation with Ansible — playbooks, roles, and inventory.", "DevOps", "fab fa-redhat", [
        Q("Playbooks & Modules", "<p>Ansible is agentless — uses SSH (Linux) or WinRM (Windows). Playbooks: YAML with hosts, become, tasks. Modules: apt/yum/dnf (package management), copy/template (file distribution), service/systemd (service control), command/shell (arbitrary commands), file (permissions, directories), user/group (user management). Idempotency: modules are idempotent — running twice produces same result. Facts: ansible_facts gathers system info (OS, IP, memory).</p>"),
        Q("Roles & Inventory", "<p>Roles: structured directories — tasks/, handlers/, templates/, files/, vars/, defaults/, meta/. Galaxy: ansible-galaxy install geerlingguy.nginx — community roles. Inventory: static INI/YAML or dynamic (AWS EC2, GCP, Azure, vmware). ansible.cfg: defaults, SSH settings, forks (parallel hosts). Ansible Vault: encrypt secrets — ansible-vault encrypt vars/secrets.yml, --ask-vault-pass. Jinja2 templates: {{ ansible_facts['os_family'] }}, {% for user in users %} {{ user }} {% endfor %}.</p>"),
    ],[F("Ansible Docs","https://docs.ansible.com/","Official Ansible documentation"),F("Ansible Galaxy","https://galaxy.ansible.com/","Community role repository")]),
    ("Terraform Infrastructure", "terraform-infrastructure.html", "Infrastructure as Code with Terraform — HCL, state management, modules, and providers.", "DevOps", "fas fa-terrain", [
        Q("HCL & Resources", "<p>Terraform HCL: resource, data source, variable, output, provider, module. Resources: resource aws_instance web { ami = var.ami_id instance_type = \"t3.micro\" }. Data sources: query existing infrastructure (aws_ami, azurerm_resource_group). Variables: variable \"region\" { type = string default = \"us-east-1\" } — used as var.region. Outputs: output \"instance_ip\" { value = aws_instance.web.public_ip } — shown after apply, usable by other configs.</p>"),
        Q("State & Modules", "<p>State: terraform.tfstate — maps resources to real infrastructure. Remote state: S3 + DynamoDB lock, Terraform Cloud, Azure Storage, GCS. Commands: init, plan, apply, destroy, fmt, validate, import, state (mv, rm, list). Modules: reusable config packages — module \"vpc\" { source = \"terraform-aws-modules/vpc/aws\" version = \"5.0\" }. Module sources: local paths, registry, Git, HTTP, S3. Terraform Registry: community modules for AWS, Azure, GCP, K8s.</p>"),
    ],[F("Terraform Docs","https://developer.hashicorp.com/terraform/docs","Official Terraform docs"),F("Terraform Registry","https://registry.terraform.io/","Module and provider registry")]),
    ("Jenkins Pipeline", "jenkins-pipeline.html", "CI/CD with Jenkins — declarative pipeline, shared libraries, and master-agent architecture.", "DevOps", "fab fa-jenkins", [
        Q("Declarative Pipeline", "<p>Jenkinsfile: pipeline { agent any stages { stage('Build') { steps { sh 'make build' } } } }. Triggers: pollSCM, cron, webhook (GitHub/GitLab plugin). Post: always, success, failure, unstable, changed — cleanup, notifications, archiving. Environment: environment { VAR = 'value' } — per stage or global. Tools: tools { maven 'Maven-3.9' go 'Go-1.21' }. When: when { branch 'main' } — conditional stage execution.</p>"),
        Q("Shared Libraries & Agents", "<p>Shared libraries: vars/ (callable functions), src/ (Groovy classes). @Library('my-lib@main') import com.example.Utils. Agent types: any, none, label, docker, dockerfile, kubernetes. Multi-branch pipeline: auto-discovers branches matching regex, builds each branch separately. Blue Ocean: modern Pipeline UI. Pipeline Syntax Generator: snippet generator for step configuration. Security: credentials binding (withCredentials), folder-based authorization.</p>"),
    ],[F("Jenkins Handbook","https://www.jenkins.io/doc/book/pipeline/","Official Jenkins Pipeline docs"),F("Jenkins User Docs","https://www.jenkins.io/doc/","Jenkins user documentation")]),
    ("Helm Charts", "helm-charts.html", "Kubernetes package manager — charts, templates, values, and repositories.", "DevOps", "fas fa-anchor", [
        Q("Chart Structure & Templates", "<p>Helm chart directory: Chart.yaml (metadata), values.yaml (default config), templates/ (Go templates + YAML), charts/ (subcharts), crds/ (CRDs). Templates: apiVersion: apps/v1 kind: Deployment metadata: name: {{ include \"myapp.fullname\" . }}. Built-in objects: .Values, .Release, .Chart, .Files, .Capabilities. Functions: {{ .Values.replicaCount | default 1 }}, {{ quote .Values.name }}, {{ upper .Values.env }}. Flow control: {{- if .Values.ingress.enabled }} ... {{- end }}, {{- range .Values.containers }} ... {{- end }}.</p>"),
        Q("Dependencies & Hooks", "<p>Chart dependencies: Chart.yaml — dependencies: [{ name: \"redis\", version: \"17.x\", repository: \"https://charts.bitnami.com/bitnami\" }]. helm dependency update. Hooks: pre-install, post-install, pre-upgrade, post-upgrade, pre-delete, post-delete — defined with annotations (helm.sh/hook). Testing: helm test — pods with test hook. Repository: helm repo add bitnami https://charts.bitnami.com/bitnami. Chart Museum: self-hosted chart repository. Helmfile: declarative management of multiple Helm releases.</p>"),
    ],[F("Helm Docs","https://helm.sh/docs/","Official Helm documentation"),F("ArtifactHUB","https://artifacthub.io/","Public Helm chart repository")]),
    ("Prometheus & Grafana", "prometheus-grafana.html", "Monitoring and alerting — Prometheus metrics, exporters, alertmanager, and Grafana dashboards.", "DevOps", "fas fa-chart-bar", [
        Q("Prometheus Metrics & Exporters", "<p>Prometheus: pull-based time-series DB. Data model: metric_name{label=\"value\"} value. Metric types: counter (incrementing — requests_total), gauge (up/down — memory_usage), histogram (bucketed — request_duration_seconds), summary (quantiles). Exporters: node_exporter (system metrics), blackbox_exporter (HTTP/DNS/TCP probes), mysqld_exporter, postgres_exporter, redis_exporter, kube-state-metrics. ServiceMonitor/PodMonitor: CRDs for K8s service discovery.</p>"),
        Q("Alertmanager & Grafana", "<p>Alerting rules: groups: [ name: example rules: [ alert: HighCPU expr: node_cpu_seconds > 0.9 for: 5m labels: { severity: critical } annotations: { summary: \"CPU over 90%\" } ] ]. Alertmanager: group by severity/instance, route to receivers. Receivers: email (SMTP), Slack (webhook), PagerDuty, OpsGenie, webhook. Grafana: data source (Prometheus, Loki, Elasticsearch, CloudWatch), panels (graph, stat, gauge, table, bar gauge), variables (${host} — template queries), alerts (visual-based alerting), folders, teams.</p>"),
    ],[F("Prometheus Docs","https://prometheus.io/docs/","Official Prometheus documentation"),F("Grafana Docs","https://grafana.com/docs/","Official Grafana docs")]),
    ("ELK Stack", "elk-stack.html", "Elasticsearch, Logstash, Kibana — log aggregation, parsing, and visualization.", "DevOps", "fas fa-search", [
        Q("Logstash Pipelines", "<p>Logstash: input { beats { port => 5044 } } filter { grok { match => { \"message\" => \"%{COMBINEDAPACHELOG}\" } } date { match => [\"timestamp\", \"dd/MMM/yyyy:HH:mm:ss Z\"] } mutate { rename => { \"response\" => \"status_code\" } } } output { elasticsearch { hosts => [\"localhost:9200\"] index => \"apache-logs-%{+YYYY.MM.dd}\" } }. Grok patterns: predefined (COMBINEDAPACHELOG, SYSLOGBASE) or custom. Dissect: faster than grok for structured logs.</p>"),
        Q("Kibana Visualizations", "<p>Kibana: Discover (search logs — KQL: status:>=400 and response_time > 1000), Dashboard (combine visualizations), Lens (drag-drop chart builder), Maps (geo data), Canvas (custom reports). ES indices: ILM (hot-warm-cold-delete lifecycle), alias management (read-only on warm, shrink, force merge). Beats: Filebeat (log files), Metricbeat (system metrics), Heartbeat (uptime monitoring), Winlogbeat (Windows events). Security: Elasticsearch security features (RBAC, TLS, audit logging).</p>"),
    ],[F("ELK Stack Docs","https://www.elastic.co/guide/index.html","Elastic Stack documentation"),F("Logstash Reference","https://www.elastic.co/guide/en/logstash/current/","Logstash configuration guide")]),
    ("ArgoCD & GitOps", "argocd-gitops.html", "GitOps for Kubernetes — ArgoCD, application sync, and progressive delivery.", "DevOps", "fas fa-code-branch", [
        Q("ArgoCD Applications", "<p>ArgoCD: declarative GitOps — Git repo as source of truth. Application CRD: spec: { source: { repoURL, path, targetRevision }, destination: { server, namespace }, syncPolicy: { automated: { prune: true, selfHeal: true } } }. Sync strategies: manual (one-click), automated (auto-sync on Git changes). PR previews: ArgoCD Image Updater or review apps. App of Apps pattern: root app manages multiple child apps via ApplicationSets.</p>"),
        Q("Progressive Delivery", "<p>Progressive delivery: Argo Rollouts — blue/green, canary deployments. Rollout CRD: spec: { strategy: { canary: { steps: [{ setWeight: 20 }, { pause: { duration: 5m } }, { setWeight: 40 }] } } }. Analysis: metrics from Prometheus, Datadog, New Relic — auto-rollback if threshold breached. ArgoCD Notifications: triggers (on-sync-succeeded, on-health-degraded), templates (Slack, email, webhook). Argo Workflows: DAG-based CI/CD pipelines on Kubernetes.</p>"),
    ],[F("ArgoCD Docs","https://argo-cd.readthedocs.io/","Official ArgoCD documentation"),F("Argo Rollouts","https://argoproj.github.io/rollouts/","Progressive delivery for K8s")]),
    ("Packer & Vagrant", "packer-vagrant.html", "Immutable infrastructure — Packer images and Vagrant environments for development.", "DevOps", "fas fa-box", [
        Q("Packer Images", "<p>Packer: build identical images for multiple platforms. HCL template: source \"amazon-ebs\" \"example\" { ami_name = \"myapp-{{timestamp}}\" instance_type = \"t3.micro\" region = \"us-east-1\" source_ami = \"ami-0c55b159cbfafe1f0\" ssh_username = \"ubuntu\" }. Build: build { sources = [\"source.amazon-ebs.example\"] provisioner \"shell\" { inline = [\"sudo apt-get update\", \"sudo apt-get install -y nginx\"] } }. Post-processors: manifest (output AMI ID), vagrant (convert to Vagrant box).</p>"),
        Q("Vagrant Environments", "<p>Vagrant: portable development environments. Vagrantfile: Vagrant.configure(2) do |config| config.vm.box = \"ubuntu/jammy64\" config.vm.network \"private_network\", ip: \"192.168.56.10\" config.vm.synced_folder \".\", \"/vagrant\" config.vm.provision \"shell\", inline: \"apt-get install -y docker.io\" end. Providers: VirtualBox, VMware, Hyper-V, Docker, libvirt. Plugins: vagrant-hostmanager (auto /etc/hosts), vagrant-vbguest (Guest Additions). Multi-machine: config.vm.define \"web\" do |web| ... end.</p>"),
    ],[F("Packer Docs","https://developer.hashicorp.com/packer/docs","Official Packer docs"),F("Vagrant Docs","https://developer.hashicorp.com/vagrant/docs","Official Vagrant documentation")]),
    ("SRE Principles", "sre-principles.html", "Site Reliability Engineering — SLIs, SLOs, error budgets, and incident management.", "DevOps", "fas fa-life-ring", [
        Q("SLIs, SLOs & Error Budgets", "<p>SRE: applying software engineering to operations. SLI (Service Level Indicator): measurable metric — latency (p99 < 200ms), availability (200/500 ratio), throughput (requests/sec), durability (data loss). SLO (Service Level Objective): target SLI — 99.9% availability over 30 days. Error budget: 100% - SLO = allowed downtime (0.1% = 43 min/month). Burn rate: how fast error budget is consumed. Multi-window, multi-burn-rate alerting: 1h@1x, 6h@5x, 3d@20x.</p>"),
        Q("Incident Management", "<p>Incident management: unplanned interruption. Severity: SEV1 (critical — all hands), SEV2 (major — business hours), SEV3 (minor — next business day), SEV4 (cosmetic). Response: detect (monitoring), triage (severity, assignee), mitigate (rollback, feature flag, scale up), resolve (fix root cause), follow-up (postmortem). Postmortem: timeline, root cause, action items, blameless culture. Toil: manual, repetitive, automatable work — SREs should spend <50% time on toil.</p>"),
    ],[F("Google SRE Book","https://sre.google/books/","Free SRE books from Google"),F("SRE Weekly","https://sreweekly.com/","Weekly SRE newsletter and resources")]),
    ("Service Mesh (Istio)", "service-mesh-istio.html", "Service mesh with Istio — sidecar proxy, traffic management, security, and observability.", "DevOps", "fas fa-network-wired", [
        Q("Istio Architecture", "<p>Istio: sidecar (Envoy proxy) injected into each pod — intercepts all traffic. Control plane (istiod): Pilot (service discovery, traffic rules), Citadel (certificate management, mTLS), Galley (config validation). Data plane: Envoy proxies — handle load balancing, circuit breakers, retries, timeouts. Installation: istioctl install --set profile=demo. Sidecar injection: namespace label istio-injection=enabled or annotation sidecar.istio.io/inject: \"true\" on pod.</p>"),
        Q("Traffic & Security", "<p>VirtualService: HTTP routing — match URI, rewrite, redirect, retry, fault injection, mirror. DestinationRule: subsets (version labels), load balancer (ROUND_ROBIN, LEAST_CONN, RANDOM), connection pool (max connections, max pending requests), outlier detection (consecutive errors, ejection time). mTLS: PeerAuthentication (STRICT, PERMISSIVE, DISABLE), DestinationRule tls mode. AuthorizationPolicy: action (ALLOW, DENY), rules (source: principals, namespaces, IP blocks; to: methods, paths).</p>"),
    ],[F("Istio Docs","https://istio.io/latest/docs/","Official Istio documentation"),F("Istio in Action","https://www.manning.com/books/istio-in-action","Book on Istio")]),
    ("Chaos Engineering", "chaos-engineering.html", "Chaos Engineering — principles, experiments, tools (Chaos Mesh, Litmus), and GameDay.", "DevOps", "fas fa-skull", [
        Q("Principles & Experiments", "<p>Chaos Engineering: test system resilience by injecting failures. Principles: steady state (define normal behavior — latency, error rate), hypothesize (what if...?), run experiment (small scope), minimize blast radius, automate. GameDay: scheduled chaos experiments — everyone on-call, practice incident response. Types: infrastructure (kill pod, network partition, CPU spike), platform (DB failover, DNS outage), application (slow responses, exceptions).</p>"),
        Q("Chaos Mesh & Litmus", "<p>Chaos Mesh: Kubernetes chaos — PodChaos (kill, failure), NetworkChaos (delay, loss, partition, bandwidth), StressChaos (CPU, memory), IOChaos (delay, fault), DNSChaos (error, random). Litmus: cloud-native chaos hub — experiments for K8s, AWS, Azure, GCP. Workflows: sequence of chaos experiments with probes (HTTP, cmd, k8s). ChaosHub: community experiment marketplace. Steady state validation: prometheus metrics, custom probes. Result: PASS/FAIL based on SLO.</p>"),
    ],[F("Chaos Mesh Docs","https://chaos-mesh.org/docs/","Kubernetes chaos engineering"),F("Litmus Docs","https://litmuschaos.io/docs/","Cloud-native chaos engineering")]),

    # === LINUX (12) ===
    ("Bash Scripting Mastery", "bash-scripting-mastery.html", "Bash scripting — variables, functions, control flow, error handling, and advanced techniques.", "Linux", "fas fa-terminal", [
        Q("Essentials & Control Flow", "<p>Shebang: #!/bin/bash. Variables: NAME=\"value\" (no spaces), $NAME or ${NAME}. Arrays: arr=(\"a\" \"b\" \"c\"); echo ${arr[1]}; ${#arr[@]} for length. Conditionals: if [[ condition ]]; then ... elif ...; else ...; fi. File tests: -f (file exists), -d (directory), -x (executable). String tests: [[ -z $var ]] (empty), [[ $a == $b ]], [[ $a =~ regexp ]]. Arithmetic: $(( x + y )), (( x++ )). Loops: for i in ${list[@]}; do ...; done; while read line; do ...; done < file.</p>"),
        Q("Functions & Error Handling", "<p>Functions: function myfunc() { local var=\"scope\"; return 0; }. Error handling: set -e (exit on error), set -u (undefined var error), set -o pipefail (pipe failure). Trap: trap 'cleanup' EXIT, trap 'echo \"Interrupted\"; exit 1' SIGINT. Debug: set -x (trace execution), bash -n script (syntax check). Subshell: (cd /tmp && command) — runs in subshell, no env change. Process substitution: diff <(cmd1) <(cmd2). Here documents: cat <<-EOF ... EOF.</p>"),
    ],[F("Bash Reference","https://www.gnu.org/software/bash/manual/","Official Bash manual"),F("Bash Hackers Wiki","https://wiki.bash-hackers.org/","Community Bash wiki")]),
    ("Linux Filesystem", "linux-filesystem.html", "Linux filesystem hierarchy — FHS, inodes, permissions, ACLs, and mount points.", "Linux", "fas fa-folder-tree", [
        Q("FHS & Inodes", "<p>Filesystem Hierarchy Standard: /bin (essential binaries), /boot (kernel, initrd), /dev (devices), /etc (config files), /home (user dirs), /lib (libraries), /media, /mnt (mount points), /opt (third-party), /proc (process virtual fs), /root (root home), /run (runtime data), /sbin (system binaries), /srv (service data), /sys (kernel/device info), /tmp (temp), /usr (user binaries/libraries — /usr/local for local), /var (log, cache, spool). Inodes: metadata — permissions, owner, timestamps, block pointers. Hard links: same inode, different names. Symlinks: separate inode pointing to path.</p>"),
        Q("Permissions & ACLs", "<p>Standard permissions: rwxr-xr-x (owner: read/write/execute, group: read/execute, others: read/execute). chmod: symbolic (u+x, g-w, o=r) or octal (755 = rwxr-xr-x, 644 = rw-r--r--). setuid (chmod u+s — execute as owner), setgid (chmod g+s — execute as group), sticky bit (chmod +t — only owner can delete own files). ACLs: setfacl -m u:username:rwx file, getfacl file. Default ACLs: setfacl -d -m g::rx directory — inherited by new files. umask: default permission mask (022 = files 644, dirs 755).</p>"),
    ],[F("FHS 3.0","https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf","Filesystem Hierarchy Standard"),F("Linux FS Guide","https://www.kernel.org/doc/html/latest/filesystems/","Linux kernel filesystem docs")]),
    ("Linux Networking", "linux-networking.html", "Linux networking — iproute2, socket troubleshooting, firewalls, and advanced routing.", "Linux", "fas fa-network-wired", [
        Q("iproute2 Suite", "<p>Modern Linux networking: ip (replaces ifconfig, route). ip addr (list/manage IPs), ip link (interface up/down, MAC), ip route (routing table), ip neigh (ARP cache). ss (socket statistics — replaces netstat): ss -tuln (listening TCP/UDP), ss -tup (active connections with PID). Bridge: ip link add br0 type bridge, ip link set eth0 master br0. VETH: ip link add veth0 type veth peer name veth1. Network namespaces: ip netns add blue, ip netns exec blue ip addr.</p>"),
        Q("Firewall & Advanced", "<p>nftables: modern firewall — nft add table inet filter, nft add chain inet filter input { type filter hook input priority 0; }, nft add rule inet filter input tcp dport 22 accept. iptables legacy: iptables -A INPUT -p tcp --dport 80 -j ACCEPT. Conntrack: connection tracking — /proc/net/nf_conntrack, conntrack -L. TC (traffic control): tc qdisc add dev eth0 root netem delay 100ms (latency simulation). Bonding: multiple NICs as one — balance-rr, active-backup, 802.3ad (LACP).</p>"),
    ],[F("iproute2 Docs","https://linux-ip.net/","Linux networking tools guide"),F("nftables Wiki","https://wiki.nftables.org/","nftables user documentation")]),
    ("Systemd & Services", "systemd-services.html", "Systemd — units, targets, timers, journald, and service management.", "Linux", "fas fa-cogs", [
        Q("Unit Files & Service Management", "<p>Systemd units: .service, .socket, .timer, .target, .mount, .path, .slice. Service unit: [Unit] Description=MyApp After=network.target [Service] Type=simple (forking, oneshot, notify, dbus) ExecStart=/usr/bin/myapp Restart=on-failure RestartSec=5s User=myapp Group=myapp EnvironmentFile=/etc/myapp/env [Install] WantedBy=multi-user.target. Commands: systemctl start/stop/restart/reload/enable/disable/status myapp. Mask: systemctl mask myapp — prevents manual and dependency starts.</p>"),
        Q("Timers & Journald", "<p>Timers: monotonic (OnBootSec, OnUnitActiveSec) or calendar (OnCalendar=daily, OnCalendar=\"*-*-* 03:00:00\"). Timer unit: [Timer] OnCalendar=daily Persistent=true [Install] WantedBy=timers.target. journalctl: -u myapp (specific unit), -f (follow), --since \"1 hour ago\", -p err (priority), -o json-pretty (output). Journal: persistent (Storage=persistent in /var/log/journal) vs volatile. Lograte: SystemMaxUse=500M, MaxRetentionSec=1month. Coredump: coredumpctl list, coredumpctl gdb PID.</p>"),
    ],[F("Systemd Docs","https://systemd.io/","Systemd documentation"),F("Freedesktop Systemd","https://www.freedesktop.org/wiki/Software/systemd/","Systemd project page")]),
    ("Linux Security Hardening", "linux-security-hardening.html", "Harden Linux — AppArmor, SELinux, auditd, secure boot, and kernel hardening.", "Linux", "fas fa-shield-halved", [
        Q("Mandatory Access Control", "<p>SELinux: contexts (user:role:type:level), modes (Enforcing, Permissive, Disabled). Common commands: getenforce, setenforce 0, ls -Z, ps -Z, semanage boolean -l, audit2why (explain AVC denials). AppArmor: profiles in /etc/apparmor.d/, aa-status, aa-complain, aa-enforce. Profiles: include <tunables/global> /usr/bin/myapp { /etc/myapp/* r, /var/log/myapp.log w, network tcp, }. auditd: auditctl (rules -w /etc/passwd -p wa -k passwd_changes), ausearch -k passwd_changes.</p>"),
        Q("Kernel Hardening & Secure Boot", "<p>sysctl: kernel parameters — net.ipv4.tcp_syncookies=1 (SYN flood), kernel.kptr_restrict=2, kernel.dmesg_restrict=1, net.ipv4.conf.all.rp_filter=1, net.ipv4.conf.all.accept_source_route=0. /etc/sysctl.d/99-hardening.conf. Kernel cmdline: lockdown=confidentiality (restrict root), slab_nomerge, init_on_alloc=1, page_alloc.shuffle=1, randomize_kstack_offset=on. Secure Boot: signed kernels, MOK (Machine Owner Key), sbctl. TPM: tpm2-tools for sealed encryption, LUKS with TPM unlock. DISA STIG/CIS Benchmarks: compliance profiles.</p>"),
    ],[F("CIS Benchmarks","https://www.cisecurity.org/cis-benchmarks","Security configuration benchmarks"),F("Linux Security Docs","https://docs.kernel.org/security/","Linux kernel security docs")]),
    ("Linux Performance Tuning", "linux-performance-tuning.html", "Performance analysis — perf, flamegraphs, sysstat, cgroups, and kernel tuning.", "Linux", "fas fa-gauge-high", [
        Q("Tools & Flamegraphs", "<p>Performance tools: top/htop (process overview), iostat (I/O), vmstat (memory/CPU), sar (historical), ss (sockets), pidstat (per-process), mpstat (per-CPU). strace: system calls — strace -p PID -e trace=network -c. ltrace: library calls. perf: perf top (live profile), perf record / perf report (sampling), perf stat (counters). Flamegraphs: perf script | stackcollapse-perf.pl | flamegraph.pl > flame.svg. Brendan Gregg's USE method: Utilization, Saturation, Errors for every resource.</p>"),
        Q("Cgroups & Kernel Tuning", "<p>cgroups v2: unified hierarchy — /sys/fs/cgroup/. CPU: cpu.weight (relative share), cpu.max (quota period). Memory: memory.max (hard limit), memory.high (soft limit), memory.swap.max. I/O: io.max (bps/iops limits), io.weight. systemd resource control: CPUQuota=50%, MemoryMax=1G, IOWeight=100. Transparent Hugepages: madvise (recommended) vs always vs never. Kernel same-page merging (KSM): for virtualization. NUMA: numactl, numastat — pin processes to local memory. IRQ balancing: irqbalance, set SMP affinity (/proc/irq/).</p>"),
    ],[F("Linux perf Wiki","https://perf.wiki.kernel.org/","Perf tool documentation"),F("Brendan Gregg's Site","https://www.brendangregg.com/","Performance analysis resources")]),
    ("Linux Package Management", "linux-package-management.html", "Package managers — apt, dnf, pacman, emerge, snap, flatpak, and AppImage.", "Linux", "fas fa-boxes", [
        Q("Debian & RPM Systems", "<p>APT (Debian/Ubuntu): apt update (refresh), apt upgrade (upgrade all), apt install, apt remove, apt purge, apt autoremove, apt search, dpkg -i (install .deb), dpkg -L (files in package), apt-mark hold/unhold (pin version). Sources: /etc/apt/sources.list, /etc/apt/sources.list.d/. DNF (Fedora/RHEL): dnf install, dnf remove, dnf groupinstall \"Development Tools\", dnf repolist, dnf provides (what package provides file). RPM: rpm -ivh (install), rpm -qa (query all). Zypper (openSUSE): zypper install, zypper search.</p>"),
        Q("Pacman, Nix & Modern Formats", "<p>Pacman (Arch): pacman -Syu (sync upgrade), pacman -S, pacman -Rs, pacman -Q, pacman -Qi (info). AUR: yay -S package — community-driven PKGBUILDs. Nix: declarative — configuration.nix, nix-env, nix-shell (temporary env). Snap: snap install, snap install --classic, snap refresh. Flatpak: flatpak install flathub app, flatpak run. AppImage: download + chmod +x + run — no install. Containers vs VMs vs packages: packages (shared libs), containers (isolated, portable), VMs (full OS isolation).</p>"),
    ],[F("APT Docs","https://wiki.debian.org/Apt","Debian package manager"),F("NixOS Docs","https://nixos.org/learn.html","Nix package manager")]),
    ("Linux Virtualization (KVM/LXC)", "linux-virtualization.html", "Linux virtualization — KVM, QEMU, libvirt, LXC/LXD, and containers.", "Linux", "fas fa-cloud", [
        Q("KVM & QEMU", "<p>KVM: kernel-based virtual machine — requires CPU with VT-x/AMD-V. Tools: virt-manager (GUI), virsh (CLI), virt-install (provisioning). VM lifecycle: virsh create/start/shutdown/destroy/undefine. Storage: raw, qcow2 (COW — snapshots, compression), qcow2 backing files (base image + overlay). Networking: NAT (default virbr0), bridged (bridge to host NIC), macvtap (direct passthrough). Snapshots: virsh snapshot-create-as vm snap1. Live migration: virsh migrate --live vm qemu+ssh://dest/system.</p>"),
        Q("LXC/LXD Containers", "<p>LXC: system containers — like VMs but share host kernel. lxc-create -t ubuntu -n mycontainer. LXD: next-gen LXC with REST API, clustering, storage pools. lxc launch ubuntu:22.04 mycontainer, lxc exec mycontainer bash. Profiles: lxc profile create myprofile, config: limits.cpu=2, limits.memory=1GB. Storage pools: ZFS (snapshots, clones, compression), Btrfs, LVM, dir. Clustering: LXD cluster — multiple nodes, one management endpoint. Instance types: container (shared kernel) vs VM (KVM guest managed by LXD).</p>"),
    ],[F("KVM Docs","https://www.linux-kvm.org/page/Documents","KVM virtualization documentation"),F("LXD Docs","https://documentation.ubuntu.com/lxd/","LXD container hypervisor docs")]),
    ("Linux Storage (LVM/RAID/ZFS)", "linux-storage.html", "Advanced Linux storage — LVM, software RAID, ZFS, Btrfs, and filesystem tuning.", "Linux", "fas fa-hard-drive", [
        Q("LVM & Software RAID", "<p>LVM: Physical Volume (pvcreate), Volume Group (vgcreate, vgextend), Logical Volume (lvcreate -L 10G -n data vg0). Extend: lvextend -L +5G /dev/vg0/data && resize2fs /dev/vg0/data. Snapshots: lvcreate -s -n snap -L 1G /dev/vg0/data — consistent backups. Thin provisioning: lvcreate --type thin-pool -L 50G vg0/thinpool. RAID (mdadm): levels 0 (stripe), 1 (mirror), 5 (parity), 6 (dual parity), 10 (stripe+mirror). mdadm --create /dev/md0 --level=5 --raid-devices=4 /dev/sd[bcde]1. Spare disks: auto rebuild on failure.</p>"),
        Q("ZFS & Btrfs", "<p>ZFS: combined filesystem + volume manager. Pool: zpool create tank mirror sda sdb mirror sdc sdd (RAID10). Datasets: zfs create tank/data, zfs set compression=lz4 tank/data, zfs set mountpoint=/data tank/data. Snapshots: zfs snapshot tank/data@today, zfs rollback tank/data@today. ZFS features: checksumming (no bit rot), deduplication, encryption (zfs load-key), send/receive (zfs send | ssh zfs receive). Btrfs: subvolumes, snapshots (btrfs subvolume snapshot), compression (compress=zstd), RAID (0/1/10/5/6), balance (btrfs balance start).</p>"),
    ],[F("LVM HowTo","https://tldp.org/HOWTO/LVM-HOWTO/","LVM documentation"),F("ZFS Docs","https://openzfs.github.io/openzfs-docs/","OpenZFS documentation")]),
    ("Linux Kernel Modules", "linux-kernel-modules.html", "Linux kernel modules — loading, parameters, building, and troubleshooting.", "Linux", "fas fa-microchip", [
        Q("Module Management", "<p>Kernel modules: dynamically loaded pieces of kernel code. Commands: lsmod (list loaded modules), modinfo (module info — license, depends, params), modprobe (load with deps), insmod (direct load), rmmod (remove), depmod (dependency map). Module location: /lib/modules/$(uname -r)/. Config: /etc/modprobe.d/ — options modname param=value, blacklist modname. initramfs: modules needed at boot — update-initramfs -u or dracut. Module parameters: modinfo -p modname, echo param > /sys/module/modname/parameters/param.</p>"),
        Q("Building & Debugging", "<p>Hello world module: #include <linux/module.h> #include <linux/kernel.h> int init_module(void) { printk(KERN_INFO \"Hello\\n\"); return 0; } void cleanup_module(void) { printk(KERN_INFO \"Bye\\n\"); } MODULE_LICENSE(\"GPL\");. Makefile: obj-m += hello.o; make -C /lib/modules/$(shell uname -r)/build M=$(PWD). Debug: dmesg -wH (kernel messages), /sys/kernel/debug/, ftrace, kprobes. Kernel headers: linux-headers-$(uname -r). Module signing: for Secure Boot. DKMS: auto-rebuild modules on kernel update.</p>"),
    ],[F("Kernel Module Docs","https://docs.kernel.org/","Linux kernel documentation"),F("The Linux Kernel Module Programming Guide","https://sysprog21.github.io/lkmpg/","Beginner kernel module guide")]),

    # === WINDOWS (8) ===
    ("PowerShell Scripting", "powershell-scripting.html", "PowerShell — cmdlets, pipelines, remoting, modules, and automation.", "Windows", "fab fa-microsoft", [
        Q("Cmdlets & Pipeline", "<p>PowerShell: verb-noun naming (Get-Process, Set-Content, Remove-Item). Pipeline: objects passed between commands — Get-Process | Where-Object { $_.CPU -gt 50 } | Sort-Object CPU -Descending | Select-Object -First 5. Aliases: ls (Get-ChildItem), cat (Get-Content), % (ForEach-Object), ? (Where-Object). Providers: FileSystem, Registry, Certificate, Environment, Variable, Function, Alias. Drive navigation: Set-Location Cert:\\CurrentUser\\My. Variables: $var = \"value\", $env:PATH, ${env:PROCESSOR_ARCHITECTURE}.</p>"),
        Q("Scripting & Remoting", "<p>Scripts: .ps1 files. Execution policy: Set-ExecutionPolicy RemoteSigned. Functions: function Get-Greeting { param([string]$Name) \"Hello, $Name\" }. Error handling: try { } catch { $_ } finally { }. Modules: Get-Module -ListAvailable, Import-Module, custom modules (.psm1). PowerShell Gallery: Install-Module -Name Pester (testing), powershell-yaml (YAML), dbatools (SQL Server). Remoting: Enter-PSSession (interactive), Invoke-Command (one-off -ComputerName). WinRM: HTTPS listener, trusted hosts. JEA (Just Enough Admin): constrained endpoints.</p>"),
    ],[F("PowerShell Docs","https://learn.microsoft.com/en-us/powershell/","Official PowerShell documentation"),F("PowerShell Gallery","https://www.powershellgallery.com/","Community module repository")]),
    ("Active Directory", "active-directory.html", "Active Directory — domains, GPOs, LDAP, replication, and security.", "Windows", "fas fa-users", [
        Q("Domain Services & LDAP", "<p>AD DS: LDAP (port 389/636), Kerberos (port 88), DNS (port 53). Components: domain (administrative boundary), tree (namespace continuity), forest (shared schema+GC). FSMO roles: Schema Master, Domain Naming Master, PDC Emulator (time + GPO updates), RID Master (pool allocation), Infrastructure Master (cross-domain refs). Global Catalog: port 3268 — partial attributes of all objects in forest. Sites & Services: replication topology, site links (cost, interval, schedule). LDAP search: base DN, scope (base/onelevel/subtree), filter (&(objectClass=user)(cn=*admin*)).</p>"),
        Q("Security & Delegation", "<p>KRBTGT: domain account encrypting Kerberos TGTs — must protect (golden ticket attack). Read-Only DC: branch office — no write capability, password caching disabled. AD groups: Domain Local (access on DCs), Global (access within domain), Universal (access across forest). OU delegation: delegate Control Wizard — assign reset password, join computer, manage group memberships. Managed Service Accounts: automatic password rotation. LAPS: manage local admin passwords — rotation, secure storage in AD. Microsoft Entra ID Connect: sync to cloud — password hash sync, PTA, ADFS.</p>"),
    ],[F("AD Docs","https://learn.microsoft.com/en-us/windows-server/identity/","Active Directory documentation"),F("AD Security","https://adsecurity.org/","Active Directory security resources")]),
    ("Group Policy", "group-policy.html", "Group Policy — administrative templates, security policies, preference, and troubleshooting.", "Windows", "fas fa-gear", [
        Q("GPO Fundamentals", "<p>Group Policy: configuration management for users and computers. Components: Administrative Templates (.admx — registry-based), Security Settings (password policy, user rights, audit policy), Preferences (drives, printers, scheduled tasks, files), Scripts (startup/shutdown, logon/logoff). GPO processing: LSDOU (local, site, domain, OU) — last writer wins. Enforce vs Block Inheritance: Enforce (no override), Block Inheritance (prevent inheritance from parent OUs). WMI filtering: apply GPO only if WMI query matches (OS version, free disk space).</p>"),
        Q("Administrative Templates & Troubleshooting", "<p>ADMX files: %SystemRoot%\\PolicyDefinitions — central store in SYSVOL. Custom ADMX: define registry-based policies. Security templates: secedit /configure /db secedit.sdb /cfg sec.inf. GPUpdate: gpupdate /force (immediate refresh), gpresult /r (RSOP report). Logs: GPO operational log (Event Viewer > Applications and Services > Microsoft > Windows > GroupPolicy). Slow link detection: 500 kbps default — GPO processing behavior. Loopback policy: Merge (user + computer) or Replace (computer only) — for kiosks and terminal servers.</p>"),
    ],[F("GP Docs","https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/","Group Policy documentation"),F("GP Best Practices","https://learn.microsoft.com/en-us/troubleshoot/windows-server/group-policy/","Group Policy troubleshooting")]),
    ("Windows Server", "windows-server.html", "Windows Server — roles, IIS, Hyper-V, Windows Admin Center, and Nano Server.", "Windows", "fab fa-microsoft", [
        Q("Server Roles & IIS", "<p>Windows Server roles: AD DS, DNS, DHCP, File Services, IIS (web server), Hyper-V (virtualization), WSUS (update services), Print Server, Remote Desktop Services. IIS: application pools (isolated worker processes), modules (rewrite, compression, auth, caching), URL rewrite, FTP, SSL binding, Failed Request Tracing for debugging. Web Deploy: msdeploy syncing. Configuration: PowerShell IIS module, IIS Manager. HTTP/2 support, WebSockets. Centralized Certificate Store: shared cert management.</p>"),
        Q("Hyper-V & Administration", "<p>Hyper-V: full virtualization — Generation 1 (BIOS) and Generation 2 (UEFI, Secure Boot). Features: Hyper-V Replica (async replication), Live Migration (no downtime), Storage Migration, Checkpoints (standard vs production), Nested Virtualization. PowerShell Direct: manage VM without network (Enter-PSSession -VMName). Shielded VMs: encrypted VMs with TPM — protect from hypervisor admin. Windows Admin Center: browser-based management — gateway for remote server management. Nano Server: headless, 90% smaller — for containers, Hyper-V hosts, and cloud.</p>"),
    ],[F("Windows Server Docs","https://learn.microsoft.com/en-us/windows-server/","Official Windows Server documentation"),F("IIS Docs","https://learn.microsoft.com/en-us/iis/","IIS configuration and reference")]),
    ("Windows Registry", "windows-registry.html", "Windows Registry — hives, keys, values, editing, backup, and forensic analysis.", "Windows", "fas fa-database", [
        Q("Registry Structure", "<p>Hives: HKLM (local machine — hardware, software, security, SAM, BCD), HKCU (current user — user profile), HKU (all user hives), HKCR (class registrations — file associations, COM), HKCC (current hardware profile). Key types: REG_SZ (string), REG_EXPAND_SZ (expandable string %VAR%), REG_DWORD (32-bit integer), REG_QWORD (64-bit), REG_BINARY, REG_MULTI_SZ (multiple strings). Registry virtualization: File > Registry redirection for legacy apps (Program Files). Registry reflection: 32/64-bit key separation (Wow6432Node).</p>"),
        Q("Editing & Forensics", "<p>Tools: regedit (GUI), reg.exe (CLI — reg query, reg add, reg delete, reg export), PowerShell (Get-ItemProperty, Set-ItemProperty -Path HKLM:\\Software\\... -Name value -Type String -Value data). Group Policy ADMX: registry-based policies. Registry backup: reg export HKLM\\Software backup.reg, PowerShell Export-CSV. Forensic artifacts: UserAssist (execution count + last run), MRU lists (most recently used), ShellBags (folder view settings), ShimCache (AppCompat — executed programs), AmCache (application compatibility cache), USB device history, network shares, RunMRU (run command history).</p>"),
    ],[F("Registry Reference","https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry","Windows registry documentation"),F("Registry Forensics","https://www.forensicmag.com/","Registry forensic analysis articles")]),
    ("WSL 2", "wsl-2.html", "Windows Subsystem for Linux 2 — full Linux kernel, VS Code integration, and Docker.", "Windows", "fab fa-linux", [
        Q("Installation & Configuration", "<p>WSL 2: full Linux kernel running in lightweight VM. Install: wsl --install (Ubuntu default), wsl --list --online (distros), wsl --install -d Debian. Version: wsl --set-version Ubuntu 2, wsl --set-default-version 2. Config: .wslconfig — [wsl2] memory=4GB processors=4 localhostForwarding=true. wsl.conf (inside distro) — [boot] command=\"service docker start\", [network] generateHosts=true. Path: Windows drives at /mnt/c/. Interop: run Windows .exe from Linux (notepad.exe, explorer.exe). WSLg: GUI application support.</p>"),
        Q("Integration & Docker", "<p>VS Code: code . in WSL installs Remote-WSL extension — full dev experience. Docker Desktop: WSL 2 backend — better performance, no Hyper-V. Or Docker Engine directly in WSL 2: install docker.io, dockerd started in background. systemd: WSL 2 now supports systemd — enable via [boot] systemd=true. Cross-filesystem: /mnt/c/Users/... — access Windows files from Linux. Performance: Linux filesystem faster (store projects in Linux home, not /mnt/c/). Git: use Git in WSL with credential manager (wsl.exe git config credential.helper /mnt/c/.../git-credential-manager.exe).</p>"),
    ],[F("WSL Docs","https://learn.microsoft.com/en-us/windows/wsl/","Official WSL documentation"),F("WSL GitHub","https://github.com/microsoft/WSL","WSL open source components")]),
    ("Windows Security", "windows-security.html", "Windows security — Defender, BitLocker, Windows Hello, and attack surface reduction.", "Windows", "fas fa-shield-virus", [
        Q("Windows Defender & ASR", "<p>Microsoft Defender: real-time protection, cloud-delivered, MPEngine. Config: Group Policy, Intune, PowerShell (Set-MpPreference). Attack Surface Reduction (ASR): rules — block Office child processes, block executable content from email, block credential stealing from LSASS. Controlled Folder Access: protect documents from ransomware. Exploit Guard: network protection, exploit protection (DEP, ASLR, CFG). Defender for Endpoint: EDR — behavioral detection, automated investigation, threat analytics.</p>"),
        Q("BitLocker & Windows Hello", "<p>BitLocker: full disk encryption — TPM + PIN or USB key. Recovery: 48-digit recovery key (back up to AD or Microsoft account). BitLocker To Go: removable drives. Layers: AES-128/256, diffuser (Elephant). Manage-bde: manage-bde -status C:, manage-bde -protectors -get C:. Windows Hello: biometric (fingerprint, face) or PIN — tied to TPM, replaces passwords. Credential Guard: isolate secrets (Kerberos, NTLM) in virtualized container — prevents pass-the-hash. Local Security Authority (LSA) protection: lsass.exe running as Protected Process Light.</p>"),
    ],[F("Windows Security Docs","https://learn.microsoft.com/en-us/windows/security/","Official Windows security documentation"),F("Microsoft Security Blog","https://www.microsoft.com/en-us/security/blog/","Security updates and best practices")]),
    ("Windows Networking", "windows-networking.html", "Windows networking — DNS, DHCP, RRAS, NLB, and monitoring tools.", "Windows", "fas fa-network-wired", [
        Q("DNS & DHCP", "<p>Windows DNS: zones (primary, secondary, AD-integrated), dynamic updates, scavenging, forwarders, conditional forwarders, DNSSEC. Records: A, AAAA, CNAME, MX, SRV, PTR, TXT. PowerShell: Add-DnsServerResourceRecordA, Get-DnsServerZone. DHCP: scopes, reservations, options (003 Router, 006 DNS), superscopes (multiple subnets), failover (hot standby, load balance), DHCPv6. DHCP policies: assign options based on vendor class or MAC prefix. Network Location Awareness: NLA detects network type (domain, private, public).</p>"),
        Q("Remote Access & Monitoring", "<p>RRAS (Routing and Remote Access Service): VPN (SSTP, L2TP/IPsec, IKEv2, PPTP), NAT, DirectAccess (always-on VPN — transparent). NLB (Network Load Balancing): cluster IP, port rules, affinity options (single/classic/none). Tools: Get-NetAdapter (NIC info), Test-NetConnection (ping + port), Get-NetTCPConnection, Resolve-DnsName. Performance Monitor: counters for network (\\Network Interface(*)\\Bytes Total/sec, (TCPv4)\\Segments Retransmitted/sec). Message Analyzer: advanced network protocol analyzer. Pktmon: built-in packet monitor (pktmon filter add -t UDP, pktmon start, pktmon stop).</p>"),
    ],[F("Windows Networking Docs","https://learn.microsoft.com/en-us/windows-server/networking/","Windows Server networking documentation"),F("PKTMon","https://learn.microsoft.com/en-us/windows-server/networking/technologies/pktmon/pktmon","Packet monitor tool guide")]),

    # === MOBILE (10) ===
    ("React Native", "react-native.html", "Cross-platform mobile apps with React Native — components, navigation, and native modules.", "Mobile", "fab fa-react", [
        Q("Core Components & Navigation", "<p>React Native: JavaScript with React patterns, compiles to native UI. Core: View, Text, ScrollView, FlatList (virtualized), TextInput, Image, TouchableOpacity. StyleSheet: StyleSheet.create({ container: { flex: 1, justifyContent: 'center' } }). Flexbox layout (flexDirection, alignItems, justifyContent). Navigation: React Navigation — Stack.Navigator (push/pop), Tab.Navigator (bottom tabs), Drawer.Navigator (side menu). Screen options: headerShown, tabBarIcon, gestureEnabled. Deep linking: linking configuration.</p>"),
        Q("Native Modules & State", "<p>Native modules: write native code (Java/Kotlin for Android, ObjC/Swift for iOS) exposed to JS. Turbo Modules (new architecture): synchronous, type-safe. Bridgeless: new architecture without the bridge. State: React state + Context API, Zustand (lightweight), Redux Toolkit, Jotai. AsyncStorage: key-value persistence. NetInfo: network status. Camera: react-native-vision-camera. Maps: react-native-maps. Expo: managed workflow — no native build setup needed. OTA updates: EAS Update, CodePush.</p>"),
    ],[F("React Native Docs","https://reactnative.dev/","Official React Native documentation"),F("Expo Docs","https://docs.expo.dev/","Expo development platform")]),
    ("Flutter Development", "flutter-development.html", "Cross-platform mobile with Flutter — widgets, state management, and platform channels.", "Mobile", "fab fa-flutter", [
        Q("Widgets & Layout", "<p>Flutter: compiled to native ARM code — Dart language. Widgets: StatelessWidget vs StatefulWidget (mutable state, setState). Layout: Container, Row, Column, Stack, Expanded, Flexible, Padding, SizedBox, ListView (scrollable), GridView. Material Design: Scaffold, AppBar, Drawer, BottomNavigationBar, FloatingActionButton, Card, ListTile, Chip, SnackBar. Cupertino (iOS-style): CupertinoPageScaffold, CupertinoNavigationBar, CupertinoTabBar. Text styling: TextStyle(fontSize, fontWeight, color, fontFamily). Theme: ThemeData, Theme.of(context). Platform-aware branching.</p>"),
        Q("State Management & Native", "<p>State: setState (simple), Provider, Riverpod, BLoC/Cubit, GetX. Provider: ChangeNotifierProvider(create: (context) => Counter()), context.watch<Counter>() / context.read<Counter>(). Riverpod: ref.read(counterProvider.notifier).increment(). Navigation: go_router (declarative routing, deep links). HTTP: http or dio packages. Platform channels: MethodChannel('channel'), invokeMethod('getBatteryLevel') calling native Kotlin/Swift. Packages: pub.dev — camera, location, maps, local_auth (biometrics), sqflite (SQLite), shared_preferences. Flutter Web: experimental web support.</p>"),
    ],[F("Flutter Docs","https://docs.flutter.dev/","Official Flutter documentation"),F("pub.dev","https://pub.dev/","Dart and Flutter package repository")]),
    ("Android Development (Kotlin)", "android-kotlin.html", "Android development with Kotlin — Jetpack Compose, Activities, and Material Design.", "Mobile", "fab fa-android", [
        Q("Jetpack Compose", "<p>Jetpack Compose: declarative UI toolkit. @Composable fun Greeting(name: String) { Text(\"Hello $name\") }. Modifier: .padding(), .fillMaxWidth(), .clickable {}, .background(), .size(). State: remember { mutableStateOf(0) }, var count by remember { mutableIntStateOf(0) }. LazyColumn (recyclable list), LazyRow, Scaffold, TopAppBar, BottomBar. Material 3: NavigationBar, NavigationDrawer, Card, Surface, Button, TextField. theming: MaterialTheme(colorScheme, typography). Preview: @Preview annotation. ViewModel + StateFlow for architecture.</p>"),
        Q("Activities & Services", "<p>Activity: entry point — single screen. Intent: navigate between activities (explicit by class, implicit by action). Lifecycle: onCreate, onStart, onResume, onPause, onStop, onDestroy — ViewModel survives config changes. Fragment: reusable screen portion — FragmentManager, NavHost (Jetpack Navigation). Service: background work — Foreground Service (notification), JobIntentService (compat), WorkManager (deferred work). BroadcastReceiver: system events (boot, connectivity, battery). ContentProvider: share data between apps. Manifest: AndroidManifest.xml — permissions, components, features.</p>"),
    ],[F("Android Docs","https://developer.android.com/docs","Official Android documentation"),F("Kotlin Docs","https://kotlinlang.org/docs/","Official Kotlin language docs")]),
    ("iOS Development (Swift)", "ios-swift.html", "iOS development with Swift — SwiftUI, UIKit, and App Store deployment.", "Mobile", "fab fa-apple", [
        Q("SwiftUI", "<p>SwiftUI: declarative UI — struct ContentView: View { var body: some View { Text(\"Hello\").font(.title) } }. Layout: VStack, HStack, ZStack, List, ScrollView, LazyVGrid, NavigationStack, TabView. State: @State private var count = 0, @Binding (parent to child), @ObservedObject / @StateObject (ObservableObject), @EnvironmentObject (shared). Modifiers: .padding(), .foregroundColor(), .frame(), .background(), .clipShape(), .shadow(). Navigation: NavigationLink, .navigationDestination(). Previews: #Preview { ContentView() }. Swift Charts: Chart { BarMark(x: , y:) }.</p>"),
        Q("UIKit & App Lifecycle", "<p>UIKit: legacy but still essential. ViewController: UIViewController — viewDidLoad, viewWillAppear, viewDidAppear. Auto Layout: NSLayoutConstraint, Visual Format Language, SnapKit (third-party). Storyboards vs XIBs vs code-only UI. App lifecycle: AppDelegate (didFinishLaunching, scene configuration), SceneDelegate (multi-window iPadOS). Codable: Encodable/Decodable for JSON. Core Data: persistent storage, NSPredicate queries, CloudKit sync. Combine: reactive framework — Publisher, Subscriber, @Published. async/await: Swift concurrency, URLSession async, Task, Actor.</p>"),
    ],[F("Apple Developer Docs","https://developer.apple.com/documentation/","Official Apple developer documentation"),F("Swift.org","https://www.swift.org/documentation/","Swift programming language")]),
    ("Mobile UI/UX Design", "mobile-ui-ux.html", "Design mobile interfaces — gesture design, navigation patterns, and accessibility.", "Mobile", "fas fa-pen-ruler", [
        Q("Design Patterns & Gestures", "<p>Mobile navigation: tab bar (primary), stack (drill-down), drawer (secondary), search bar (discovery). Gestures: tap, double-tap, long press, swipe (dismiss, reveal actions), pinch-to-zoom, pan/drag, rotation. Touch targets: minimum 44x44pt (Apple HIG), 48x48dp (Material). Bottom sheet: action sheet, half modal, expandable sheet. Pull-to-refresh: standard pattern for content refresh. FAB (Floating Action Button): primary action, can expand to multiple. Snackbar: non-intrusive feedback. Haptic feedback: impact, notification, selection.</p>"),
        Q("Accessibility & Platform Guidelines", "<p>iOS HIG: Human Interface Guidelines — clarity, deference, depth. Safe areas, notch, Dynamic Island handling. Android Material Design 3: color system (primary, secondary, tertiary, error), typography (type scale), elevation (surface tones). Accessibility: VoiceOver/TalkBack, dynamic type (large text), sufficient contrast (4.5:1 for small text), focus indicators, reduce motion, semantic labels. Adaptive layout: size classes (iOS), screen width breakpoints (Android — compact, medium, expanded). Design tools: Figma (components, auto layout, variants), Prototyping (Smart Animate, overlay).</p>"),
    ],[F("Apple HIG","https://developer.apple.com/design/human-interface-guidelines/","iOS design guidelines"),F("Material 3","https://m3.material.io/","Material Design 3 guidelines")]),
    ("Mobile Security", "mobile-security.html", "Mobile app security — OWASP Mobile Top 10, code obfuscation, and runtime protection.", "Mobile", "fas fa-shield", [
        Q("OWASP Mobile Top 10", "<p>M1: Improper Credential Usage (hardcoded keys, weak auth). M2: Inadequate Supply Chain Security (vulnerable libraries — OSS Index, Snyk). M3: Insecure Authentication (token storage, biometric bypass). M4: Insufficient Authorization (IDOR, client-side enforcement). M5: Insufficient Input/Output Validation (injection). M6: Insecure Communication (no TLS pinning, HTTP instead of HTTPS). M7: Inadequate Privacy (excessive data collection, analytics leakage). M8: Insecure Data Storage (SharedPreferences, NSUserDefaults, SQLite unencrypted). M9: Insecure Configuration (debug enabled, backup allowed). M10: Insufficient Attestation (root detection bypass).</p>"),
        Q("Protection Techniques", "<p>Code obfuscation: ProGuard/R8 (Android), SwiftShield (iOS). Root/jailbreak detection: SafetyNet/Play Integrity (Android), DeviceCheck (iOS), custom checks (SU binary, Cydia). Certificate pinning: OkHttp CertificatePinner (Android), TrustKit (iOS), TrustManager (manual). Runtime protection: Siren/in-app update check, Firebase Remote Config (kill switch). Secure storage: Android Keystore, iOS Keychain, EncryptedSharedPreferences. Biometric auth: BiometricPrompt (Android), LAContext (iOS). App attestation: iOS App Attest, Android Play Integrity API. OWASP MSTG: comprehensive mobile security testing guide.</p>"),
    ],[F("OWASP Mobile Top 10","https://owasp.org/www-project-mobile-top-10/","Mobile security risks"),F("Mobile Security Testing Guide","https://github.com/OWASP/owasp-mstg","OWASP MSTG guide")]),
    ("Push Notifications", "push-notifications.html", "Push notifications — FCM, APNs, notification channels, and best practices.", "Mobile", "fas fa-bell", [
        Q("FCM & APNs", "<p>Firebase Cloud Messaging: cross-platform. Setup: google-services.json, FirebaseMessagingService extends Service, onNewToken(token), onMessageReceived(remoteMessage). Token: registration token (device-specific) — send to app server. Message types: notification (displayed automatically), data (custom handling), notification+data (both). Topics: subscribe to topic, broadcast to all subscribers. Conditions: subscribe with logical OR/AND of topics. APNs: Apple Push Notification service — device token, payload (alert, badge, sound, content-available for background fetch). Certificate vs Token-based auth (.p8 key).</p>"),
        Q("Notification Design", "<p>Android channels: NotificationChannel(id, name, importance) — Importance HIGH for heads-up, DEFAULT for sound, LOW for no sound, MIN for no UI. Grouping: setGroup for stacked notifications. Direct reply: RemoteInput for inline replies. Action buttons: up to 3. Progress: setProgress(max, current, indeterminate). iOS categories: UNNotificationCategory with actions. Rich notifications: media attachments (image, video, audio). Notification Service Extension: modify content before display. Push priority: time-sensitive, passive, critical alerts. Rate limiting: FCM (600k/min per project), APNs (no hard limit, but exponential backoff on errors).</p>"),
    ],[F("FCM Docs","https://firebase.google.com/docs/cloud-messaging","Firebase Cloud Messaging"),F("APNs Docs","https://developer.apple.com/documentation/usernotifications/","Apple push notifications")]),
    ("App Store Publishing", "app-store-publishing.html", "Publishing to App Store and Google Play — signing, review, in-app purchases, and ASO.", "Mobile", "fas fa-rocket", [
        Q("Google Play Publishing", "<p>Play Console: developer account ($25), app signing (Play App Signing — key managed by Google, upload key separate). Store listing: title (30 chars), short description (80), full description (4000), screenshots (2-8 per device type), feature graphic (1024x500). APK vs AAB: Android App Bundle recommended — size reduction, dynamic delivery, on-demand modules. Internal/Closed/Open testing tracks — production after testing. In-app products: managed products (one-time), subscriptions (auto-renewing, base plans + offers). Pricing: user's local currency, tax handling.</p>"),
        Q("App Store Publishing", "<p>App Store Connect: Apple Developer Program ($99/year). Certificates: Development, Distribution (App Store), Push Notification, Pass Type ID. Provisioning profiles: Development, Ad Hoc (limited devices), App Store (distribution). App review guidelines: 4.2 minimum functionality, 2.3 accurate metadata, 5.1 privacy (permissions, data collection), 3.1 IAP (digital goods). TestFlight: internal testing (up to 100 users), external testing (up to 10k, requires Beta App Review). IAP: consumable, non-consumable, auto-renewable, non-renewing. In-app events: timely events, live streams. SKAdNetwork: privacy-preserving ad attribution (iOS 14.5+). ASO: keyword optimization, rating/review management, A/B testing (product page optimization).</p>"),
    ],[F("Google Play Console Help","https://support.google.com/googleplay/android-developer/","Play Console documentation"),F("App Store Connect Help","https://developer.apple.com/help/app-store-connect/","App Store Connect guide")]),
    ("Mobile Performance", "mobile-performance.html", "Mobile app performance — profiling, memory, startup time, and rendering optimization.", "Mobile", "fas fa-gauge-high", [
        Q("Profiling & Memory", "<p>Android profiling: Android Studio Profiler (CPU, memory, network, energy). Memory: dumpsys meminfo, Allocation Tracker, MAT (Memory Analyzer Tool) for heap dumps. LeakCanary: auto-detect memory leaks. iOS profiling: Instruments — Time Profiler, Allocations, Leaks, Energy Log. Memory warnings: didReceiveMemoryWarning, override func applicationDidReceiveMemoryWarning. Images: resize to display size, use thumbnails, cache with LRU (Glide/Picasso for Android, Kingfisher/SDWebImage for iOS). Lazy loading: paginate lists, use placeholders. App thinning: Slicing, Bitcode, On-Demand Resources.</p>"),
        Q("Startup & Rendering", "<p>Cold start: process creation to first frame. Hot start: activity/view controller recreated. Warm start: process alive but activity recreated. Optimizations: defer SDK init (lazy), class verification (baseline profiles for Android), reduce dynamic linker work, minimize main thread work. Android Baseline Profiles: AOT compilation of critical paths. Rendering: 16ms frame budget (60fps). Overdraw: GPU debug overdraw (Android), Color Blended Layers (iOS). Reduce overdraw: remove background layers, clip rects, use opaque when possible. View hierarchy: flatten deeply nested layouts (ConstraintLayout, Compose).</p>"),
    ],[F("Android Performance","https://developer.android.com/topic/performance","Android performance optimization"),F("iOS Performance","https://developer.apple.com/library/archive/documentation/Performance/Conceptual/PerformanceOverview/","iOS performance overview")]),
    ("Cross-Platform Mobile Tools", "cross-platform-mobile.html", "Cross-platform tools — Kotlin Multiplatform, .NET MAUI, and Progressive Web Apps.", "Mobile", "fas fa-mobile-button", [
        Q("Kotlin Multiplatform", "<p>KMP: shared business logic in Kotlin, native UI per platform. expect/actual: platform-specific implementations — expect fun getPlatform(): Platform, actual fun getPlatform(): Platform = AndroidPlatform(). Shared module: commonMain (shared code), androidMain (Android), iosMain (iOS). Libraries: Ktor (HTTP client), SQLDelight (database), kotlinx.serialization (JSON), kotlinx.coroutines (async). Compose Multiplatform: shared UI using Jetpack Compose across Android, iOS, desktop. CocoaPods/Swift Package Manager integration for iOS. Gradle: multi-module project structure.</p>"),
        Q(".NET MAUI & PWAs", "<p>.NET MAUI: Xamarin.Forms evolution — one project for Android, iOS, macOS, Windows. Pages: ContentPage, NavigationPage, TabbedPage, Shell (flyout, tabs). MVVM: CommunityToolkit.Mvvm — ObservableObject, RelayCommand. Handlers: custom native mappings. Blazor Hybrid: Blazor Web UI in native MAUI shell. PWAs: service worker, manifest.json, offline support, install prompt. Workbox: simplify service worker generation. PWA capabilities: push notifications, background sync, periodic sync, file system access, Web Bluetooth. Lighthouse: PWA audit tool. Trade-offs: PWA (no App Store, limited native APIs), KMP (more native), MAUI (Windows + mobile).</p>"),
    ],[F("KMP Docs","https://kotlinlang.org/docs/multiplatform.html","Kotlin Multiplatform documentation"),F(".NET MAUI Docs","https://learn.microsoft.com/en-us/dotnet/maui/",".NET MAUI documentation")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials (p3a)!")
