#!/usr/bin/env python3
"""Generate ~31 tutorials — Networking, Programming Concepts, Hardware."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === NETWORKING (10) ===
    ("TCP/IP & OSI Model", "tcpip-osi-model.html", "Understand the TCP/IP stack and OSI model — layers, protocols, and packet flow.", "Networking", "fas fa-sitemap", [
        Q("OSI Model Layers", "<p>OSI (Open Systems Interconnection): 7 layers. Layer 7 Application: HTTP, FTP, SMTP, DNS — user-facing protocols. Layer 6 Presentation: encryption (TLS), compression, character encoding (ASCII, UTF-8). Layer 5 Session: session management, NetBIOS, RPC. Layer 4 Transport: TCP (reliable, connection-oriented), UDP (unreliable, connectionless), SCTP. Layer 3 Network: IP, ICMP, ARP, routing protocols — packet forwarding. Layer 2 Data Link: Ethernet, MAC addresses, switches, ARP, VLANs. Layer 1 Physical: cables (Cat5e/6/6a, fiber), signal encoding, hubs, repeaters.</p>"),
        Q("TCP/IP Stack", "<p>TCP/IP (Internet protocol suite): 4 layers. Application (OSI L5-7): HTTP, SSH, DNS, TLS. Transport (L4): TCP (segments, sequencing, ACK, retransmission, flow control with sliding window, congestion control with slow start, congestion avoidance, fast retransmit), UDP (datagrams, no guarantee). Internet (L3): IP (packets, routing), ICMP (ping, traceroute), IGMP (multicast), IPsec. Link (L1-2): Ethernet frames, WiFi, physical transport. Encapsulation: data > TCP/UDP header (segment) > IP header (packet) > Ethernet header (frame) > bits. Key: each layer adds its header, peer layers communicate via headers.</p>"),
    ],[F("TCP/IP Guide","https://www.tcpipguide.com/","Comprehensive TCP/IP reference"),F("OSI Model RFC","https://www.iso.org/standard/20269.html","ISO OSI standard")]),
    ("HTTP & HTTPS", "http-https.html", "HTTP/1.1, HTTP/2, HTTP/3 — methods, headers, caching, TLS, and security.", "Networking", "fas fa-globe", [
        Q("HTTP Protocol & Versions", "<p>HTTP: request-response protocol. Methods: GET (read), POST (create), PUT (replace), PATCH (partial update), DELETE, HEAD, OPTIONS, CONNECT. Status codes: 1xx (informational — 101 Switching Protocols), 2xx (success — 200 OK, 201 Created, 204 No Content), 3xx (redirect — 301 Moved Permanently, 302 Found, 304 Not Modified), 4xx (client error — 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 429 Too Many Requests), 5xx (server error — 500 Internal Server Error, 502 Bad Gateway, 503 Service Unavailable). HTTP/2: multiplexed streams (one TCP connection), header compression (HPACK), server push, binary framing layer. HTTP/3: QUIC (UDP-based), 0-RTT, connection migration, no head-of-line blocking.</p>"),
        Q("Caching & TLS", "<p>Caching headers: Cache-Control (max-age, no-cache, no-store, public, private, immutable, stale-while-revalidate), ETag (entity tag — conditional requests with If-None-Match), Last-Modified (If-Modified-Since), Expires (deprecated in favor of Cache-Control). Cookies: Set-Cookie (name=value; Domain; Path; Secure; HttpOnly; SameSite=Strict/Lax/None). CORS: Access-Control-Allow-Origin, preflight OPTIONS request. TLS: handshake (ClientHello > ServerHello > Certificate > Key Exchange > Finished), cipher suites (TLS_AES_128_GCM_SHA256), TLS 1.3 (1-RTT handshake, 0-RTT resumption, no RC4/3DES/RC5, deprecated RSA key exchange). HSTS: Strict-Transport-Security header. mTLS: mutual TLS — client also presents certificate.</p>"),
    ],[F("HTTP Semantics RFC 9110","https://httpwg.org/specs/rfc9110.html","HTTP semantics and content"),F("TLS 1.3 RFC 8446","https://datatracker.ietf.org/doc/html/rfc8446","TLS 1.3 specification")]),
    ("DNS Deep Dive", "dns-deep-dive.html", "Domain Name System — resolution, record types, DNSSEC, and advanced configurations.", "Networking", "fas fa-globe", [
        Q("Resolution & Record Types", "<p>DNS: hierarchical, distributed naming system. Resolution: recursive resolver queries root servers (.), TLD servers (.com, .org), authoritative nameserver. Recursive: resolver does all work (ISP, 8.8.8.8). Iterative: client follows referrals. Record types: A (IPv4 address), AAAA (IPv6 address), CNAME (alias — points to another name), MX (mail server — priority), TXT (arbitrary text — SPF, DKIM, DMARC), NS (nameserver), SOA (start of authority — serial, refresh, retry, expire, TTL), PTR (reverse DNS — IP to hostname), SRV (service location), CAA (certificate authority authorization). DNS propagation: TTL (time to live) — lower TTL for migrations.</p>"),
        Q("DNSSEC & Advanced", "<p>DNSSEC: cryptographic signing of DNS records — RRSIG (signature), DNSKEY (public key), DS (delegation signer — chain of trust), NSEC/NSEC3 (authenticated denial of existence). Validation: resolver checks signatures up to root trust anchor. DNS over HTTPS (DoH): DNS queries over HTTPS (Cloudflare 1.1.1.1, Google 8.8.8.8). DNS over TLS (DoT): DNS on port 853. Split-horizon DNS: different answers based on client IP (internal vs external). Dynamic DNS: update DNS records when IP changes (DDNS). Anycast: same IP from multiple locations — route to nearest. mDNS: local network discovery (.local). EDNS: extension mechanisms for DNS (larger payloads).</p>"),
    ],[F("DNS RFCs","https://www.ietf.org/standards/rfcs/","IETF DNS standards"),F("DNSSEC Guide","https://dnssec-guide.cloudflare.com/","Cloudflare DNSSEC guide")]),
    ("VPNs & Tunneling", "vpn-tunneling.html", "Virtual Private Networks — WireGuard, OpenVPN, IPsec, and secure site-to-site connections.", "Networking", "fas fa-eye-slash", [
        Q("VPN Protocols", "<p>VPN: encrypted tunnel between endpoints. WireGuard: modern, performant — kernel-level (Linux), ChaCha20 encryption, Curve25519 key exchange, Noise protocol. Config: [Interface] PrivateKey = ... Address = 10.0.0.1/24 [Peer] PublicKey = ... AllowedIPs = 10.0.0.0/24 Endpoint = server:51820. OpenVPN: TLS-based, flexible — UDP (preferred) or TCP, tun (layer 3) or tap (layer 2), certificate-based auth. Config: dev tun, proto udp, port 1194, cipher AES-256-GCM, auth SHA-256. IPsec: IKEv1/IKEv2 — tunnel mode (entire packet encrypted) vs transport mode (payload only). StrongSwan: modern IPsec implementation.</p>"),
        Q("Site-to-Site & Remote Access", "<p>Site-to-site: connect entire networks — IPSec tunnel between routers (AWS VPN, Azure VPN Gateway). WireGuard: wg-quick up wg0 — multiple peers, automatic routing. Remote access: client connects to concentrator — OpenVPN (TLS handshake, MFA), WireGuard (simple config, no built-in MFA — use with SSO). Split tunneling: only corporate traffic goes through VPN (10.0.0.0/8, 172.16.0.0/12). Full tunnel: all traffic through VPN. Mesh VPN: Tailscale (WireGuard-based — SSO, ACLs), ZeroTier (L2). VPN vs Proxy: VPN (encrypted tunnel, system-wide), SOCKS5 proxy (no encryption, per-app). Cloud VPN: AWS Client VPN, Azure P2S, GCP Cloud VPN.</p>"),
    ],[F("WireGuard Docs","https://www.wireguard.com/","WireGuard VPN protocol"),F("OpenVPN Docs","https://openvpn.net/community/","OpenVPN community resources")]),
    ("Load Balancing", "load-balancing.html", "Load balancing — algorithms, reverse proxies, health checks, and global server load balancing.", "Networking", "fas fa-balance-scale", [
        Q("Algorithms & Reverse Proxy", "<p>Load balancing: distribute traffic across multiple servers. Algorithms: round-robin (sequential), least-connections (to fewest active), IP hash (stickiness — session persistence), weighted round-robin (different capacities), random, least-response-time. Reverse proxy: nginx (upstream block), HAProxy (frontend/backend), Traefik (auto-discovery, Let's Encrypt), Caddy (automatic HTTPS). Config (nginx): upstream backend { server 10.0.0.1:3000 weight=3; server 10.0.0.2:3000; } server { location / { proxy_pass http://backend; } }. Session persistence: sticky cookies (Set-Cookie with backend ID), IP hash, Redis-backed sessions.</p>"),
        Q("Health Checks & GSLB", "<p>Health checks: passive (proxy detects failure by connection errors), active (periodic probe — HTTP /health, TCP connect). Unhealthy: remove from pool until healthy again. Circuit breaker: stop sending after N failures. Rate limiting: nginx limit_req_zone, limit_conn_zone. GSLB (Global Server Load Balancing): DNS-based (geo-aware DNS, weighted records), Anycast (same IP, routed to nearest datacenter). Cloud LBs: AWS ALB (HTTP/HTTPS), NLB (TCP/UDP), GCLB (global HTTP), Azure Load Balancer. Layer 4 (transport) vs Layer 7 (application): L4 faster, L7 smarter (header-based routing, content switching).</p>"),
    ],[F("NGINX LB Docs","https://docs.nginx.com/nginx/admin-guide/load-balancer/","NGINX load balancing guide"),F("HAProxy Docs","https://www.haproxy.org/documentation/","HAProxy documentation")]),
    ("Firewalls & Security Groups", "firewalls-security-groups.html", "Firewalls — stateful, stateless, WAF, network ACLs, and zero-trust architecture.", "Networking", "fas fa-fire", [
        Q("Stateful vs Stateless", "<p>Stateful firewall: tracks connection state (NEW, ESTABLISHED, RELATED, INVALID) — allows return traffic automatically. Example: iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT. Stateless firewall: each packet evaluated individually — must allow both directions explicitly. Network ACLs: stateless — AWS NACL (subnet-level, numbered rules, allow/deny). Security Groups: stateful — AWS SG (instance-level, allow rules only). pfSense: open-source firewall — traffic shaping, VPN, DNS forwarding, captive portal. OPNsense: pfSense fork with modern UI. Firewalld (Linux): zones (public, internal, DMZ), services, rich rules.</p>"),
        Q("WAF & Zero Trust", "<p>WAF (Web Application Firewall): protects web apps from OWASP Top 10 — SQL injection, XSS, CSRF, RFI/LFI. ModSecurity: open-source WAF engine — CRS (Core Rule Set). Cloud WAF: Cloudflare WAF, AWS WAF, Azure WAF, Fastly. Rate limiting: mitigate DDoS and brute force. Zero Trust: never trust, always verify — micro-segmentation (each app in its own segment), least-privilege access, explicit verification. BeyondCorp: Google's zero-trust model — access based on device + user identity, not network location. ZTNA: Zscaler, Cloudflare Access, Twingate — no VPN needed. Next-Gen Firewall (NGFW): application awareness (Deep Packet Inspection), IPS, TLS inspection, user identity.</p>"),
    ],[F("ModSecurity Docs","https://modsecurity.org/","WAF engine documentation"),F("Zero Trust Architecture NIST","https://www.nist.gov/publications/zero-trust-architecture","NIST SP 800-207")]),
    ("Routing Protocols (BGP & OSPF)", "routing-protocols.html", "Dynamic routing — BGP, OSPF, IS-IS, route redistribution, and network design.", "Networking", "fas fa-route", [
        Q("OSPF & IS-IS", "<p>OSPF (Open Shortest Path First): link-state, uses Dijkstra's SPF algorithm. Areas: backbone (area 0), standard areas, stub areas (no external routes), NSSA. LSA types: Router (1), Network (2), Summary (3/4), ASBR (5/7). Hello protocol: discover neighbors, elect DR/BDR (broadcast networks). Timers: hello (10s), dead (40s). Cost = reference bandwidth / interface bandwidth. DR/BDR: reduce adjacencies on broadcast networks. Authentication: MD5 or SHA. IS-IS: similar to OSPF — used by ISPs, CLNS-based, entire router in one area. BGP: path-vector protocol — designed for the Internet.</p>"),
        Q("BGP & Route Redistribution", "<p>BGP (Border Gateway Protocol): AS path, next-hop, multi-exit discriminator, local preference, communities. eBGP: between different ASes (peering). iBGP: within same AS (full mesh or route reflectors). Attributes: AS_PATH (loop prevention — prepend to influence outbound), LOCAL_PREF (higher preferred — inbound adjustment), MED (lower preferred — outbound adjustment), COMMUNITIES (NO_EXPORT, NO_ADVERTISE). Route reflectors: reduce iBGP mesh — RR reflects routes to clients. BGP convergence: slow (route flap damping). Route redistribution: between protocols (OSPF to BGP) — careful with administrative distance. BGP security: RPKI (ROA validation), BGPsec.</p>"),
    ],[F("BGP RFC 4271","https://datatracker.ietf.org/doc/html/rfc4271","BGP specification"),F("OSPF RFC 2328","https://datatracker.ietf.org/doc/html/rfc2328","OSPF version 2 specification")]),
    ("Network Security (TLS, mTLS, PKI)", "network-security.html", "Network security — PKI, certificates, mTLS, SSH, and secure protocols.", "Networking", "fas fa-shield-halved", [
        Q("PKI & Certificates", "<p>PKI (Public Key Infrastructure): CAs, certificates, CRLs, OCSP. X.509 certificate: subject, issuer, validity, public key, extensions (SAN, key usage, extended key usage, basic constraints). CA hierarchy: root CA (offline, self-signed), intermediate CAs (issuing), end-entity certs (servers, clients). Certificate chain: server cert > intermediate > root. CSR: openssl req -new -key server.key -out server.csr. Self-signed: openssl req -x509 -days 365 -key ca.key -out ca.crt. Let's Encrypt: automated ACME protocol — certbot, DNS-01, HTTP-01 challenges. Certificate pinning: pin public key or cert — risky (pinning failure = outage).</p>"),
        Q("mTLS & SSH", "<p>mTLS (mutual TLS): both client and server present certificates. Use cases: microservice-to-microservice (service mesh — Istio, Linkerd), API authentication, zero-trust networking. ACME: Automated Certificate Management Environment — certbot, acme.sh, Lego. SSH: secure remote access — key pairs (ed25519 preferred; RSA 4096 minimum). SSH config: ~/.ssh/config — Host *, HostName, User, IdentityFile, Port. SSH agent: ssh-add, ssh-agent, agent forwarding (use with caution). Hardening: disable password auth, disable root login, use port 22 (moving port is obscurity), fail2ban, 2FA. SSH tunnels: local (-L), remote (-R), dynamic (-D SOCKS5). SSH Certificate Authority: sign host and user keys — eliminates known_hosts warnings.</p>"),
    ],[F("Let's Encrypt Docs","https://letsencrypt.org/docs/","Free automated certificates"),F("SSH Hardening Guide","https://www.ssh-audit.com/hardening_guides.html","SSH security recommendations")]),
    ("SDN & Network Automation", "sdn-network-automation.html", "Software-Defined Networking — OpenFlow, SDN controllers, NetOps, and automation tools.", "Networking", "fas fa-network-wired", [
        Q("SDN Architecture", "<p>SDN: decouple control plane from data plane. Planes: management (monitoring, orchestration), control (routing decisions — SDN controller), data (packet forwarding — switches, routers). OpenFlow: protocol between controller and switches — flow tables (match fields, counters, instructions). SDN Controllers: ONOS (Open Network Operating System), OpenDaylight, Ryu (Python-based), POX, Floodlight. Southbound interfaces: OpenFlow, NETCONF, OVSDB. Northbound interfaces: REST APIs to applications. Open vSwitch (OVS): production-quality virtual switch — OpenFlow support. VXLAN: overlay networking — tunnel L2 over L3.</p>"),
        Q("Network Automation", "<p>Network automation: reduce manual config, ensure consistency. Ansible networking: provider-specific modules (ios_config, nxos_config, junos_config), napalm (multi-vendor). Netmiko: Python library for SSH network devices. NAPALM: vendor-agnostic API — get_facts, get_config, commit, rollback. YANG: data modeling language for network config. NETCONF: protocol for YANG-based config management (RFC 6241). RESTCONF: RESTful API to YANG datastores. SaltStack: network automation with proxy minions. CI/CD for network: git-based config management, automated testing (batfish for config validation). Nornir: Python automation framework (threaded, no SSH daemon needed).</p>"),
    ],[F("OpenFlow Spec","https://opennetworking.org/sdn-resources/","Open Networking Foundation"),F("Ansible Networking","https://docs.ansible.com/ansible/latest/network/","Ansible network modules")]),
    ("Wireless Networking", "wireless-networking.html", "Wireless networks — WiFi 6/7, mesh, security, and spectrum management.", "Networking", "fas fa-wifi", [
        Q("WiFi Standards & Spectrum", "<p>WiFi standards: 802.11b (11 Mbps, 2.4 GHz), 802.11g (54 Mbps, 2.4 GHz), 802.11n (WiFi 4 — up to 600 Mbps, MIMO), 802.11ac (WiFi 5 — up to 3.5 Gbps, 5 GHz, MU-MIMO), 802.11ax (WiFi 6 — up to 9.6 Gbps, 2.4/5/6 GHz, OFDMA, TWT), 802.11be (WiFi 7 — up to 46 Gbps, 320 MHz channels, multi-link operation). Frequency bands: 2.4 GHz (longer range, more interference, 3 non-overlapping channels 1/6/11), 5 GHz (shorter range, more channels, DFS), 6 GHz (WiFi 6E/7 — very clean, 1200 MHz spectrum). MIMO: multiple antennas for spatial streams. MU-MIMO: simultaneous transmission to multiple devices. Beamforming: focus signal toward clients.</p>"),
        Q("Security & Mesh", "<p>Wireless security: WPA3 (SAE handshake — dictionary attack resistant, 192-bit mode), WPA2 (CCMP/AES, pre-shared key — vulnerable to KRACK). WPA3-Enterprise: 802.1X with EAP-TLS (certificate auth). RADIUS: centralized auth — FreeRADIUS, Cisco ISE. EAP methods: PEAP, EAP-TLS, EAP-TTLS. Mesh networks: multiple APs with one SSID — seamless roaming (802.11r/k/v fast roaming). Mesh vs wired AP: mesh easier to deploy, wired AP better performance. Captive portal: splash page for guest access. WiFi analytics: signal strength (RSSI), channel utilization, interference sources. RF planning: site survey (Ekahau, NetSpot), heat maps, channel reuse. PoE: power over Ethernet (802.3af 15.4W, 802.3at 30W, 802.3bt 60/90W).</p>"),
    ],[F("WiFi Alliance","https://www.wi-fi.org/","WiFi standards and certification"),F("WPA3 Spec","https://www.wi-fi.org/wpa3","WPA3 security standard")]),

    # === PROGRAMMING CONCEPTS (13) ===
    ("Object-Oriented Programming", "object-oriented-programming.html", "OOP — classes, inheritance, polymorphism, encapsulation, and SOLID principles.", "Programming Concepts", "fas fa-cubes", [
        Q("Core Principles", "<p>OOP: paradigm based on objects combining data and behavior. Encapsulation: hide internal state, expose via methods — private fields, public getters/setters. Access modifiers: public, protected, private (language-specific). Inheritance: IS-A relationship — subclass extends superclass. Types: single (Java), multiple (C++/Python — diamond problem), multilevel, hierarchical. Composition: HAS-A relationship — object contains other objects (prefer over inheritance — Gang of Four). Polymorphism: many forms — compile-time (method overloading, operator overloading), runtime (method overriding, virtual functions). Abstraction: hide complexity — abstract classes (partial implementation), interfaces (contract).</p>"),
        Q("SOLID Principles", "<p>S: Single Responsibility (SRP) — one class, one reason to change. O: Open/Closed (OCP) — open for extension, closed for modification. L: Liskov Substitution (LSP) — derived class must be substitutable for base class. I: Interface Segregation (ISP) — many specific interfaces > one general interface. D: Dependency Inversion (DIP) — depend on abstractions, not concretions. Dependency Injection: constructor, setter, interface-based injection. DI containers: Spring (Java), Guice, ASP.NET Core DI. Design patterns: Creational (Factory, Singleton, Builder), Structural (Adapter, Decorator, Proxy), Behavioral (Observer, Strategy, Command). OOP vs FP: OOP (mutable state, side effects, methods on objects) vs FP (immutability, pure functions).</p>"),
    ],[F("SOLID Principles","https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design","SOLID explained"),F("Design Patterns Book","https://www.oodesign.com/","Gang of Four design patterns")]),
    ("Functional Programming", "functional-programming.html", "Functional programming — pure functions, immutability, monads, and lambda calculus.", "Programming Concepts", "fas fa-lambda", [
        Q("Core Concepts", "<p>Functional programming: computation as evaluation of mathematical functions. Pure functions: same input always same output, no side effects (no I/O, no mutable state change). Immutability: data cannot be changed — create new copies instead. Referential transparency: expression can be replaced by its value without changing program behavior. Higher-order functions: functions that take functions as arguments or return functions — map, filter, reduce. First-class functions: functions treated as values — assigned to variables, passed as arguments. Currying: transform function with multiple args into chain of single-arg functions (f(a,b,c) -> f(a)(b)(c)). Partial application: fix some arguments, produce function for remaining.</p>"),
        Q("Monads & Practical FP", "<p>Monad: type with flatMap/bind and unit/return — Maybe/Option (handle null), Either/Result (error handling), List, IO (lazy I/O). Laws: left identity, right identity, associativity. Functor: type with map/fmap — apply function to wrapped value. Applicative: apply wrapped function to wrapped value. Pattern matching: destructure and branch on types — powerful in Scala, Haskell, Rust, Elixir. Practical FP languages: Haskell (pure, lazy), Scala (OOP + FP), Elixir (actor model + FP), Clojure (Lisp on JVM), F# (.NET FP), OCaml. JavaScript/TypeScript: lodash/fp, Ramda, fp-ts, RxJS (reactive). Kotlin: lambda syntax, sequences, Arrow. Rust: ownership + FP patterns. Benefits: testability, concurrency safety (immutable data), modularity.</p>"),
    ],[F("Functional Programming in Haskell","https://www.haskell.org/documentation/","Haskell functional programming"),F("Learn You a Haskell","http://learnyouahaskell.com/","Introductory Haskell book")]),
    ("Design Patterns", "design-patterns.html", "Software design patterns — creational, structural, behavioral, and architectural patterns.", "Programming Concepts", "fas fa-puzzle-piece", [
        Q("Creational & Structural", "<p>Creational patterns: Singleton (single instance — global config), Factory Method (interface for creating objects — subclasses decide class), Abstract Factory (families of related objects), Builder (step-by-step complex object construction — fluent interface), Prototype (clone existing object). Structural patterns: Adapter (match interfaces — wrapper), Bridge (abstraction from implementation — platform independence), Composite (treat individual and composite objects uniformly — tree structures), Decorator (add behavior dynamically — wrapper), Facade (simplified interface to complex subsystem), Flyweight (share fine-grained objects), Proxy (placeholder — lazy loading, access control, logging).</p>"),
        Q("Behavioral & Architectural", "<p>Behavioral patterns: Observer (publish-subscribe — event handling, MVC), Strategy (interchangeable algorithms — sorting, compression), Command (request as object — undo, queue, logging), Template Method (skeleton algorithm — subclasses fill steps), Iterator (sequential access without exposing representation), State (behavior changes with internal state — state machine), Chain of Responsibility (request passes through handlers), Mediator (centralize communication between objects). Architectural patterns: MVC (Model-View-Controller), MVVM (Model-View-ViewModel), Microservices (independent deployable services), Event-Driven (event bus, CQRS, Event Sourcing), Hexagonal (ports and adapters), Layered (presentation, business, data).</p>"),
    ],[F("Refactoring Guru","https://refactoring.guru/design-patterns","Design pattern catalog with examples"),F("SourceMaking","https://sourcemaking.com/design_patterns","Design pattern tutorials")]),
    ("Data Structures", "data-structures.html", "Data structures — arrays, linked lists, trees, hash tables, and advanced structures.", "Programming Concepts", "fas fa-layer-group", [
        Q("Linear & Tree Structures", "<p>Arrays: contiguous memory, O(1) random access, O(n) insert/delete. Dynamic arrays: ArrayList, vector, List — amortized O(1) append. Linked lists: singly (next pointer), doubly (prev + next), circular. Operations: O(n) search, O(1) insert/delete at head. Stacks: LIFO — push/pop O(1), used for undo, expression evaluation, DFS. Queues: FIFO — enqueue/dequeue O(1), used for BFS, scheduling. Deque: double-ended queue. Trees: Binary Tree (each node 0-2 children), Binary Search Tree (left < node < right — O(log n) average), AVL Tree (self-balancing — rotations), Red-Black Tree (approximate balance — used in TreeMap, std::map), B-Tree (multi-way — database indexes), Trie (prefix tree — autocomplete), Segment Tree (range queries), Fenwick Tree (prefix sums).</p>"),
        Q("Hash Tables & Graphs", "<p>Hash tables: key-value pairs with O(1) average lookup. Hash function: maps key to bucket index. Collision resolution: chaining (linked list per bucket), open addressing (linear probing, quadratic probing, double hashing). Load factor: resize when table is X% full. HashMap (Java), unordered_map (C++), dict (Python), Map (JS). Graphs: directed/undirected, weighted/unweighted. Representations: adjacency matrix (Vx2, dense, O(1) edge check), adjacency list (list per vertex, sparse, O(V+E) traversal). DFS: stack/recursion, O(V+E). BFS: queue, O(V+E). Dijkstra: shortest path (non-negative weights) — O(E log V). A*: heuristic-guided pathfinding. Topological sort: DAG ordering — Kahn's algorithm. Union-Find: disjoint sets — Kruskal's MST.</p>"),
    ],[F("Big-O Cheat Sheet","https://www.bigocheatsheet.com/","Data structure complexity reference"),F("Visualgo","https://visualgo.net/","Algorithm visualization tool")]),
    ("Algorithms", "algorithms.html", "Algorithms — sorting, searching, dynamic programming, and complexity analysis.", "Programming Concepts", "fas fa-chart-line", [
        Q("Sorting & Searching", "<p>Sorting: Bubble Sort O(n^2), Selection Sort O(n^2), Insertion Sort O(n^2) — good for small/partially sorted data. Merge Sort O(n log n): divide & conquer, stable, O(n) extra space. Quick Sort O(n log n) average, O(n^2) worst: pivot-based, in-place, unstable — median-of-3, random pivot. Heap Sort O(n log n): in-place, not stable — binary heap. Counting Sort O(n+k): integer range, linear. Radix Sort O(nk): digit by digit. Searching: Linear O(n), Binary O(log n) — sorted array, Binary Search Tree. Interpolation Search O(log log n) average — uniform distribution. Hashing: O(1) average. KMP: substring search O(n+m). Boyer-Moore: substring search with skip table.</p>"),
        Q("Dynamic Programming & Greedy", "<p>DP: optimal substructure + overlapping subproblems. Memoization: top-down with cache. Tabulation: bottom-up with table. Classic problems: Fibonacci, Knapsack (0/1 and fractional), Longest Common Subsequence, Longest Increasing Subsequence, Edit Distance (Levenshtein), Matrix Chain Multiplication, Coin Change, Rod Cutting. DP patterns: 1D DP (house robber), 2D DP (grid paths), interval DP (burst balloons), tree DP (binary tree cameras), state DP (bitmask). Greedy: locally optimal choices — Fractional Knapsack, Huffman Coding, Prim's/Dijkstra's, Activity Selection, Coin Change (canonical currencies). Bit manipulation: XOR tricks, bitmask DP, Brian Kernighan's popcount. Two pointers: sliding window, partition. Backtracking: N-Queens, Sudoku, generate permutations.</p>"),
    ],[F("GeeksforGeeks Algorithms","https://www.geeksforgeeks.org/fundamentals-of-algorithms/","Algorithm tutorials and problems"),F("LeetCode","https://leetcode.com/","Algorithm practice platform")]),
    ("API Design (REST & GraphQL)", "api-design.html", "API design — RESTful principles, GraphQL, versioning, documentation, and rate limiting.", "Programming Concepts", "fas fa-plug", [
        Q("RESTful Design", "<p>REST: Representational State Transfer. Resources: nouns (/users, /articles/{id}), actions via HTTP methods. CRUD: POST (create), GET (read), PUT (replace), PATCH (partial update), DELETE. Status codes: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 409 Conflict, 422 Unprocessable Entity, 500 Internal Server Error. Query params: filtering (?status=active), sorting (?sort=-created_at), pagination (?page=1&per_page=20 — cursor-based preferred for large sets). Fields: sparse fieldsets (?fields=id,name,email). HATEOAS: links in responses for discoverability. OpenAPI/Swagger: specification format — OpenAPI Generator, Swagger UI, ReDoc. API versioning: URL path (/v1/users), header (Accept: application/vnd.api+json;version=1), query param.</p>"),
        Q("GraphQL & Best Practices", "<p>GraphQL: query language by Meta — single endpoint (/graphql). Schema: type Query { users: [User!]! } type User { id: ID! name: String posts: [Post!]! }. Queries: { users { id name posts { title } } }. Mutations: mutation { createUser(input: {name: \"Alice\"}) { id } }. Subscriptions: WebSocket-based real-time. Resolvers: functions per field — Dataloader (batching + caching). N+1 problem: solved by DataLoader, JOINs. Fragments: reusable field selections. Apollo: client + server — cache normalization. Rate limiting: token bucket (Leaky Bucket), sliding window — headers X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset. Backend best practices: idempotency keys, proper error responses (RFC 7807 Problem Details), request validation (JSON Schema).</p>"),
    ],[F("OpenAPI 3.0","https://spec.openapis.org/oas/v3.0.3/","OpenAPI specification"),F("GraphQL Docs","https://graphql.org/learn/","GraphQL learning resources")]),
    ("Version Control (Git Deep Dive)", "git-deep-dive.html", "Git internals — branching, rebasing, hooks, and advanced workflows.", "Programming Concepts", "fab fa-git-alt", [
        Q("Git Internals & Branching", "<p>Git: content-addressable filesystem. Objects: blob (file content), tree (directory — blobs + trees), commit (snapshot + parent + tree + author/message), tag (annotated tag). References: branches (movable refs pointing to commits), HEAD (current branch), tags (immutable refs). Packfiles: delta compression, gc (garbage collection). .git/objects: first 2 chars = directory, rest = filename. Branches: lightweight (just a ref). Merge: fast-forward (no branch divergence), 3-way merge (merge commit). Rebase: replay commits on top of another branch — linear history, rewrite commits (never rebase public branches). Cherry-pick: apply specific commit. Reflog: local history of HEAD movements — emergency recovery. Reset: --soft (move HEAD), --mixed (unstage), --hard (discard changes). Stash: temporarily save working directory.</p>"),
        Q("Advanced Workflows & Hooks", "<p>Git hooks: .git/hooks/ — pre-commit (lint, format), commit-msg (conventional commit check), pre-push (run tests), post-receive (deploy). Hooks are local — share via .githooks/ + git config core.hooksPath. Signed commits: git commit -S (GPG key). Submodules: external repo in subdirectory — git submodule update --init --recursive. worktrees: multiple branches checked out simultaneously. bisect: binary search for bug introduction — git bisect start; git bisect bad; git bisect good; automated with git bisect run. Filter-branch / filter-repo: rewrite history. Partial clone: git clone --filter=blob:none (only fetch on demand). Sparse checkout: check out only specific directories. Convention: Conventional Commits (feat:, fix:, chore:, docs:, BREAKING CHANGE:). Git flow: develop + feature branches + release/hotfix. Trunk-based: short-lived branches, main deployed often.</p>"),
    ],[F("Git Pro Book","https://git-scm.com/book/en/v2","Comprehensive Git reference"),F("Atlassian Git Tutorials","https://www.atlassian.com/git/tutorials","Git workflow guides")]),
    ("Software Testing", "software-testing.html", "Testing — unit, integration, e2e, TDD, mocking, and test automation.", "Programming Concepts", "fas fa-vial", [
        Q("Testing Pyramid", "<p>Testing pyramid: unit (many, fast, isolated), integration (fewer, slower, external services), e2e (few, slow, full system). Unit tests: test single function/class in isolation — mocking external deps. Frameworks: Jest (JS), Pytest (Python), JUnit (Java), RSpec (Ruby), Go testing. Assertions: assertEqual, assertTrue, assertRaises, assertThat (Hamcrest matchers). AAA pattern: Arrange (set up), Act (invoke), Assert (verify). Fixtures: setUp/tearDown (reusable test data). Parameterized tests: run same test with different inputs. Mocking: unittest.mock (Python), Mockito (Java), jest.fn() (JS). Test doubles: dummy (placeholder), fake (functional stub), stub (canned answers), spy (record calls), mock (verify interactions).</p>"),
        Q("TDD & Automation", "<p>TDD: Red (write failing test) > Green (make pass) > Refactor (improve code). Benefits: test coverage, regression safety, better design. BDD: Given-When-Then (Cucumber, SpecFlow, Behat). Integration tests: test components together — database (Testcontainers), HTTP (supertest), message queues. E2E: Cypress, Playwright, Selenium, Puppeteer — browser automation. Visual regression: Percy, Chromatic, Applitools. Snapshot testing: Jest snapshots. Property-based testing: Hypothesis (Python), QuickCheck (Haskell), fast-check (JS). Code coverage: Istanbul (JS), coverage.py (Python), JaCoCo (Java). CI integration: test in CI pipeline — fail on coverage drop. Fuzz testing: random inputs to find crashes. Load testing: k6, Locust, Artillery, wrk. Mutation testing: Stryker — test quality metric.</p>"),
    ],[F("Pytest Docs","https://docs.pytest.org/","Python testing framework"),F("OWASP Testing Guide","https://owasp.org/www-project-web-security-testing-guide/","Web application testing")]),
    ("CI/CD Concepts", "cicd-concepts.html", "Continuous Integration and Delivery — pipelines, artifact management, and deployment strategies.", "Programming Concepts", "fas fa-repeat", [
        Q("CI Fundamentals", "<p>CI: frequently merge code to main branch, automatically build and test. Triggers: push, pull request, merge, schedule, manual. Pipeline stages: checkout > lint > build > unit test > integration test > security scan > package. Fast feedback: < 10 minutes ideally — parallel jobs, caching, test splitting. Branch protection: required status checks, code review, linear history. CI platforms: GitHub Actions, GitLab CI, Jenkins, CircleCI, Travis CI, Buildkite, Drone CI. Self-hosted vs cloud: cloud (no maintenance), self-hosted (more control, faster with local caching, GPU access). Runner scaling: auto-scaling groups, Kubernetes-based runners (actions-runner-controller).</p>"),
        Q("CD & Deployment Strategies", "<p>CD: automatically deploy after CI passes. Artifact repositories: Docker Registry, Nexus, Artifactory, PyPI, npm registry, S3/GCS. Deployment strategies: Rolling (gradually replace instances), Blue/Green (switch between environments), Canary (percentage-based rollout), Feature flags (toggle in production, no deploy needed). Container orchestration: Kubernetes Deployments (rolling update, maxSurge, maxUnavailable). Immutable infrastructure: never modify running server — rebuild from image. GitOps: ArgoCD, Flux — Git as source of truth. Smoke tests: basic health checks post-deployment. Rollback: versioned deployments, database rollback plan. Progressive delivery: Flagger, Argo Rollouts — automated canary analysis.</p>"),
    ],[F("GitHub Actions Docs","https://docs.github.com/en/actions","CI/CD with GitHub"),F("Patterns for CI/CD","https://martinfowler.com/articles/continuousIntegration.html","Martin Fowler on CI")]),
    ("Database Design", "database-design.html", "Database design — normalization, indexes, ACID, NoSQL, and query optimization.", "Programming Concepts", "fas fa-database", [
        Q("Relational & Normalization", "<p>Relational model: tables, rows (tuples), columns (attributes). Keys: primary key (unique row ID), foreign key (reference to other table), composite key (multiple columns). Normalization: 1NF (atomic columns, no repeating groups), 2NF (1NF + no partial dependencies), 3NF (2NF + no transitive dependencies), BCNF (every determinant is a candidate key). Denormalization: intentionally add redundancy for read performance. Views: virtual tables — simplify complex queries, security. Stored procedures: server-side logic — reduce network round trips. Triggers: automatic actions on INSERT/UPDATE/DELETE. Transactions: BEGIN, COMMIT, ROLLBACK — all or nothing. ACID: Atomicity (all or nothing), Consistency (valid state), Isolation (concurrent transactions don't interfere), Durability (committed data persists).</p>"),
        Q("Indexes & NoSQL", "<p>Indexes: B-tree (balanced — sorted, range queries), Hash (equality lookups), Bitmap (low cardinality), GiST (full-text search, geometric), GIN (inverted index — arrays, JSON). Composite index: order matters — (city, last_name) covers queries on city and (city, last_name). EXPLAIN: query plan analysis — sequential scan vs index scan. Query optimization: avoid SELECT *, use covering indexes, avoid functions on indexed columns, limit pagination. NoSQL types: Document (MongoDB — JSON documents, flexible schema), Key-Value (Redis — in-memory, TTL), Wide-column (Cassandra — high write throughput, distributed), Graph (Neo4j — relationships), Time-series (InfluxDB, TimescaleDB). CAP theorem: Consistency, Availability, Partition tolerance — pick 2. Eventual consistency: all replicas eventually converge. Sharding: horizontal partitioning across servers. Replication: master-slave (read replicas), multi-master.</p>"),
    ],[F("Use the Index, Luke!","https://use-the-index-luke.com/","SQL indexing guide"),F("MongoDB Docs","https://www.mongodb.com/docs/","MongoDB documentation")]),
    ("System Design", "system-design.html", "System design — scalability, caching, load balancing, and distributed systems.", "Programming Concepts", "fas fa-cogs", [
        Q("Scalability & Caching", "<p>Scalability: Vertical (bigger machine — limited, expensive), Horizontal (more machines — elastic, fault-tolerant). Stateless vs stateful: stateless scales horizontally easily. Load balancing: as discussed — distribute traffic, health checks. Caching: CDN (static assets — Cloudflare, CloudFront, Akamai), in-memory cache (Redis, Memcached — application data), HTTP caching (browser/proxy). Cache strategies: Cache Aside (app checks cache first), Read-Through (cache loads from DB), Write-Through (write to cache + DB), Write-Behind (async write to DB). Eviction policies: LRU (least recently used), LFU (least frequently used), FIFO, TTL-based. Content Delivery: CDN edge locations, static asset caching, dynamic content acceleration. Cache invalidation: hard (delete cache), soft (mark stale).</p>"),
        Q("Distributed Systems", "<p>Distributed systems: multiple nodes working together. CAP theorem: Consistency, Availability, Partition tolerance — pick 2. Consistency models: Strong (linearizability), Eventual (replicas converge), Causal (related operations ordered). Consensus: Paxos (classic, complex), Raft (understandable — leader election, log replication). Zab (ZooKeeper Atomic Broadcast). Message queues: Kafka (partitioned, persistent, replay), RabbitMQ (AMQP, flexible routing), AWS SQS/SNS. Patterns: CQRS (separate read/write models), Event Sourcing (store events, derive state), Saga (distributed transaction — choreography vs orchestration). Database per service: each service owns its data. API Gateway: single entry point — auth, rate limiting, routing. Service mesh: Istio, Linkerd. Observability: logs, metrics, traces. Health checks: /health, /ready, /live.</p>"),
    ],[F("System Design Primer","https://github.com/donnemartin/system-design-primer","System design fundamentals"),F("Awesome Scalability","https://github.com/binhnguyennus/awesome-scalability","Scalability patterns")]),
    ("Concurrency & Parallelism", "concurrency-parallelism.html", "Concurrency — threads, async/await, locks, channels, and parallel processing.", "Programming Concepts", "fas fa-tasks", [
        Q("Threads & Locks", "<p>Concurrency: multiple tasks making progress (interleaved). Parallelism: multiple tasks running simultaneously (multi-core). Processes: separate memory space, IPC (pipes, sockets, shared memory). Threads: shared memory within process — lightweight, race conditions. Locks: Mutex (mutual exclusion — one thread at a time), Semaphore (N permits), ReadWriteLock (multiple readers, one writer). Deadlock: circular wait — lock ordering, tryLock with timeout. Livelock: threads keep yielding without progress. Starvation: thread never gets resources. Condition variables: wait/notify pattern. Atomics: lock-free CAS (compare-and-swap) — AtomicInteger, AtomicReference. Memory model: happens-before relationship, volatile (visibility guarantees). Amdahl's Law: speedup limited by serial portion. Thread pools: ExecutorService (Java), ThreadPoolExecutor (Python), std::thread pool (C++).</p>"),
        Q("Async/Await & Actor Model", "<p>Async/await: cooperative concurrency — single-threaded event loop, non-blocking I/O. Event loop: select/epoll/kqueue (I/O multiplexing). Promises/Futures: pending, fulfilled, rejected. async: marks function as asynchronous, returns a Future. await: suspends execution until Future completes. JavaScript: async/await on single thread, Web Workers for parallelism. Python: asyncio (event loop, coroutines, tasks). Rust: async/await, Tokio runtime. C#: async/await, Task Parallel Library. Kotlin: coroutines — launch, async, structured concurrency. Go: goroutines (lightweight, multiplexed onto OS threads), channels (CSP — Communicating Sequential Processes), select. Actor model: Erlang/Elixir (supervision trees, let it crash), Akka (JVM). Each actor: private state, message passing, no shared state. Data parallelism: SIMD, GPU (CUDA, OpenCL). MapReduce: distributed processing (Hadoop, Spark).</p>"),
    ],[F("Concurrency in Go","https://go.dev/blog/pipelines","Go concurrency patterns"),F("Kotlin Coroutines","https://kotlinlang.org/docs/coroutines-overview.html","Kotlin structured concurrency")]),
    ("Clean Code & SOLID", "clean-code-solid.html", "Writing clean, maintainable code — naming, refactoring, and software craftsmanship.", "Programming Concepts", "fas fa-broom", [
        Q("Naming & Functions", "<p>Clean Code: Robert C. Martin. Naming: intention-revealing names (isEligible vs flag), pronounceable, searchable, avoid disinformation (accountsList vs accounts — if not a List). Functions: small (ideally < 20 lines), single responsibility, descriptive names, minimal arguments (0-2 ideal, avoid 3+). DRY: Don't Repeat Yourself — extract repeated code. Comments: explain WHY, not WHAT (code should be self-documenting). Avoid commented-out code, misleading comments. Error handling: exceptions vs return codes, provide context with exception messages. Null handling: Optional/Option/Maybe, Null Object pattern, fail fast. Formatting: consistent indentation, vertical spacing (blank lines between concepts), horizontal alignment. Code smells: long method, large class, feature envy, inappropriate intimacy, switch statements.</p>"),
        Q("Refactoring & Craftsmanship", "<p>Refactoring: Martin Fowler. Techniques: Extract Method, Inline Method, Extract Class, Move Method, Rename, Replace Temp with Query, Introduce Parameter Object. Safe refactoring: tests first, small steps. YAGNI: You Aren't Gonna Need It — don't add speculative functionality. KISS: Keep It Simple, Stupid. Boy Scout Rule: leave code cleaner than you found it. Code reviews: constructive feedback, focus on design/readability, automated checks (linters) handle style. Pair programming: driver + navigator, real-time code review. Technical debt: conscious (deliberate shortcut) vs unconscious (lack of knowledge) — track in backlog. Legacy code: characterize with tests before refactoring (Working Effectively with Legacy Code by Feathers). Continuous improvement: retrospectives, learning culture.</p>"),
    ],[F("Clean Code Book","https://www.oreilly.com/library/view/clean-code/9780136083238/","Robert C. Martin's Clean Code"),F("Refactoring Guru Smells","https://refactoring.guru/refactoring/smells","Code smell catalog")]),

    # === HARDWARE (8) ===
    ("PC Building Guide", "pc-building-guide.html", "Build your own PC — component selection, assembly, and benchmarking.", "Hardware", "fas fa-desktop", [
        Q("Component Selection", "<p>PC components: CPU (Intel Core i5/i7/i9 — LGA1700/1851, AMD Ryzen 5/7/9 — AM5), GPU (NVIDIA GeForce RTX 40/50 series, AMD Radeon RX 7000/9000), motherboard (chipset — B760, Z790, B650, X670E — socket, PCIe lanes, DDR5 support), RAM (DDR5 — 6000-8000 MT/s, 32GB recommended), storage (NVMe M.2 SSD — PCIe 4.0/5.0, 1-2TB), PSU (power supply — 80+ Gold/Platinum, 750-1000W, modular), case (ATX, mATX, ITX — airflow). Cooling: air (tower cooler, dual tower), AIO liquid (240/360mm). Monitor: resolution (1440p, 4K), refresh rate (144Hz, 240Hz), panel type (IPS, OLED, VA). Peripherals: mechanical keyboard (Cherry MX, optical switches), mouse (DPI, wireless). Budget vs performance: prioritize GPU for gaming, CPU for productivity. Bottleneck: balance components.</p>"),
        Q("Assembly & Benchmarking", "<p>Assembly: anti-static wrist strap, clear workspace. Steps: 1) CPU into socket (triangle alignment, no force). 2) RAM into slots A2+B2 (dual channel). 3) M.2 SSD into motherboard slot. 4) CPU cooler (thermal paste — pea size, mounting pressure). 5) PSU in case, route cables. 6) Motherboard in case (standoffs). 7) GPU into PCIe x16 slot. 8) Connect all cables (24-pin ATX, 8-pin CPU, PCIe power, SATA, front panel). 9) Cable management. 10) First boot: enter BIOS, check CPU temp, RAM speed (enable XMP/EXPO), boot drive order. OS install: Windows 11 (requires TPM 2.0, Secure Boot) or Linux. Drivers: GPU driver (NVIDIA/AMD), chipset drivers, network drivers. Benchmarking: Cinebench (CPU), 3DMark/Unigine (GPU), CrystalDiskMark (SSD), MemTest86 (RAM stability). Stress test: Prime95 + FurMark (temperature). Monitoring: HWMonitor, HWiNFO, MSI Afterburner.</p>"),
    ],[F("PCPartPicker","https://pcpartpicker.com/","Component compatibility checker"),F("Tom's Hardware","https://www.tomshardware.com/","Hardware reviews and guides")]),
    ("CPU Architecture", "cpu-architecture.html", "CPU architecture — cores, cache, pipelines, instruction sets, and microarchitecture.", "Hardware", "fas fa-microchip", [
        Q("Core Architecture", "<p>CPU core: arithmetic logic unit (ALU), floating-point unit (FPU), control unit, registers. Pipeline: Fetch > Decode > Execute > Memory Access > Write Back. Superscalar: multiple instructions per cycle. Out-of-order execution: execute independent instructions while waiting for dependencies. Speculative execution: predict branches (branch predictor — TAGE, perceptron). Caches: L1 (per-core, 32KB I + 32KB D, ~1ns), L2 (per-core, 512KB-2MB, ~4ns), L3 (shared, 16-64MB, ~12ns). Cache lines: 64 bytes, prefetching. Cache coherence: MESI protocol (Modified, Exclusive, Shared, Invalid). Hyper-Threading/SMT: 2 logical threads per core. AVX-512: vector processing — 512-bit SIMD. Memory controller: integrated (DDR4/DDR5) — channels, ranks. PCIe controller: lanes directly from CPU (Gen 4/5, x16 for GPU, x4 for SSD). Power management: C-states (idle), P-states (performance), thermal throttling.</p>"),
        Q("Microarchitecture & ISA", "<p>ISA (Instruction Set Architecture): x86 (Intel/AMD — CISC, variable-length), ARM (RISC, fixed-length), RISC-V (open-source). Microarchitecture: specific implementation of ISA — Intel Core (Golden Cove, Raptor Cove, Lion Cove), AMD Zen (Zen 1-5, CCD/IO die), Apple Silicon (M1-M4 — Firestorm/Icestorm performance/efficiency cores). x86-64: legacy (16-bit real mode, 32-bit protected mode, 64-bit long mode). Virtualization: VT-x/AMD-V (hardware virtualization), IOMMU for device passthrough. TEE: Trusted Execution Technology (Intel SGX/TDX, AMD SEV, ARM TrustZone). Fabric: interconnect between cores — Intel Ring Bus (desktop), Mesh (Xeon), AMD Infinity Fabric (CCX/CCD chiplets). Chiplet design: multiple dies in one package (AMD, Intel Meteor Lake). Advanced: 3D V-Cache (stacked L3), HBM (high-bandwidth memory on-package).</p>"),
    ],[F("Intel Architecture","https://www.intel.com/content/www/us/en/architecture-and-technology/","Intel processor architecture"),F("AMD Architecture","https://www.amd.com/en/technologies/zen-core","AMD Zen microarchitecture")]),
    ("GPU Architecture", "gpu-architecture.html", "GPU architecture — shaders, CUDA cores, ray tracing, VRAM, and tensor cores.", "Hardware", "fas fa-video", [
        Q("GPU Pipeline", "<p>GPU: massively parallel processor optimized for graphics and compute. Graphics pipeline: vertex shader (transform 3D vertices), geometry shader (tessellation, geometry generation), rasterization (convert to fragments/pixels), fragment/pixel shader (color, lighting, textures), output merger (depth/stencil, blending). Shaders: programmable stages — HLSL (DirectX), GLSL (OpenGL), SPIR-V (Vulkan). CUDA cores (NVIDIA) / Stream Processors (AMD): ALU units for parallel computation. Ray tracing: RT cores (NVIDIA) / Ray Accelerators (AMD) — BVH traversal, ray-triangle intersection. Tensor cores: mixed-precision matrix multiply — DLSS (Deep Learning Super Sampling), AI inference. VRAM: GDDR6/GDDR6X/GDDR7 (NVIDIA), HBM2e/HBM3 (enterprise — high bandwidth, stacked). Memory bandwidth: 512-1024 GB/s consumer, 1-3 TB/s HBM. TDP: 150W (mainstream) - 450W (flagship). PCIe power: 8-pin (150W), 12VHPWR (600W).</p>"),
        Q("Compute & Modern Features", "<p>General-purpose GPU (GPGPU): compute shaders — physics simulation, particle systems, image processing. CUDA: NVIDIA's parallel computing platform — threads, blocks, grids, shared memory, warp (32 threads). ROCm: AMD's open-source GPU compute platform. Vulkan: low-overhead graphics API — explicit control, command buffers, pipeline state objects. DirectX 12 Ultimate: DirectX Raytracing (DXR 1.1), Variable Rate Shading, Mesh Shaders, Sampler Feedback. OpenGL: legacy but still used (4.6 core profile). NVIDIA DLSS 3/4: AI upscaling — DLAA (anti-aliasing), Ray Reconstruction, Frame Generation. AMD FSR: open-source upscaling — quality/balanced/performance modes. Intel XeSS: AI upscaling for Intel Arc GPUs. Multi-GPU: NVIDIA SLI/NVLink (mostly deprecated), AMD CrossFire. GPU virtualization: NVIDIA vGPU, SR-IOV. External GPU: Thunderbolt/USB4 eGPU enclosure.</p>"),
    ],[F("NVIDIA CUDA Docs","https://docs.nvidia.com/cuda/","CUDA programming guide"),F("Vulkan Docs","https://docs.vulkan.org/","Vulkan API specification")]),
    ("Storage (SSD, NVMe, HDD)", "storage-ssd-nvme.html", "Storage technology — SSD, NVMe, HDD, RAID, and data reliability.", "Hardware", "fas fa-hard-drive", [
        Q("SSD & NVMe", "<p>SSD: NAND flash storage — no moving parts, fast random access. NAND types: SLC (1 bit/cell — fastest, most durable), MLC (2 bits), TLC (3 bits — consumer standard), QLC (4 bits — cheaper, slower writes, lower endurance). 3D NAND: vertical stacking — 128-238+ layers. Form factors: 2.5-inch (SATA), M.2 2280 (NVMe or SATA), U.2 (enterprise), EDSFF (enterprise). SATA SSD: up to 550 MB/s (SATA 3 limit). NVMe: PCIe interface — up to 14 GB/s (PCIe 5.0 x4), 1M+ IOPS. Protocols: AHCI (legacy, SATA), NVMe (native PCIe — queue depth 65k vs AHCI 32). NVMe features: multiple queues (per-core), interrupt coalescing, streamlined command set. DRAM vs DRAM-less: DRAM has host memory buffer (HMB) uses system RAM for mapping table. Over-provisioning: spare NAND for wear leveling. TRIM: inform SSD of unused blocks. Endurance: TBW (terabytes written) rating.</p>"),
        Q("HDD & Reliability", "<p>HDD: spinning magnetic platters, read/write head on arm. RPM: 5400 (low power), 7200 (desktop), 10k/15k (enterprise). Areal density: bits per square inch — increases yearly (CMR vs SMR). CMR (Conventional Magnetic Recording): standard tracks. SMR (Shingled Magnetic Recording): overlapping tracks — more capacity, slower random writes. Form factors: 3.5-inch (desktop), 2.5-inch (laptop). Interfaces: SATA (consumer), SAS (enterprise — dual-port, better error handling). Reliability: MTBF (mean time between failures — 1-2M hours), AFR (annualized failure rate ~1-3%). SMART: self-monitoring attributes — reallocated sectors, pending sectors, spin retry count. RAID levels: 0 (stripe — performance, no redundancy), 1 (mirror), 5 (striped parity — 1 drive failure), 6 (dual parity — 2 drives), 10 (stripe + mirror). RAID vs standalone: RAID provides redundancy/performance, not backup. Backup: 3-2-1 rule (3 copies, 2 media types, 1 off-site).</p>"),
    ],[F("AnandTech Storage","https://www.anandtech.com/tag/ssd","SSD reviews and benchmarks"),F("Backblaze HDD Stats","https://www.backblaze.com/cloud-storage/resources/hard-drive-test-data","HDD reliability statistics")]),
    ("RAM & Memory", "ram-memory.html", "Memory — DDR5, DIMM, latency, dual-channel, ECC, and memory overclocking.", "Hardware", "fas fa-memory", [
        Q("DDR5 & Memory Technologies", "<p>DDR (Double Data Rate): data on both clock edges. Generations: DDR4 (2133-5333 MT/s, 1.2V), DDR5 (4800-8400+ MT/s, 1.1V — on-die ECC, two 32-bit channels per module, PMIC on board). DIMM types: DIMM (desktop), SO-DIMM (laptop), RDIMM/LRDIMM (server — registered/buffered). Latency: CAS latency (CL — cycles between column address and data). CL30-36 typical for DDR5. True latency = (CL / data rate) * 2000 — DDR5-6000 CL30 = 10ns. Dual-channel: two DIMMs in alternating channels (A2/B2) — 2x memory bandwidth. Quad-channel: high-end desktop (AMD Threadripper, Intel Xeon W). Memory ranks: single-rank (1 DRAM chip set), dual-rank (2 sets — more parallelism). XMP (Intel Extreme Memory Profile) / EXPO (AMD Extended Profiles for Overclocking): pre-configured OC profiles in SPD. Memory overclocking: increase frequency, tighten timings — stability test with MemTest86, TM5, y-cruncher. 1usmus DRAM Calculator.</p>"),
        Q("ECC & Virtual Memory", "<p>ECC (Error-Correcting Code): detect and correct single-bit errors, detect double-bit. On-die ECC (DDR5): corrects internal DRAM errors. Full ECC (server): additional data bus width (72-bit vs 64-bit) — requires compatible CPU and motherboard. Registered/Buffered: RDIMM has register between DRAM and memory controller — reduces electrical load, supports more DIMMs per channel. ECC vs non-ECC: ECC critical for servers, workstations (data integrity). Virtual memory: OS uses disk as extension of RAM — page file (Windows), swap (Linux). Pages: 4KB default, 2MB huge pages (Linux), 1GB pages. TLB (Translation Lookaside Buffer): cache for virtual-to-physical mappings. NUMA (Non-Uniform Memory Access): memory closer to some CPU sockets — latency differs. Memory tiering: CXL-attached memory as slower tier. Persistent memory: Intel Optane (discontinued), CXL-attached NVDIMM.</p>"),
    ],[F("DDR5 Standard","https://www.jedec.org/standards-documents/docs/jesd79-5","JEDEC DDR5 specification"),F("MemTest86","https://www.memtest86.com/","Memory testing tool")]),
    ("Motherboard & Chipset", "motherboard-chipset.html", "Motherboard — chipsets, PCIe lanes, VRM, form factors, and BIOS/UEFI.", "Hardware", "fas fa-microchip", [
        Q("Chipsets & PCIe", "<p>Chipset: connects CPU to peripherals (SATA, USB, LAN, audio, secondary M.2). Intel chipsets: B760 (mid-range, PCIe 4.0), Z790 (high-end, overclocking, PCIe 5.0 GPU + 4.0 storage), Z890 (Arrow Lake — new LGA1851, Thunderbolt 4). AMD chipsets: B650 (mid-range, PCIe 5.0 GPU + storage), X670E (high-end, dual chipset, PCIe 5.0), X870E (new — USB4, PCIe 5.0). PCIe lanes: direct from CPU (x16 GPU, x4 M.2) and from chipset (additional M.2, USB, SATA, Ethernet). Gen 4: 16 GT/s per lane (~2 GB/s). Gen 5: 32 GT/s (~4 GB/s). Gen 6: 64 GT/s (~8 GB/s). PCIe bifurcation: split x16 into x8/x8 (dual GPU) or x8/x4/x4 (GPU + 2 SSDs). M.2 slots: CPU-attached (direct, faster) vs chipset-attached (shared bandwidth). SATA: 6 Gbps per port. USB: controller in chipset — USB 3.2 Gen2x2 (20 Gbps), USB4/TB4 (40 Gbps).</p>"),
        Q("VRM & BIOS/UEFI", "<p>VRM (Voltage Regulator Module): converts 12V to CPU/IMC voltage — phases (doublers), MOSFETs, chokes, capacitors. Phase count: more phases = cleaner power, less ripple. Quality: low RDS(on) MOSFETs, high-quality capacitors (Japanese). Power stages (DrMOS): integrated MOSFET + driver — more efficient. BIOS/UEFI: firmware interface — UEFI (modern, GPT, Secure Boot, GUI) vs legacy BIOS (MBR). Settings: XMP/EXPO (RAM overclock), PBO (AMD Precision Boost Overdrive — auto OC), undervolting (offset voltage), fan curves (PWM vs DC), boot order (UEFI vs CSM/Legacy), Resizable BAR/SAM (GPU memory access). Update: flash via USB (BIOS Flashback — no CPU needed). CMOS reset: remove battery or jumper. POST codes: debug LED, beep codes, Q-Code display. Form factors: ATX (305x244mm), mATX (244x244mm), ITX (170x170mm), E-ATX (305x330mm).</p>"),
    ],[F("Intel Chipset Guide","https://www.intel.com/content/www/us/en/chipsets/","Intel chipset documentation"),F("LGA1851 Overview","https://www.tomshardware.com/tag/lga-1851","New Intel socket coverage")]),
    ("Cooling & Thermal", "cooling-thermal.html", "PC cooling — air, AIO, custom loop, thermal paste, and fan optimization.", "Hardware", "fas fa-fan", [
        Q("Air vs Liquid Cooling", "<p>Air cooling: heatsink + fan — heat pipes (copper, heat-pipe direct touch vs nickel-plated), fin density, tower height. Types: low-profile (ITX), single tower (mid-range CPUs), dual tower (high-end — Noctua NH-D15, Thermalright Peerless Assassin). Fans: size (120mm, 140mm), bearing (sleeve, hydraulic, FDB — fluid dynamic bearing, rifle), static pressure (radiators/radiators + fine fins), airflow (case ventilation), PWM (4-pin — variable speed) vs DC (3-pin). AIO (All-in-One): pump, radiator, fans, pre-filled. Sizes: 120mm, 240mm, 280mm, 360mm, 420mm. Performance: 280mm ~= 360mm (140mm fans run quieter). Thickness: 27mm standard, 45mm+ high-performance (push-pull fans). Custom loop: pump/reservoir, CPU block, GPU block, radiator, fittings, tubing (soft/PETG/acrylic), coolant (distilled + biocide or premix). Maintenance: drain, refill yearly. Materials: copper (good) vs aluminum (cheaper) — never mix (galvanic corrosion).</p>"),
        Q("Thermal Management", "<p>Thermal paste: TIM (thermal interface material) — fills microscopic gaps between CPU and cooler. Types: thermal grease (NT-H1, MX-6 — easy), liquid metal (Conductonaut — best conductivity but conductive, risky), thermal pads (for GPUs, VRAM). Application: pea method (center), line method (Intel LGA), spread method (thin layer). Thermal paste lifespan: 2-5 years before drying out. Thermal throttling: CPU/GPU reduce frequency when temperature exceeds threshold (~100°C CPU, ~85°C GPU). Junction temp (Tjmax): hottest spot on die. Ambient temperature: affects cooling performance. Case airflow: front intake, rear/top exhaust — positive pressure (more intake than exhaust — less dust). Fan curves: BIOS or software (FanControl, SpeedFan) — define temperature:rpm mapping. Water cooling temp: target 35-40°C coolant under load. Radiator placement: top (exhaust) or front (intake) — push vs pull vs push-pull. Fan control: PWM splitter, fan hub, Aquacomputer Quadro/Octo. Thermal pads: for VRAM, VRM (replace if too thick/thin). Undervolting: reduce voltage without losing stability — lower temps. Power limits: PL1 (sustained) and PL2 (boost) for Intel CPUs.</p>"),
    ],[F("Noctua Cooling Guide","https://noctua.at/en/faq","Noctua cooling guides"),F("Thermal Grizzly","https://www.thermal-grizzly.com/","High-end thermal paste and pads")]),
    ("Networking Hardware", "networking-hardware.html", "Network hardware — routers, switches, access points, cables, and home networking.", "Hardware", "fas fa-network-wired", [
        Q("Routers & Switches", "<p>Routers: connect different networks, perform NAT, firewall, routing. Home router: all-in-one (router + switch + AP + modem). Advanced: pfSense/OPNsense (DIY router on PC), Ubiquiti UniFi (Dream Machine, EdgeRouter), MikroTik (RouterBOARD, RouterOS — powerful but steep learning curve). Features: VLAN support, QoS (traffic shaping — fq_codel, CAKE), VPN server, ad-blocking (Pi-hole), parental controls. Switches: connect devices within LAN. Managed vs unmanaged: managed = VLANs, STP, LACP, SNMP, port mirroring, PoE. PoE standards: 802.3af (15.4W), 802.3at (30W — PoE+), 802.3bt Type 3 (60W), Type 4 (90W — PoE++). Switch form factors: desktop, rackmount, fanless (silent for home). L2 vs L3 switches: L2 (MAC-based switching), L3 (IP routing — inter-VLAN routing). Stacking: multiple switches as one logical unit. SFP/SFP+: fiber or DAC uplink ports (1G SFP, 10G SFP+, 25G SFP28, 100G QSFP28).</p>"),
        Q("Access Points & Cabling", "<p>Access Points (APs): wireless connectivity — Ubiquiti UniFi (U6-LR, U7-Pro), TP-Link Omada (EAP670), Aruba Instant On, Ruckus. Mesh systems: eero, Google Nest WiFi, TP-Link Deco, Asus ZenWiFi — easy setup, AI roaming. Controller-based: UniFi Controller (software or CloudKey + 'gateway) — manage multiple APs centrally (roaming, band steering, RF optimization). Ethernet: Cat5e (1Gbps, 100m), Cat6 (10Gbps, 55m), Cat6a (10Gbps, 100m), Cat7 (proprietary), Cat8 (25/40Gbps, 30m). Shielded (STP) vs unshielded (UTP): STP reduces interference, needs proper grounding. Keystone jacks, patch panels, punch-down tools. Fiber optic: single-mode (OS2 — long distance, 9/125um core, LC connector) vs multi-mode (OM3/OM4/OM5 — short distance, 50/125um). Media converters: fiber to copper. Cable testing: continuity, wiremap (T568A/B), signal loss (TDR). UPS: battery backup for network equipment — runtime for modem, router, switch, AP. Rack: 19-inch server rack, patch panel, cable management.</p>"),
    ],[F("Ubiquiti UniFi Docs","https://help.ui.com/hc/en-us/categories/","UniFi networking documentation"),F("MikroTik Docs","https://wiki.mikrotik.com/wiki/Main_Page","MikroTik RouterOS manual")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials (p3b)!")
