#!/usr/bin/env python3
"""Generate ~18 tutorials — More DevOps, More Web, More Linux."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === MORE DEVOPS (5) ===
    ("Docker Swarm", "docker-swarm.html", "Orchestrate containers with Docker Swarm -- services, stacks, networking, production.", "DevOps", "fab fa-docker", [
        Q("Swarm Mode & Services", "<p>Docker Swarm: native Docker orchestration. Init: docker swarm init. Workers: docker swarm join. Services: docker service create --name web --publish 80:80 --replicas 3 nginx. Scaling: docker service scale web=5. Update: rolling update --update-parallelism 2 --update-delay 30s. Constraints: node labels, node.role. Secrets: docker secret create, mounted at /run/secrets/. Stacks: docker stack deploy -c docker-compose.yml mystack. Networking: overlay (multi-host), ingress routing mesh. Production: 3-5 managers (odd, no workloads). Resource limits: --limit-cpu, --limit-memory. Health checks: HEALTHCHECK in Dockerfile. Monitoring: Portainer UI, Prometheus, cAdvisor. Draining: docker node update --availability drain. Swarm vs K8s: simpler, native Docker, less powerful.</p>"),
        Q("Compose & Production", "<p>Docker Compose + Swarm: use deploy section in compose. Labels: node.labels for placement. Traefik: reverse proxy with Let's Encrypt and Swarm service discovery. GitLab CI: deploy to swarm via SSH and docker stack deploy. Backup: /var/lib/docker/swarm. Multi-platform: buildx for multi-arch. Swarm limitations: no auto-scaling, weaker service discovery. Portainer: web UI for Swarm management. docker stack ps mystack: check service status. docker service logs web: view service logs. Rolling updates: --update-parallelism, --update-delay, --update-order start-first. Rollback: docker service rollback web. Global services: one per node. Replicated services: N replicas across cluster. Placement preferences: spread, pack across nodes. Docker Compose watch: hot reload in dev.</p>"),
    ],[F("Swarm Docs","https://docs.docker.com/engine/swarm/","Docker Swarm documentation"),F("Portainer","https://docs.portainer.io/","Swarm UI management")]),
    ("HashiCorp Vault", "hashicorp-vault.html", "Secrets management -- Vault, dynamic secrets, encryption-as-a-service, auto-unseal.", "DevOps", "fas fa-vault", [
        Q("Secrets Engines & Auth", "<p>Vault: secrets management. Storage: Raft, Consul, file. Secret engines: KV (key-value), Database (dynamic DB creds), AWS (dynamic IAM), PKI (dynamic TLS certs), Transit (encryption-as-a-service), TOTP. Auth: Token, AppRole, LDAP, Kubernetes, JWT/OIDC, AWS IAM. Dynamic secrets: short-lived, auto-rotate. Policies: path-based capabilities (create, read, update, delete, list). Leases: TTL + renewable, revokable. Audit: log all requests to file/syslog/socket. CLI: vault kv put/get/delete, vault login, vault write/read. API: all via REST /v1/. Unseal: Shamir keys (threshold) or auto-unseal (cloud KMS).</p>"),
        Q("Deployment & K8s", "<p>HA: active + standby nodes. Auto-unseal: AWS KMS, Azure Key Vault, GCP Cloud KMS, Transit. Vault agent: sidecar for apps, template rendering. K8s injector: mutating webhook, inject agent sidecar. CSI provider: Secrets Store CSI driver. Vault Enterprise: namespaces, replication, seal wrap, control groups. Terraform provider: manage Vault via Terraform. Backups: raft snapshot save. Disaster recovery: DR replication. Monitoring: Prometheus metrics, audit logs. Integration: Ansible, Jenkins, GitHub Actions. Security: seal wrap, response wrapping. Reference architecture: integrated storage (Raft), 3-5 nodes.</p>"),
    ],[F("Vault Docs","https://developer.hashicorp.com/vault/docs","Vault documentation"),F("Vault Tutorials","https://developer.hashicorp.com/vault/tutorials","Learn Vault")]),
    ("Grafana Loki", "grafana-loki.html", "Log aggregation -- Loki, LogQL, Promtail, and log-based alerting.", "DevOps", "fas fa-chart-bar", [
        Q("Loki & Promtail", "<p>Loki: horizontally-scalable log aggregation, label-based (like Prometheus). Components: Distributor, Ingester, Querier, Query Frontend, Compactor. Labels: identify log streams. Object storage: S3, GCS, Azure Blob, MinIO. Promtail: log collector -- scrape logs, systemd journal, Docker. Config: scrape_configs with relabeling. Clients: Promtail, Grafana Agent, Fluent Bit, Logstash, Vector. Pipelines: stages (regex, json, logfmt, timestamp, labels). Chunk: compressed log block, ~1.5MB target. Multi-tenancy: X-Scope-OrgID header. Label best practices: low cardinality.</p>"),
        Q("LogQL & Alerting", "<p>LogQL: {job=\"nginx\"} |= \"error\". Parsers: | json, | logfmt, | regexp. Metric queries: rate({job=\"nginx\"} |= \"error\" [5m]). Aggregation: sum by(level) (rate(...)). Alerting: rules in Loki ruler, send to Alertmanager. Recording rules: precompute expensive queries. Retention: S3 lifecycle, retention enforcement. Loki vs Elasticsearch: cheaper (object storage), label-based, simpler queries. Grafana: Explore (ad-hoc LogQL), panels (log panel, derived fields). Bloom filters: query acceleration (skip irrelevant chunks).</p>"),
    ],[F("Loki Docs","https://grafana.com/docs/loki/latest/","Grafana Loki documentation"),F("LogQL","https://grafana.com/docs/loki/latest/logql/","LogQL language reference")]),
    ("Terraform Cloud & Enterprise", "terraform-cloud-enterprise.html", "Terraform Cloud -- remote state, workspaces, Sentinel, cost estimation.", "DevOps", "fas fa-cloud", [
        Q("Workspaces & Runs", "<p>Terraform Cloud: managed Terraform. Workspaces: separate state per workspace. VCS integration: auto-trigger on PR/merge. Runs: plan, apply, discard. Remote state: encrypted, versioned, locked. Variables: terraform vars, env vars, sensitive (masked). Variable sets: reusable groups. Team management: owners, manage, plan/apply permissions. Private registry: share modules. Cost estimation: Infracost integration. Run tasks: Checkov, Aqua, Snyk. Notifications: Slack, email. API-driven: tfe provider, API tokens. CLI: terraform login, remote execution.</p>"),
        Q("Sentinel & Enterprise", "<p>Sentinel: policy-as-code. Policies: allowed regions, naming, cost, tagging. Enforcement: advisory, soft mandatory, hard mandatory. Mock: sentinel test. TFE: self-hosted -- air-gapped, private network. Features: audit logging, SAML/SSO, private network runners, agents. TFC agents: connect to private network. Agent pools: assign to workspaces. Drift detection: scheduled plans. Pricing: Free (5 users), Team, Business, Enterprise.</p>"),
    ],[F("Terraform Cloud Docs","https://developer.hashicorp.com/terraform/cloud-docs","Terraform Cloud docs"),F("Sentinel Docs","https://developer.hashicorp.com/sentinel/docs","Sentinel policy docs")]),
    ("SRE Runbooks & On-Call", "sre-runbooks.html", "Site Reliability -- runbooks, incident response, on-call, and postmortems.", "DevOps", "fas fa-life-ring", [
        Q("Runbooks & Response", "<p>Runbooks: documented procedures. Structure: symptoms, severity, checklist, escalation path. Tools: Grafana OnCall, PagerDuty, Opsgenie. On-call: primary, secondary, rotation. Escalation: auto-escalate on no response. Severity: SEV1 (critical, all hands), SEV2 (degraded), SEV3 (minor), SEV4 (cosmetic). Incident commander: coordinates. Scribe: documents timeline. Blameless culture: systems thinking. SLO tracking: burn rate alerts. Error budget: freeze on exhaustion. Production readiness: monitoring, alerting, runbook, DR plan.</p>"),
        Q("Postmortems", "<p>Postmortem: timeline, root cause, action items. Blameless: assume good intent. SLA/SLO/SLI: 99.9% = 8.7h/yr. DR: RTO, RPO, periodic drills. Toil: manual, automatable -- target <50%. Chaos engineering: GameDays test runbooks. On-call wellness: compensation, handover, follow-the-sun. Observability: logs + metrics + traces. Capacity planning: trend analysis, load testing. Fault tolerance: redundancy, circuit breakers. Postmortem tools: Incident.io, FireHydrant.</p>"),
    ],[F("Google SRE Book","https://sre.google/books/","Free SRE books"),F("PagerDuty Docs","https://www.pagerduty.com/docs/","On-call management")]),

    # === MORE WEB (8) ===
    ("WebSockets & SSE", "websockets-sse.html", "Real-time web -- WebSockets, Server-Sent Events, WebRTC data channels.", "Web", "fas fa-plug", [
        Q("WebSocket", "<p>WebSocket: full-duplex persistent connection. Handshake: HTTP upgrade (101 Switching Protocols). Frames: text, binary, ping/pong, close. API: new WebSocket(url), onopen, onmessage, onclose, send(). Libraries: ws (Node), Socket.IO (fallback, rooms, namespaces). Socket.IO: namespaces, rooms, events, acks, Redis adapter. Spring WebSocket: STOMP protocol. Scaling: sticky sessions or Redis pub/sub. Security: wss://, origin check, token auth, rate limiting. Auto-reconnect: exponential backoff.</p>"),
        Q("SSE & WebRTC", "<p>SSE: unidirectional server->client HTTP streaming. EventSource API: onmessage, auto-reconnect. Event format: data:, event:, id:, retry:. SSE vs WebSocket: simpler, unidirectional, auto-reconnect built-in. WebRTC: P2P real-time comm. RTCPeerConnection, RTCDataChannel. Signaling: SDP + ICE via WebSocket. STUN/TURN: NAT traversal. SFU: selective forwarding unit for group calls. Use: video calls, file sharing, live streaming. Libraries: PeerJS, LiveKit, Janus.</p>"),
    ],[F("MDN WebSocket","https://developer.mozilla.org/en-US/docs/Web/API/WebSocket","WebSocket API"),F("WebRTC","https://webrtc.org/","WebRTC project")]),
    ("JAMstack Architecture", "jamstack-architecture.html", "JAMstack -- static sites, headless CMS, serverless functions, edge rendering.", "Web", "fas fa-cubes", [
        Q("Static Generation", "<p>JAMstack: JavaScript, APIs, Markup -- prebuilt static files via CDN. SSGs: Next.js (SSG + ISR), Astro (islands), Hugo (fastest), 11ty, Gatsby. Next.js SSG: getStaticProps, getStaticPaths, ISR (revalidate). Astro: zero-JS default, islands, content collections. Build: git push -> CI -> deploy to CDN. CDN: Vercel, Netlify, Cloudflare Pages. Incremental builds: rebuild only changed pages. Preview deploys: per branch/PR.</p>"),
        Q("Serverless & CMS", "<p>Serverless: Vercel Functions, Netlify Functions, AWS Lambda. Edge: Vercel Edge, Cloudflare Workers. Headless CMS: Sanity, Contentful, Strapi, Ghost. Content API: REST or GraphQL at build or runtime. Commerce: Shopify, Snipcart. Auth: Auth0, Supabase, NextAuth. Search: Algolia, Meilisearch. Benefits: performance, security, scaling, cost. Serverless limits: cold starts, 15 min timeout, stateless.</p>"),
    ],[F("JAMstack.org","https://jamstack.org/","JAMstack resources"),F("Next.js SSG","https://nextjs.org/docs/pages/building-your-application/rendering/static-generation","Next.js static generation")]),
    ("WebAssembly", "webassembly.html", "High-performance browser code -- Wasm, WASI, Emscripten, and tooling.", "Web", "fab fa-web-awesome", [
        Q("Wasm & Emscripten", "<p>WebAssembly: binary instruction format, near-native speed. Compiled from: C, C++, Rust, Go, Zig. Emscripten: compile C/C++ to Wasm -- emcc hello.c -o hello.html. Linear memory: ArrayBuffer, shared with JS. JS glue: Emscripten generates loader. Limitations: no DOM access, GC in progress, no Web API directly. Threads: SharedArrayBuffer. SIMD: 128-bit packed. Debug: browser DevTools, source maps. Performance: game engines, image processing, compression, SQLite.</p>"),
        Q("WASI & Tooling", "<p>WASI: system interface outside browser. Runtimes: Wasmtime, Wasmer, WasmEdge. Component model: modular Wasm with interfaces. Tooling: wasm-pack (Rust), wasm-bindgen, wasm-tools, Binaryen (wasm-opt). Streaming: WebAssembly.instantiateStreaming. Security: sandboxed, capability-based. Use cases: serverless (Fastly, Cloudflare), plugins, edge computing. Rust to Wasm: wasm-pack build --target web. Go to Wasm: GOOS=js GOARCH=wasm.</p>"),
    ],[F("MDN WebAssembly","https://developer.mozilla.org/en-US/docs/WebAssembly","Wasm documentation"),F("Wasmtime","https://wasmtime.dev/","WASI runtime")]),
    ("CSS Animations & Transitions", "css-animations.html", "CSS animations, transitions, keyframes -- smooth, performant web animations.", "Web", "fab fa-css3-alt", [
        Q("Transitions & Keyframes", "<p>Transitions: transition-property, duration, timing-function (ease, cubic-bezier), delay. Trigger: hover, focus, class change. Performance: transform + opacity only (GPU composited). will-change: hint browser. Keyframes: @keyframes name { from { } to { } }. Animation: name, duration, timing, delay, iteration, direction, fill-mode, play-state. Stagger: animation-delay on children. Houdini: Paint API, Animation Worklet. Scroll-driven: scroll(), view() CSS. Container queries.</p>"),
        Q("Performance & JS", "<p>GPU properties: transform (translate, scale, rotate, skew) + opacity. Avoid: width, height, top, left, margin, padding, box-shadow. rAF: requestAnimationFrame for JS animations. Web Animations API: element.animate(). FLIP: First, Last, Invert, Play. Libraries: GSAP, Framer Motion, Anime.js. prefers-reduced-motion: respect user preference. 3D: perspective, rotateX/Y/Z. Easing: cubic-bezier for natural movement. Steps: for typewriter effect. Debug: DevTools Animations panel.</p>"),
    ],[F("MDN CSS Animations","https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animations","CSS animations guide"),F("Web Animations API","https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API","JS animation API")]),
    ("Static Site Generators", "static-site-generators.html", "Build static sites -- SSG comparison, build process, deployment strategies.", "Web", "fas fa-file-code", [
        Q("SSG Comparison", "<p>SSG: build HTML at build time. Hugo: Go, fastest build. 11ty: JS, flexible templates (Nunjucks, Liquid, Markdown), minimal. Astro: multi-framework, islands, content collections, partial hydration. Next.js: React, SSG+ISR+SSR, API routes. Gatsby: React+GraphQL, rich plugins. Nuxt: Vue, SSG+SSR. Jekyll: Ruby, GitHub Pages. Build output: static HTML, CSS, JS, images. Content: markdown + frontmatter (YAML). Dev server: HMR, incremental builds.</p>"),
        Q("Deployment", "<p>Hosting: Vercel, Netlify, Cloudflare Pages, GitHub Pages, S3+CloudFront. Deploy: git push -> auto build + deploy. Preview: per branch/PR. Domain: custom, SSL (Let's Encrypt). Headers: CSP, HSTS, X-Frame-Options. Image opt: next/image, astro:assets. Search: Lunr, Pagefind, Algolia. RSS: built-in. Sitemap: auto-generated. i18n: locale routing. Analytics: Plausible, Simple Analytics. Incremental: only rebuild changed pages.</p>"),
    ],[F("Eleventy Docs","https://www.11ty.dev/docs/","11ty documentation"),F("Astro Docs","https://docs.astro.build/","Astro web framework")]),
    ("Headless CMS", "headless-cms.html", "Content management -- headless CMS, content modeling, preview, workflow.", "Web", "fas fa-pencil", [
        Q("Content Modeling", "<p>Headless CMS: content + API, no frontend. Content types: author, post, tag. Fields: text, rich text, number, boolean, date, media, reference, JSON, SEO. Rich text: block-based (paragraph, heading, image, code, embed). API: REST or GraphQL, public CDN, private write. Webhooks: notify on change -- rebuild, update search, invalidate CDN. Preview: unpublished content via draft tokens. Versioning: history, rollback. Workflow: draft -> review -> published. Roles: admin, editor, contributor. Assets: upload, transform, CDN delivery.</p>"),
        Q("Platforms", "<p>Cloud: Contentful (enterprise, rich), Sanity (real-time, custom studio), Hygraph (GraphQL-native). Self-hosted: Strapi (Node, plugins, easy), Ghost (publishing), Directus (SQL-based). Git-based: Decap CMS (markdown in repo), TinaCMS (visual editing). Cost: Contentful Free (2 users), Sanity Free (2 users), Strapi (self-hosted free). Migration: import/export JSON. Comparison: Contentful (enterprise), Sanity (custom studio), Strapi (easy setup), Ghost (blogs). SSR vs SSG: fetch at request vs build time.</p>"),
    ],[F("Contentful Docs","https://www.contentful.com/developers/docs/","Contentful docs"),F("Strapi Docs","https://docs.strapi.io/","Strapi CMS")]),
    ("Web Auth (OAuth, JWT, SAML)", "web-authentication.html", "Web authentication -- OAuth 2.0, OpenID Connect, JWT, SAML, WebAuthn.", "Web", "fas fa-lock", [
        Q("OAuth 2.0 & OIDC", "<p>OAuth 2.0: authorization framework. Grant types: Authorization Code + PKCE (most secure), Client Credentials (machine), Device Code (TV/CLI). Access token: short-lived (5-60 min). Refresh token: long-lived, rotate on use. OIDC: identity on OAuth 2 -- ID Token (JWT with user identity). Providers: Auth0, Okta, Keycloak, Firebase, Supabase, Cognito. Social login: Google, GitHub, Apple. PKCE: S256 code_challenge, code_verifier -- prevents interception.</p>"),
        Q("JWT, SAML & WebAuthn", "<p>JWT: header.payload.signature. Signing: HS256 (shared secret), RS256/ES256 (public/private). Best: short exp, no sensitive data, rotate keys. SAML: XML-based enterprise SSO. Assertions, IdP-initiated, SP-initiated. WebAuthn: passwordless -- key pair, challenge-response. Passkeys: synced via cloud (iCloud, Google, 1Password). MFA: TOTP, SMS (not recommended), WebAuthn. Security: rate limit login, CSRF tokens, HttpOnly cookies.</p>"),
    ],[F("OAuth 2.0","https://oauth.net/2/","OAuth 2.0 framework"),F("WebAuthn Guide","https://webauthn.guide/","WebAuthn docs")]),
    ("Web Performance Optimization", "web-performance.html", "Core Web Vitals, lazy loading, caching, CDN, and performance budgets.", "Web", "fas fa-rocket", [
        Q("Core Web Vitals", "<p>LCP (<2.5s): optimize hero image (preload, fetchpriority=high), compress, CDN. CLS (<0.1): set image dimensions, space for embeds, font-display:optional. FID/INP (<100ms/200ms): minimize main thread blocking, code-split, lazy JS. TTFB: fast server response, CDN, preconnect. Measuring: Lighthouse, PageSpeed Insights, web-vitals library, CrUX. Performance budget: 300KB JS, 100KB CSS, 1MB total.</p>"),
        Q("Loading & Caching", "<p>Code splitting: dynamic import(), React.lazy, route-based. Images: WebP/AVIF, srcset, loading=lazy, blur placeholders. Fonts: subset, variable, preload, font-display:optional. Preload: critical resources. Preconnect: early origin connections. Service worker: Workbox (precache, runtime strategies). Cache: Cache-Control immutable for hashed assets. Brotli: better than gzip. HTTP/2 multiplexing. HTTP/3 QUIC. Minimize: HTML, CSS, JS (terser, cssnano). Critical CSS: inline above-fold.</p>"),
    ],[F("Web Vitals","https://web.dev/vitals/","Core Web Vitals guide"),F("web.dev/fast","https://web.dev/fast/","Performance optimization")]),

    # === MORE LINUX (5) ===
    ("Linux From Scratch", "linux-from-scratch.html", "Build Linux from source -- LFS, BLFS, toolchain, and customization.", "Linux", "fas fa-wrench", [
        Q("LFS Build", "<p>LFS: build Linux from source. Host: existing Linux, 10GB+, 4+ CPU. Steps: prepare host, build temporary toolchain (cross-compiler), build system (chroot), configure (boot scripts, kernel, grub). Toolchain: binutils, gcc, glibc. Build order: binutils pass1 -> gcc pass1 -> linux headers -> glibc -> binutils pass2 -> gcc pass2 -> coreutils. Chroot: chroot $LFS /tools/bin/env -i... /tools/bin/bash. Kernel: make menuconfig, modules_install. Boot: grub-mkconfig. LFS version 12.2.</p>"),
        Q("BLFS & Custom", "<p>BLFS: packages after LFS -- networking (DHCP, SSH), X11, desktop (GNOME, KDE), multimedia (ALSA, PipeWire, ffmpeg), office, browser. Systemd or SysV. Benefits: complete control, minimal size, deep understanding. Challenges: long compile, dependency management. Gentoo: Portage similar approach. Config: /etc/fstab, hostname, hosts, resolv.conf. Users/groups: useradd, passwd. Kernel modules: essential drivers.</p>"),
    ],[F("LFS Book","https://www.linuxfromscratch.org/lfs/view/stable/","Linux From Scratch"),F("BLFS","https://www.linuxfromscratch.org/blfs/view/stable/","Beyond LFS")]),
    ("Container Runtimes", "container-runtimes.html", "Container runtimes -- containerd, CRI-O, runc, gVisor, Kata.", "Linux", "fab fa-docker", [
        Q("OCI & containerd", "<p>OCI: runtime spec (config.json + rootfs), image spec (layers, manifest). runc: low-level OCI runtime. containerd: high-level daemon -- pull images, manage lifecycle, snapshots. Shim: per-container process. Namespaces: pid, net, mnt, uts, ipc, user. Cgroups v2: resource limits. Rootless: user namespace remapping. nerdctl: Docker-compatible CLI. Snapshotter: overlayfs, devmapper. K8s: uses containerd or CRI-O.</p>"),
        Q("Sandbox & Security", "<p>crun: fast OCI runtime in C. gVisor: user-space kernel (Sentry) intercept syscalls -- sandboxed. Kata: lightweight VM per container. Firecracker: microVM (AWS Lambda). RuntimeClass: specify runtime per pod. Security: runc (namespace), gVisor (syscall filter), Kata (VM isolation). Performance: runc > crun > gVisor > Kata. Networking: CNI (calico, flannel). crictl: debug containers. CRT config: containerd config.toml.</p>"),
    ],[F("containerd","https://containerd.io/docs/","Container runtime"),F("gVisor","https://gvisor.dev/docs/","Sandboxed runtime")]),
    ("Linux Audio (PipeWire)", "linux-audio-pipewire.html", "Linux audio -- PipeWire, ALSA, PulseAudio, pro-audio setup.", "Linux", "fas fa-music", [
        Q("Audio Stack", "<p>ALSA: kernel-level, hardware access. PulseAudio: sound server, mixing, routing, per-app volume. PipeWire: replaces both -- low latency, dynamic, container. Commands: pactl info/list sinks, pavucontrol, pw-cli, pw-top. ALSA: aplay -l, arecord, alsamixer. Config: /etc/pipeWire/pipewire.conf. Session manager: WirePlumber. Bluetooth: A2DP, HSP, LE Audio, codecs (SBC, aptX, LDAC).</p>"),
        Q("Pro Audio", "<p>PipeWire JACK: pw-jack for pro audio. Latency: buffer 256 (5.3ms) or 64 (1.3ms). DAWs: Ardour, Reaper, Bitwig. Plugins: LV2, VST via yabridge. MIDI: seq, a2jmidi_bridge. Noise cancellation: noisetorch (RNNoise). EasyEffects: EQ, compression, limiting. OBS: PipeWire capture. Troubleshooting: pw-top, pw-dump, journalctl -u pipewire. Crackling: increase buffer.</p>"),
    ],[F("PipeWire","https://pipewire.org/","Linux multimedia"),F("Arch Wiki PipeWire","https://wiki.archlinux.org/title/PipeWire","PipeWire setup")]),
    ("Wayland vs X11", "wayland-x11.html", "Display servers -- Wayland architecture, X11 comparison, migration.", "Linux", "fas fa-display", [
        Q("Wayland", "<p>Wayland: modern compositor protocol. Compositors: wlroots (sway, Hyprland), Mutter (GNOME), KWin (KDE). Client renders surface directly. Security: windows cant see each other, keylog protection. XWayland: X11 apps on Wayland. Features: fractional scaling, VRR, gestures, screen capture via PipeWire. NVIDIA: driver 555+ stable, nvidia_drm.modeset=1. libinput: touchpad gestures. Sway: i3-compatible. Hyprland: animations, blur.</p>"),
        Q("X11 & Migration", "<p>X11: legacy (1984), network transparency, compositor optional. Issues: tearing, no native fractional scaling, no per-pixel alpha. XWayland: compatibility layer. Migration: set GDK_BACKEND=wayland, QT_QPA_PLATFORM=wayland. Screen sharing: xdg-desktop-portal. Clipboard: wl-clipboard. Notifications: mako. Remote: pipewire-remote-desktop. Compositors: sway (tiling), Hyprland (dynamic), river (zen). xdg-desktop-portal: file picker, screen share.</p>"),
    ],[F("Wayland Docs","https://wayland.freedesktop.org/docs/html/","Wayland protocol"),F("Arch Wiki Wayland","https://wiki.archlinux.org/title/Wayland","Wayland guide")]),
    ("Linux Desktop Customization", "linux-desktop-customization.html", "Desktop ricing -- tiling WMs, GTK theming, polybar, conky.", "Linux", "fas fa-paint-brush", [
        Q("Tiling WMs", "<p>Ricing: customize desktop. i3: manual tiling. sway: Wayland i3-clone. hyprland: dynamic, animations, blur, rounded corners. bspwm: binary space partitioning. polybar: status bar. eww: custom widgets. Rofi: app launcher, dmenu replacement. Dunst: notifications. Picom: X11 compositor. Wallpaper: feh (X11), swaybg (Wayland), hyprpaper. Kitty, Alacritty, WezTerm: GPU terminals. Starship: shell prompt.</p>"),
        Q("Themes & Icons", "<p>GTK: ~/.themes, Catppuccin, Tokyo Night, Nord, Dracula. Qt: qt5ct, qt6ct. Icons: ~/.icons, Papirus, Tela. Fonts: JetBrains Mono, Inter, Nerd Fonts. pywal/wallust: colors from wallpaper. Conky: system monitor. Display manager: SDDM, GDM, LightDM. Dotfiles: manage with git bare, stow, chezmoi. r/unixporn: inspiration. Fontconfig: hinting, antialiasing, DPI.</p>"),
    ],[F("Arch Wiki Desktop","https://wiki.archlinux.org/title/Desktop_environment","Desktop customization"),F("Catppuccin","https://catppuccin.com/","Popular theme")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials (p3d)!")
