#!/usr/bin/env python3
"""Generate ~210 more tutorials using data-driven approach."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === WEB FRAMEWORKS (12) ===
    ("Django Web Framework", "django-web-framework.html", '''Build web apps with Django — models, views, templates, ORM, and REST framework.''', "Web", "fab fa-python", [
        Q("Models & ORM", '''<p>Django models define database schema as Python classes. Fields: CharField, IntegerField, ForeignKey, ManyToManyField. ORM: Model.objects.filter(), .exclude(), .annotate(), .select_related() for joins. Migrations: python manage.py makemigrations && migrate. Admin: auto-generated CRUD UI for models with list_display, search_fields, filters.</p>'''),
        Q("Views, URLs & Templates", '''<p>Function-based views (request → response) vs class-based views (ListView, DetailView, CreateView). URL dispatcher: path('articles/', views.article_list), re_path for regex. Templates: DTL (Django Template Language) with {{ variables }}, {% for %}, {% if %}, template inheritance ({% extends "base.html" %}, {% block content %}). Static files: {% static 'css/style.css' %}.</p>'''),
        Q("Django REST Framework", '''<p>DRF builds REST APIs quickly. Serializers: ModelSerializer converts model instances to JSON. ViewSets: ModelViewSet provides CRUD endpoints. Routers: DefaultRouter auto-generates URL patterns. Authentication: TokenAuth, SessionAuth, JWT (djangorestframework-simplejwt). Permissions: IsAuthenticated, IsAdminUser, custom permission classes. Pagination, filtering, and versioning built-in.</p>'''),
    ],[F("Django Documentation","https://docs.djangoproject.com/","Official Django docs"),F("DRF Documentation","https://www.django-rest-framework.org/","Django REST Framework docs")]),
    ("Flask Web Development", "flask-web-development.html", '''Lightweight web apps with Flask — routing, templates, databases, and extensions.''', "Web", "fab fa-python", [
        Q("Routing & Requests", '''<p>Flask routes: @app.route('/users/<int:id>'). Request object: request.method, request.args, request.form, request.json. Response: return jsonify({'key': 'value'}), make_response(), redirect(url_for('index')). Error handlers: @app.errorhandler(404). Session: flask.session dict (signed cookies). Flash messages for user notifications.</p>'''),
        Q("Jinja2 & SQLAlchemy", '''<p>Jinja2 templates: {{ var }}, {% for %}, {% if %}, {% include %}, {% macro %}. Autoescape enabled by default. Flask-SQLAlchemy: db = SQLAlchemy(app), class User(db.Model). CRUD: db.session.add(), .commit(), .delete(). Relationships: db.relationship() for backrefs. Migrations with Flask-Migrate (Alembic).</p>'''),
    ],[F("Flask Documentation","https://flask.palletsprojects.com/","Official Flask docs"),F("Flask Mega-Tutorial","https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world","Comprehensive Flask tutorial")]),
    ("Spring Boot Development", "spring-boot-development.html", '''Enterprise Java with Spring Boot — auto-configuration, data JPA, security, and microservices.''', "Web", "fab fa-java", [
        Q("Auto-Configuration & Starters", '''<p>Spring Boot auto-configures beans based on classpath dependencies. Starters: spring-boot-starter-web (Tomcat + Spring MVC), spring-boot-starter-data-jpa (Hibernate + H2/Datasource), spring-boot-starter-security. @SpringBootApplication = @Configuration + @EnableAutoConfiguration + @ComponentScan. application.properties / application.yml for configuration with profile-specific files.</p>'''),
        Q("Data JPA & REST", '''<p>Spring Data JPA: JpaRepository<Entity, Id> provides save(), findAll(), findById(), delete(). Derived queries: findByLastName(String name), findByEmailAndActive(String email, boolean active). @RestController: @GetMapping, @PostMapping, @PutMapping, @DeleteMapping. ResponseEntity for status codes and headers. HATEOAS for REST hypermedia.</p>'''),
    ],[F("Spring Boot Guide","https://spring.io/guides/gs/spring-boot/","Official Spring Boot guide"),F("Baeldung Spring Boot","https://www.baeldung.com/spring-boot","Spring Boot tutorials")]),
    ("Express.js Deep Dive", "express-js-deep-dive.html", '''Node.js web server with Express — middleware, routing, error handling, and performance.''', "Web", "fab fa-node-js", [
        Q("Middleware Pipeline", '''<p>Express middleware: app.use(express.json()), app.use(cors()), app.use(morgan('combined')). Custom middleware: (req, res, next) => { req.user = getUser(); next(); }. Error middleware: (err, req, res, next) => { console.error(err); res.status(500).json({error: err.message}); }. Third-party: helmet (security), compression (gzip), express-rate-limit, cookie-parser.</p>'''),
        Q("Routing & Controllers", '''<p>Express.Router: const router = express.Router(); router.get('/users', getUsers); app.use('/api', router). Route parameters: /users/:id, req.params.id. Query: req.query.page. Chainable: router.route('/:id').get(getUser).put(updateUser).delete(deleteUser). Async error handling: wrapAsync(fn) catches promise rejections automatically.</p>'''),
    ],[F("Express.js Docs","https://expressjs.com/","Official Express.js documentation"),F("Express Best Practices","https://expressjs.com/en/advanced/best-practice-performance.html","Production best practices")]),
    ("Next.js Full-Stack", "nextjs-full-stack.html", '''Full-stack React with Next.js — SSR, SSG, API routes, and App Router.''', "Web", "fab fa-react", [
        Q("App Router & Layouts", '''<p>Next.js App Router (app/ directory): page.tsx (route UI), layout.tsx (shared layout wrapping children), loading.tsx (streaming SSR), error.tsx (error boundaries). Server Components by default (no JS on client, direct DB access). Client Components: 'use client' for interactivity (hooks, event handlers). Nested layouts persist across navigations.</p>'''),
        Q("Data Fetching & Caching", '''<p>Server Components: async function Page() { const data = await fetch('https://api.example.com/data'); } — automatic caching, deduplication. Revalidation: fetch(url, { next: { revalidate: 3600 } }) or on-demand revalidation (revalidatePath, revalidateTag). Route handlers: app/api/route.ts — similar to API routes, support for streaming. Server Actions: form actions with progressive enhancement.</p>'''),
    ],[F("Next.js Documentation","https://nextjs.org/docs","Official Next.js docs"),F("Vercel Next.js Learn","https://nextjs.org/learn","Next.js interactive course")]),
    ("Vue.js & Nuxt.js", "vuejs-nuxtjs.html", '''Progressive framework Vue.js with Nuxt.js — composition API, Pinia, SSR.''', "Web", "fab fa-vuejs", [
        Q("Composition API", '''<p>Vue 3 Composition API: setup() or <script setup>. Reactive state: ref() (primitives), reactive() (objects). Computed: computed(() => state.value * 2). Watchers: watch(source, callback), watchEffect(callback). Lifecycle: onMounted, onUnmounted, onUpdated. Composables: reusable functions using composition API (like React hooks). Provide/inject for dependency injection.</p>'''),
        Q("Nuxt.js & Pinia", '''<p>Nuxt.js conventions: pages/ (file-based routing), components/ (auto-imported), layouts/, middleware/, composables/. Auto-imports: ref, computed, useFetch, useState. Pinia state management: defineStore('counter', () => { const count = ref(0); function increment() { count.value++ } return { count, increment } }). SSR, SSG, and hybrid rendering modes supported.</p>'''),
    ],[F("Vue.js Documentation","https://vuejs.org/","Official Vue.js docs"),F("Nuxt.js Documentation","https://nuxt.com/docs","Official Nuxt.js documentation")]),
    ("Svelte & SvelteKit", "svelte-sveltekit.html", '''Compile-time React alternative — reactive declarations, stores, and SvelteKit.''', "Web", "fab fa-svelte", [
        Q("Reactivity & Components", '''<p>Svelte shifts reactivity to compile time. Variables are reactive: let count = 0; count++ updates DOM automatically. $: doubled = count * 2 (reactive declaration). {#if}, {#each}, {#await} blocks. Component props: export let name;. Event dispatch: createEventDispatcher. Two-way binding: bind:value={input}. Stores: writable, readable, derived — use $ prefix for auto-subscription.</p>'''),
        Q("SvelteKit Features", '''<p>SvelteKit: file-based routing (src/routes/), +page.svelte (page), +layout.svelte (layout), +server.js (API endpoint). Load functions: export async function load({ fetch, params }) — runs on server first, then client. Form actions: export const actions = { default: async ({ request }) => {...} }. Adapters: adapter-node, adapter-static, adapter-vercel, adapter-cloudflare. Streaming, progressive enhancement, SSR/SSG.</p>'''),
    ],[F("Svelte Documentation","https://svelte.dev/docs","Official Svelte docs"),F("SvelteKit Documentation","https://kit.svelte.dev/docs","Official SvelteKit docs")]),
    ("Angular Development", "angular-development.html", '''Enterprise frontend with Angular — components, services, routing, and RxJS.''', "Web", "fab fa-angular", [
        Q("Components & Templates", '''<p>Angular components: @Component({selector: 'app-user', template: '...', styles: [...]}). Lifecycle: ngOnInit, ngOnDestroy, ngOnChanges. Templates: {{ interpolation }}, [property binding], (event), *ngIf, *ngFor, *ngSwitch. @Input() and @Output() for component communication. Content projection: <ng-content>. Pipes: | date, | currency, | async, custom pipes via @Pipe.</p>'''),
        Q("Services, DI & Routing", '''<p>Services: @Injectable({ providedIn: 'root' }) for singleton services. Dependency injection: constructor(private userService: UserService) {}. HttpClient: this.http.get<User[]>('/api/users'). Router: const routes: Routes = [{ path: 'users/:id', component: UserDetailComponent }]. Guards: CanActivate, CanDeactivate. Lazy loading: loadChildren: () => import('./users/users.module').then(m => m.UsersModule).</p>'''),
    ],[F("Angular Documentation","https://angular.dev/","Official Angular docs"),F("Angular University","https://angular-university.io/","Angular courses and tutorials")]),
    ("ASP.NET Core", "aspnet-core-development.html", '''Cross-platform .NET web apps — MVC, Razor Pages, Entity Framework, and Web API.''', "Web", "fab fa-microsoft", [
        Q("MVC & Razor Pages", '''<p>ASP.NET Core MVC: Controllers with actions returning IActionResult/ViewResult. Routing: [Route("api/[controller]")], [HttpGet("{id}")]. Razor syntax: @model IEnumerable<User>, @foreach(var u in Model) { ... }, @Html.DisplayFor, tag helpers (<form asp-action="Create">). Razor Pages: @page directive, PageModel class with OnGet, OnPost handlers — simpler than MVC for page-focused apps.</p>'''),
        Q("Entity Framework & Web API", '''<p>EF Core: DbContext with DbSet<T> properties. Migrations: dotnet ef migrations add InitialCreate, dotnet ef database update. LINQ: context.Users.Where(u => u.IsActive).OrderBy(u => u.Name). Web API: [ApiController], [Route], auto-400 on invalid ModelState. Minimal APIs (NET 6+): app.MapGet("/users", async (AppDbContext db) => await db.Users.ToListAsync()); OpenAPI/Swagger built-in.</p>'''),
    ],[F("ASP.NET Core Docs","https://learn.microsoft.com/en-us/aspnet/core/","Official ASP.NET Core docs"),F(".NET Tutorials","https://dotnet.microsoft.com/learn","Learn .NET")]),
    ("Gatsby & Static Sites", "gatsby-static-sites.html", '''Blazing-fast static sites with Gatsby — GraphQL, plugins, and the JAMstack.''', "Web", "fab fa-gatsby", [
        Q("Gatsby Architecture", '''<p>Gatsby is a React-based static site generator. Build-time GraphQL: page queries (in page components) and static queries (in any component, useStaticQuery). Source plugins: gatsby-source-filesystem (local files), gatsby-source-wordpress, gatsby-source-contentful. Transformer plugins: gatsby-transformer-remark (Markdown → HTML), gatsby-transformer-sharp (image processing). Automatic code splitting, prefetching, and image optimization.</p>'''),
        Q("Building & Deployment", '''<p>gatsby develop (hot reload dev server), gatsby build (production build → public/ folder). gatsby-node.js: createPages API for programmatic page creation from data. gatsby-config.js: site metadata, plugins, path prefix. Deploy: Gatsby Cloud (CI/CD with previews), Netlify, Vercel, Cloudflare Pages. Incremental builds: only rebuild changed pages (faster deploys).</p>'''),
    ],[F("Gatsby Documentation","https://www.gatsbyjs.com/docs/","Official Gatsby docs"),F("JAMstack Resources","https://jamstack.org/","JAMstack community and resources")]),
    ("Hugo Static Site Generator", "hugo-static-site.html", '''Fastest static site generator — Go templates, content management, and themes.''', "Web", "fas fa-bolt", [
        Q("Hugo Structure & Templates", '''<p>Hugo directory: content/ (Markdown), layouts/ (Go HTML templates), static/ (assets), config.toml/yaml/json. Template hierarchy: baseof.html (shell), list.html (section pages), single.html (individual pages). Shortcodes: {{< youtube id >}}, custom shortcodes in layouts/shortcodes/. Variables: .Title, .Content, .Date, .Params.custom_param. Pagination: {{ template "_internal/pagination.html" . }}.</p>'''),
        Q("Taxonomies & Multilingual", '''<p>Hugo taxonomies: tags, categories (or custom). content/posts/post1.md: tags = ["golang", "web"]. Taxonomy pages: /tags/golang/ lists all tagged pages. Multilingual: config.toml [languages.en], [languages.fr]. Content: content/en/ and content/fr/. i18n: {{ i18n "hello" }} with i18n/en.yaml. Hugo Modules: theme components as Git submodules (go-based dependency management).</p>'''),
    ],[F("Hugo Documentation","https://gohugo.io/documentation/","Official Hugo docs"),F("Hugo Themes","https://themes.gohugo.io/","Hugo theme gallery")]),
    ("Eleventy (11ty)", "eleventy-static-site.html", '''Simpler static site generator — zero-config, multiple template languages, and fast builds.''', "Web", "fas fa-zap", [
        Q("Template Flexibility", '''<p>Eleventy supports Nunjucks, Liquid, EJS, Handlebars, Pug, and Vanilla JS templates. Permalinks: permalink: /notes/{{ page.fileSlug }}/. Data cascade: global data (_data/*.json), template front matter, directory data files (_dir/*.json). Collections: tags create collections — collections.posts. Pagination: paginate a collection over multiple output files.</p>'''),
        Q("Performance & Deployment", '''<p>Eleventy is benchmark-fast — builds 1000+ pages in <1s. Zero client-side JS by default — pure HTML/CSS output. Plugins: @11ty/eleventy-plugin-rss, @11ty/eleventy-img (build-time image optimization), @11ty/eleventy-navigation (breadcrumbs, prev/next). Deploy: Netlify (npx eleventy --serve for dev), Vercel, GitHub Pages. PWA support: service worker generation via Workbox plugin.</p>'''),
    ],[F("Eleventy Documentation","https://www.11ty.dev/docs/","Official 11ty docs"),F("Learn Eleventy","https://learn-eleventy.pages.dev/","Eleventy tutorials and guides")]),

    # === PROGRAMMING LANGUAGES (14) ===
    ("Haskell Functional Programming", "haskell-functional-programming.html", '''Pure functional programming with Haskell — monads, type classes, and lazy evaluation.''', "Programming", "fas fa-lambda", [
        Q("Core Concepts", '''<p>Haskell is pure functional: no side effects, immutable data, lazy evaluation. Type system: strong, static, inferred. Basic types: Int, Integer, Float, Bool, Char, String. Functions: add x y = x + y, curried by default. Pattern matching: head (x:_) = x. Guards: sign x | x > 0 = "positive" | x < 0 = "negative" | otherwise = "zero". List comprehensions: [x*2 | x <- [1..10], x `mod` 2 == 0].</p>'''),
        Q("Monads & IO", '''<p>Monads handle effects in pure contexts. Maybe monad: Just 5 >>= (\\x -> Just (x+1)). IO monad: main = do { putStrLn "Name:"; name <- getLine; putStrLn ("Hello " ++ name) }. do notation is syntactic sugar for >>= and >>. Common Monads: Maybe (nullable), Either (error handling), Reader (dependency injection), Writer (logging), State (mutable state), IO (input/output).</p>'''),
    ],[F("Haskell Documentation","https://www.haskell.org/documentation/","Official Haskell resources"),F("Learn You a Haskell","http://learnyouahaskell.com/","Beginner Haskell tutorial")]),
    ("Scala & Functional JVM", "scala-functional-jvm.html", '''Scala combines OOP and functional programming on the JVM — Akka, Play, and Cats.''', "Programming", "fab fa-scala", [
        Q("Scala Basics", '''<p>Scala runs on JVM with full Java interop. val (immutable), var (mutable). Functions: def add(x: Int, y: Int): Int = x + y. Case classes: case class User(id: Int, name: String) — auto toString, equals, copy, pattern matching. Pattern matching: x match { case 1 => "one"; case _ => "other" }. Options: Some/None instead of null. For comprehensions: for { x <- Some(5); y <- Some(10) } yield x + y.</p>'''),
        Q("Akka & Actors", '''<p>Akka implements the Actor model for concurrency. Actors: class MyActor extends Actor { def receive = { case msg => sender() ! "response" } }. ActorSystem manages actors hierarchically. Supervision: oneForOne strategy restarts children on failure. Akka HTTP: routes defined with directives (path, get, complete). Akka Streams: reactive streams with back-pressure — Source, Flow, Sink.</p>'''),
    ],[F("Scala Documentation","https://docs.scala-lang.org/","Official Scala docs"),F("Akka Documentation","https://akka.io/docs/","Akka framework docs")]),
    ("Julia for Scientific Computing", "julia-scientific-computing.html", '''High-performance scientific computing with Julia — multiple dispatch, parallelism, and ML.''', "Programming", "fas fa-flask", [
        Q("Multiple Dispatch", '''<p>Julia's core feature: functions specialize on all argument types. f(x::Int, y::Float64) = x + y. Type hierarchy: abstract types (Number, AbstractFloat), concrete types (Float64, Int32), composite types (struct Point x; y; end). Parametric types: Vector{Float64}. Multiple dispatch makes generic code fast — write once, specialize per type without performance penalty.</p>'''),
        Q("Scientific Computing", '''<p>Julia excels at numerical computing. Arrays: A = [1 2; 3 4] (2x2 matrix), comprehensions, broadcasting (A .+ 1). LinearAlgebra: \`A \\ b\` solves linear systems, eigvals(A), svd(A). Plots.jl: plot(x, y, seriestype=:scatter, title="My Plot"). DataFrames: df = DataFrame(Name=["A","B"], Value=[1,2]), filter, transform, groupby. DifferentialEquations.jl: ODEProblem, solve.</p>'''),
    ],[F("Julia Documentation","https://docs.julialang.org/","Official Julia docs"),F("JuliaAcademy","https://juliaacademy.com/","Free Julia courses")]),
    ("Lua Scripting & Embedding", "lua-scripting-embedding.html", '''Lightweight embeddable scripting language — Lua syntax, C API, and game scripting.''', "Programming", "fas fa-rocket", [
        Q("Lua Syntax & Tables", '''<p>Lua is minimal (~200KB) and fast. Tables are the universal data structure: t = {key = "value", [1] = "array"}. Metatables: setmetatable(t, {__index = other, __call = f}) enables OOP, operator overloading. Functions are first-class: local fn = function(x) return x*2 end. Coroutines: co = coroutine.create(fn); coroutine.resume(co). Multiple return values: function f() return 1, 2, 3 end.</p>'''),
        Q("C API & Embedding", '''<p>Embed Lua in C/C++: luaL_newstate(), luaL_openlibs(L), luaL_dofile(L, "script.lua"). Stack-based communication: lua_pushnumber(L, 42), lua_getglobal(L, "myvar"). Calling Lua from C: lua_pcall(L, nargs, nresults, 0). Calling C from Lua: lua_register(L, "cfunc", c_function). LuaJIT: JIT compiler for Lua — 10-50x faster, FFI library for direct C binding.</p>'''),
    ],[F("Lua Manual","https://www.lua.org/manual/5.4/","Official Lua reference manual"),F("LuaJIT","https://luajit.org/","LuaJIT documentation")]),
    ("R Statistical Computing", "r-statistical-computing.html", '''Statistical computing and data visualization with R — tidyverse, ggplot2, and Shiny.''', "Programming", "fab fa-r-project", [
        Q("Tidyverse & Data Manipulation", '''<p>Tidyverse packages work together: dplyr (data manipulation), tidyr (data tidying), readr (data import), purrr (functional programming), stringr (strings), lubridate (dates). dplyr verbs: df %>% filter(age > 18) %>% group_by(city) %>% summarise(avg = mean(income), n = n()). %>% (pipe) chains operations. Tibbles: modern data frames with better printing.</p>'''),
        Q("ggplot2 & Shiny", '''<p>ggplot2 implements Grammar of Graphics. Layers: ggplot(data, aes(x, y)) + geom_point() + geom_smooth(method = "lm") + labs(title = "Scatter") + theme_minimal(). Facets: facet_wrap(~category). Shiny: web apps from R — ui = fluidPage(...), server = function(input, output) { output$plot <- renderPlot({...}) }. Reactive values, observers, modules for complex apps.</p>'''),
    ],[F("R Documentation","https://www.r-project.org/","Official R project"),F("RStudio Education","https://education.rstudio.com/","R tutorials and teaching materials")]),
    ("Dart Programming Language", "dart-programming-language.html", '''Client-optimized language for UI — sound null safety, isolates, and FFI.''', "Programming", "fab fa-dart", [
        Q("Dart Basics & Sound Null Safety", '''<p>Dart is type-safe with sound null safety: int? nullable, int non-nullable (!). Named parameters: void greet({required String name, int age = 0}). Records: (String, int) record = ('Alice', 30). Pattern matching: switch (record) { case ('Alice', var age) => ... }. Cascade notation: obj..method1()..method2() for fluent APIs. Extension methods: extension on String { int parseInt() => int.parse(this); }.</p>'''),
        Q("Isolates & FFI", '''<p>Isolates: Dart's concurrency model — no shared memory, message passing. Isolate.spawn((msg) => print(msg), 'hello'). Flutter uses root isolate for UI, spawn isolates for compute. async/await with Future and Stream. FFI (Foreign Function Interface): import 'dart:ffi'; typedef C function signatures, call C libraries from Dart without native extensions. Dart:io for file, network, and process I/O.</p>'''),
    ],[F("Dart Documentation","https://dart.dev/guides","Official Dart docs"),F("Dart Language Tour","https://dart.dev/language","Dart language features tour")]),
    ("Elixir & Phoenix", "elixir-phoenix.html", '''Concurrent, fault-tolerant apps with Elixir/Erlang VM — Phoenix, OTP, and LiveView.''', "Programming", "fas fa-fire", [
        Q("Elixir & OTP", '''<p>Elixir runs on BEAM (Erlang VM) — lightweight processes, fault tolerance, hot code reloading. Pattern matching: {:ok, result} = {:ok, 42}. Pipe operator: "hello" |> String.upcase() |> String.reverse(). OTP: GenServer (stateful server process), Supervisor (restart strategy — one_for_one, rest_for_one), Application (start/stop supervision tree). Tasks: Task.async(fn -> heavy_computation() end) | Task.await(task).</p>'''),
        Q("Phoenix & LiveView", '''<p>Phoenix web framework: routes (get "/users", UserController, :index), controllers, Ecto (DB wrapper with changesets, queries, migrations). Phoenix.LiveView: server-rendered, real-time UI — no JS required. def mount(_params, _session, socket) — assigns state, handle_event("click", _val, socket) for user interactions. PubSub: Phoenix.PubSub.broadcast(topic, msg) for real-time features (chat, notifications).</p>'''),
    ],[F("Elixir Documentation","https://elixir-lang.org/docs.html","Official Elixir docs"),F("Phoenix Framework","https://www.phoenixframework.org/","Official Phoenix framework")]),
    ("Clojure & Lisp on JVM", "clojure-lisp-jvm.html", '''Modern Lisp dialect on JVM — immutable data, REPL-driven development, and ClojureScript.''', "Programming", "fas fa-code", [
        Q("Immutable Data & REPL", '''<p>Clojure is a Lisp dialect on JVM with immutable persistent data structures. Data structures: list '(1 2 3), vector [1 2 3], map {:key "value"}, set #{1 2 3}. Functions: (defn add [x y] (+ x y)). Higher-order: (map inc [1 2 3]), (filter even? [1 2 3 4]), (reduce + [1 2 3]). REPL-driven development: interactive coding — eval, test, reload without restart.</p>'''),
        Q("Concurrency & ClojureScript", '''<p>Clojure concurrency: atoms (sync, coordinated), refs (sync, coordinated, STM), agents (async), core.async (channels, go blocks). ClojureScript: Clojure compiled to JS, interop with JS libraries (.. obj -method, js/console.log). Reagent: React wrapper — (defn component [] [:div "Hello"]). Re-frame: ClojureScript SPA framework — app state, events, subscriptions.</p>'''),
    ],[F("Clojure Documentation","https://clojure.org/","Official Clojure site"),F("ClojureScript","https://clojurescript.org/","Official ClojureScript docs")]),
    ("Erlang & BEAM", "erlang-beam.html", '''Concurrent, distributed, fault-tolerant systems on the BEAM VM.''', "Programming", "fas fa-cogs", [
        Q("Erlang Concurrency", '''<p>Erlang processes are lightweight (microseconds to spawn, ~300 words each). Spawn: Pid = spawn(fun() -> loop() end). Message passing: Pid ! {self(), hello}, receive {From, Msg} -> io:format("Got ~p~n", [Msg]) end. Process linking: link(Pid) — linked processes receive exit signals. Monitors: monitor(process, Pid) — receive {'DOWN', ...} on crash without crashing.</p>'''),
        Q("OTP & Distribution", '''<p>OTP (Open Telecom Platform): gen_server (callback module for server), gen_statem (state machine), supervisor (restart strategies). gen_server callbacks: init/1, handle_call/3, handle_cast/2, terminate/2. Distribution: nodes connect via epmd, spawn processes on remote nodes: spawn(Node, fun() -> ... end). Mnesia: distributed DBMS built into Erlang. Hot code swapping: release_handler for zero-downtime updates.</p>'''),
    ],[F("Erlang Documentation","https://www.erlang.org/docs","Official Erlang docs"),F("Learn You Some Erlang","https://learnyousomeerlang.com/","Beginner Erlang book")]),
    ("Zig Systems Programming", "zig-systems-programming.html", '''Modern systems programming — manual memory management, comptime, and C interop.''', "Programming", "fas fa-microchip", [
        Q("Comptime & Memory", '''<p>Zig: comptime (compile-time execution) — generics, type reflection without macros. const std = @import("std"); pub fn main() void { const msg = comptime blk: { break :blk "Hello, world!"; }; std.debug.print("{s}\n", .{msg}); }. Manual memory management: allocator pattern (std.heap.page_allocator, arena, FixedBufferAllocator). No hidden allocations — explicit allocator passing. no default overflow checks, no hidden control flow.</p>'''),
        Q("Zig vs C Interop", '''<p>Zig is a first-class C compiler (zig cc / zig c++). Direct C interop: @cImport(@cInclude("stdio.h")), call C functions without FFI. @cDefine, @cInclude for C headers. Cross-compilation: zig targets lists all targets, zig build-exe --target x86_64-windows main.zig. Build system: build.zig with Builder pattern — addExecutable, addLibrary, addTest. Package manager: zig fetch for dependencies.</p>'''),
    ],[F("Zig Documentation","https://ziglang.org/documentation/master/","Official Zig docs"),F("Zig Learn","https://ziglearn.org/","Comprehensive Zig guide")]),
    ("Nim Programming Language", "nim-programming-language.html", '''Efficient, expressive, Python-like systems programming — compile to C/JS.''', "Programming", "fas fa-gem", [
        Q("Nim Syntax & Metaprogramming", '''<p>Nim compiles to C (or JS, C++, Objective-C). Python-like syntax: var x = 5, let y = "hello" (immutable), proc add(a, b: int): int = a + b. Type inference, generics: proc max[T](a, b: T): T = if a > b: a else: b. Metaprogramming: macros operate on AST — write compile-time code generation. Templates: template twice(expr): untyped = expr * 2 (hygienic, unlike C macros).</p>'''),
        Q("Performance & FFI", '''<p>Nim compiles to efficient C — zero-cost abstractions, no GC per object (optional GC). FFI: {.importc: "printf", header: "<stdio.h>".} proc printf(frmt: cstring): cint {.varargs.}. Export: proc myFunc(x: int): int {.exportc.} =. Bindings for any C library. Async: asyncdispatch, asyncdb, httpclient. Memory: ref (GC-managed), ptr (raw pointer), ARC/ORC (new GC — deterministic, no stop-the-world).</p>'''),
    ],[F("Nim Documentation","https://nim-lang.org/documentation.html","Official Nim docs"),F("Nim by Example","https://nim-by-example.github.io/","Nim examples and tutorials")]),
    ("Crystal Language", "crystal-language.html", '''Ruby-like syntax, compiled, type-inferred — LLVM backend, C bindings.''', "Programming", "fas fa-gem", [
        Q("Crystal Basics", '''<p>Crystal: compiled, statically typed with global type inference, Ruby-inspired syntax. def add(x, y) = x + y — type inferred. Types: Int32, Float64, String, Bool, Nil, Symbol. Union types: Int32 | String. nilable: String?. Proc: ->(x : Int32) { x + 1 }. Macros: macro define_method(name, body) {{ "def #{name.id}\n #{body}\n end".id }} end. Macros run at compile time for metaprogramming.</p>'''),
        Q("Concurrency & C Bindings", '''<p>Crystal concurrency: Fibers (lightweight, cooperative), spawn { http_request() }. Channels: ch = Channel(Int32).new; spawn { ch.send(42) }; value = ch.receive. Select: select when x = ch1.receive { ... } when y = ch2.receive { ... }. C bindings: @[Link("pcre")] lib LibPCRE; fun compile = pcre_compile(...). No GC pause — Crystal uses precise garbage collection with generational and incremental collection.</p>'''),
    ],[F("Crystal Documentation","https://crystal-lang.org/docs/","Official Crystal docs"),F("Crystal by Example","https://crystalbyexample.com/","Crystal examples")]),

    # === DATABASES & STORAGE (10) ===
    ("Amazon DynamoDB", "dynamodb-guide.html", '''NoSQL key-value and document database — single-digit millisecond performance at scale.''', "Database", "fab fa-aws", [
        Q("Tables, Items & Queries", '''<p>DynamoDB is serverless NoSQL. Tables: partition key (HASH) + optional sort key (RANGE). Item: up to 400KB, attributes (M, L, S, N, SS, NS, BS, BOOL, NULL). Queries: Query by PK (+ optional SK conditions) — most efficient. Scan: full table scan (expensive, avoid in production). Secondary indexes: GSI (global — any attribute), LSI (local — same PK, different SK).</p>'''),
        Q("Capacity & Best Practices", '''<p>Capacity modes: On-demand (auto-scales, pay per request — good for unpredictable) vs Provisioned (RCUs/WCUs — cost-effective for predictable). Auto Scaling: adjust provisioned capacity based on utilization. DAX: in-memory cache (microsecond reads). Best practices: single-table design (one table per app), use sparse indexes, avoid hot partitions (distribute keys), use Exponential Backoff for throttled requests.</p>'''),
    ],[F("DynamoDB Developer Guide","https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/","Official DynamoDB docs"),F("DynamoDB Best Practices","https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/best-practices.html","DynamoDB design patterns")]),
    ("Firebase Firestore", "firebase-firestore.html", '''NoSQL document database with real-time sync, offline support, and security rules.''', "Database", "fab fa-google", [
        Q("Data Model & Queries", '''<p>Firestore: collections contain documents, documents contain fields (and subcollections). Document: { name: "Alice", age: 30, addresses: [{city: "NYC"}] }. Queries: db.collection("users").where("age", ">=", 18).orderBy("name").limit(10).get(). Composite indexes: automatic for simple, manual for multi-field queries. Real-time: onSnapshot(callback) — websocket, updates on changes. Array-contains, in, array-contains-any for flexible filtering.</p>'''),
        Q("Security Rules & Offline", '''<p>Security rules: match /databases/{database}/documents { match /users/{userId} { allow read, write: if request.auth != null && request.auth.uid == userId; } }. Validate data: allow write: if request.resource.data.name is string && request.resource.data.age is number. Offline persistence: enabled by default on mobile (cache queries). Conflicts: last-write-wins. Multi-region: strong consistency, automatic backups.</p>'''),
    ],[F("Firestore Documentation","https://firebase.google.com/docs/firestore","Official Firestore docs"),F("Firestore Data Modeling","https://firebase.blog/posts/2021/02/firestore-data-modeling/","Firestore modeling guide")]),
    ("CouchDB & PouchDB", "couchdb-pouchdb.html", '''Offline-first NoSQL with multi-master replication and conflict resolution.''', "Database", "fas fa-database", [
        Q("CouchDB Documents & Views", '''<p>CouchDB is a JSON document store with multi-master replication. Document: { "_id": "user:alice", "name": "Alice", "age": 30 }. Views (MapReduce): function(doc) { if (doc.age) emit(doc.age, doc.name); } — built with JavaScript. Reduce: _sum, _count, _stats or custom reduce. Mango queries: {"selector": {"age": {"$gte": 18}}, "fields": ["name"]} — MongoDB-like JSON queries.</p>'''),
        Q("Replication & PouchDB", '''<p>CouchDB replication: continuous one-way or two-way sync between databases. PouchDB: CouchDB-compatible JS database that runs in the browser. Works offline — sync when online: localDB = new PouchDB('mydb'); remoteDB = new PouchDB('http://example.com/db'); localDB.replicate.to(remoteDB).on('complete', ...). Conflict resolution: revisions tree, _rev tracking, manual merge or last-write-wins.</p>'''),
    ],[F("CouchDB Documentation","https://docs.couchdb.org/","Official CouchDB docs"),F("PouchDB Documentation","https://pouchdb.com/","Offline-first browser database")]),
    ("Neo4j Graph Database", "neo4j-graph-database.html", '''Property graph database — Cypher queries, graph modeling, and recommendations.''', "Database", "fas fa-project-diagram", [
        Q("Cypher Query Language", '''<p>Cypher: declarative graph query language. MATCH (p:Person)-[:KNOWS]->(f:Person) WHERE p.name = "Alice" RETURN f.name. Create: CREATE (a:Person {name: "Alice"})-[:KNOWS {since: 2020}]->(b:Person {name: "Bob"}). Aggregation: MATCH (p:Person)-[:PURCHASED]->(prod:Product) RETURN p.name, count(prod) AS purchases ORDER BY purchases DESC. Indexes: CREATE INDEX FOR (p:Person) ON (p.name).</p>'''),
        Q("Graph Modeling & Traversal", '''<p>Graph modeling: nodes (entities), relationships (connections), properties (attributes). Labels group nodes (:Person, :Company). Relationship types: :KNOWS, :WORKS_AT, :LIVES_IN. Traversal: BFS/DFS via Cypher — MATCH path = (a:Person)-[:KNOWS*1..3]-(b:Person). Shortest path: shortestPath((a)-[*]-(b)). Graph algorithms: PageRank, Louvain (community detection), Dijkstra (weighted paths) via GDS library.</p>'''),
    ],[F("Neo4j Documentation","https://neo4j.com/docs/","Official Neo4j docs"),F("Neo4j Graph Academy","https://graphacademy.neo4j.com/","Free Neo4j courses")]),
    ("MariaDB Deep Dive", "mariadb-deep-dive.html", '''Advanced MariaDB — storage engines, replication, Galera cluster, and performance tuning.''', "Database", "fas fa-database", [
        Q("Storage Engines", '''<p>MariaDB storage engines: InnoDB (default, ACID, row-level locking, MVCC), Aria (crash-safe, MyISAM replacement — page-level locking), MyISAM (table locking, full-text search), ColumnStore (columnar, analytics), Spider (sharding across nodes), Connect (access external data sources — CSV, XML, Excel, ODBC). Engine selection: InnoDB for OLTP, ColumnStore for OLAP, Spider for scaling writes.</p>'''),
        Q("Replication & Galera", '''<p>Replication: master-slave (async, semi-sync), master-master (circular, bidirectional). Binlog formats: STATEMENT, ROW, MIXED. GTID (Global Transaction ID) for automatic failover positioning. Galera Cluster: synchronous multi-master replication — wsrep provider, certification-based replication. Nodes: 3 minimum, auto-member control, state snapshot transfer (SST) for new nodes. Galera limitations: no XA transactions, no gap locks, all tables must have PK.</p>'''),
    ],[F("MariaDB Knowledge Base","https://mariadb.com/kb/en/","Official MariaDB documentation"),F("Galera Cluster Documentation","https://galeracluster.com/library/","Galera cluster docs")]),
    ("Oracle Database Basics", "oracle-database-basics.html", '''Enterprise relational database — SQL*Plus, PL/SQL, and Oracle architecture.''', "Database", "fas fa-database", [
        Q("Oracle Architecture", '''<p>Oracle database: instance (memory structures — SGA, PGA) + database (data files, control files, redo logs). SGA: Shared Pool (library cache + dictionary cache), Buffer Cache (data blocks), Redo Log Buffer. Processes: PMON (process monitor), SMON (system monitor), DBWn (database writer), LGWR (log writer), CKPT (checkpoint). Tablespaces: logical storage units — SYSTEM, SYSAUX, TEMP, UNDO, USERS.</p>'''),
        Q("PL/SQL & SQL*Plus", '''<p>PL/SQL: block-structured language — DECLARE (variables), BEGIN (statements), EXCEPTION (error handling). Cursors: CURSOR c IS SELECT * FROM emp; OPEN c; FETCH c INTO rec; CLOSE c. Procedures: CREATE PROCEDURE raise_salary(p_id INT, p_amt NUMBER) IS BEGIN UPDATE emp SET sal = sal + p_amt WHERE id = p_id; END;. SQL*Plus: sqlplus user/pass@db, SET LINESIZE, SET PAGESIZE, @script.sql. AWR reports: @?/rdbms/admin/awrrpt.sql.</p>'''),
    ],[F("Oracle Documentation","https://docs.oracle.com/en/database/","Official Oracle DB docs"),F("Oracle Dev Gym","https://devgym.oracle.com/","Oracle learning platform")]),
    ("SQL Server & T-SQL", "sql-server-tsql.html", '''Microsoft SQL Server — T-SQL, indexes, SSIS, SSRS, and high availability.''', "Database", "fab fa-microsoft", [
        Q("T-SQL & Querying", '''<p>T-SQL extends SQL with procedural features. Variables: DECLARE @count INT = 0. CTEs: WITH cte AS (SELECT * FROM users) SELECT * FROM cte. Window functions: ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC). Dynamic SQL: EXEC sp_executesql N'SELECT * FROM ' + @table. TRY...CATCH for error handling. Temp tables: #local (##global), table variables @table.</p>'''),
        Q("HA & BI Tools", '''<p>High Availability: Always On Availability Groups (synchronous/async replicas, automatic failover, readable secondaries), Failover Cluster Instances (shared storage, IP/hostname failover), Log Shipping (async, manual failover). Business Intelligence: SSIS (ETL — extract, transform, load), SSRS (reporting — paginated, mobile, KPIs), SSAS (multidimensional/tabular OLAP cubes). Columnstore indexes for analytics performance improvement.</p>'''),
    ],[F("SQL Server Docs","https://learn.microsoft.com/en-us/sql/","Official SQL Server docs"),F("SQL Server Central","https://www.sqlservercentral.com/","Community articles and tutorials")]),
    ("Redis Deep Dive", "redis-deep-dive.html", '''Advanced Redis — data structures, persistence, clustering, and caching patterns.''', "Database", "fas fa-bolt", [
        Q("Data Structures", '''<p>Redis data structures: String (caching, counters), List (queues, stacks — LPUSH, RPOP, BLPOP blocking), Set (unique items — SADD, SISMEMBER, SUNION), Sorted Set (leaderboards — ZADD, ZRANGEBYSCORE, ZREVRANK), Hash (objects — HSET, HGETALL), Bitmap (tracking — SETBIT, BITCOUNT), HyperLogLog (cardinality — PFADD, PFCOUNT), Stream (message queue — XADD, XREAD, XREADGROUP). Geospatial: GEOADD, GEORADIUS for location-based queries.</p>'''),
        Q("Persistence & Clustering", '''<p>Persistence: RDB (snapshots — save 900 1), AOF (append-only log — everysec, always), or both. Cluster: automatic sharding (16384 slots), replication (master-replica per shard), no centralized proxy. Sentinel: HA monitoring — auto-failover, master detection, client redirection. Redis Stack: RediSearch (full-text search), RedisJSON (native JSON), RedisTimeSeries, RedisBloom (probabilistic data structures — bloom filter, cuckoo filter).</p>'''),
    ],[F("Redis Documentation","https://redis.io/docs/","Official Redis docs"),F("Redis University","https://university.redis.com/","Free Redis courses")]),
    ("Elasticsearch Deep Dive", "elasticsearch-deep-dive.html", '''Search and analytics — inverted index, mappings, aggregations, and cluster operations.''', "Database", "fas fa-search", [
        Q("Mapping & Analysis", '''<p>Elasticsearch index: collection of documents with mappings. Mapping: property name, type (text, keyword, integer, date, geo_point, nested), analyzer (standard, simple, whitespace, custom with char/word/token filters). Inverted index: token → document list. Analysis chain: character filter → tokenizer → token filter (lowercase, stop words, synonyms, ngrams). multi-fields: title.text (full-text search) and title.keyword (sorting, aggregations).</p>'''),
        Q("Aggregations & Cluster", '''<p>Aggregations: metric (avg, sum, cardinality), bucket (terms, date_histogram, range, filter), pipeline (derivative, moving_avg, bucket_script). Query types: match (full-text), term (exact), bool (must/should/must_not), range, geo_distance, function_score (relevance boosts). Cluster: nodes (master, data, ingest, coordinating), discovery (Zen, cloud-based), shards (primary + replicas), rebalancing, rolling restarts. ILM (Index Lifecycle Management): hot → warm → cold → delete.</p>'''),
    ],[F("Elasticsearch Guide","https://www.elastic.co/guide/en/elasticsearch/reference/current/","Official Elasticsearch docs"),F("Elasticsearch: The Definitive Guide","https://www.elastic.co/guide/en/elasticsearch/guide/current/","Elasticsearch book")]),

    # === CLOUD SERVICES (12) ===
    ("AWS Lambda & Serverless", "aws-lambda-serverless.html", '''Serverless compute on AWS — Lambda functions, triggers, and best practices.''', "Cloud", "fab fa-aws", [
        Q("Lambda Fundamentals", '''<p>AWS Lambda runs code without provisioning servers. Runtimes: Node.js, Python, Java, Go, Ruby, .NET, Custom (provided.al2 via layers). Handler: def handler(event, context): return {"statusCode": 200}. Event sources: S3 (object create), DynamoDB Streams, Kinesis, SQS, SNS, API Gateway (HTTP/REST), EventBridge (scheduled/event rules). Concurrency: reserved (guaranteed capacity), provisioned (pre-warmed), burst limits (500-3000 per region).</p>'''),
        Q("Best Practices & SAM", '''<p>Best practices: keep functions small (single purpose), stateless (externalize state to DynamoDB/ElastiCache), cold start mitigation (provisioned concurrency, SnapStart for Java). Lambda Power Tuning: find optimal memory (128-10240MB) vs cost trade-off. AWS SAM: serverless.yml — Transform: AWS::Serverless-2016-10-31. Resources: AWS::Serverless::Function, API, SimpleTable, StateMachine. sam build && sam deploy --guided.</p>'''),
    ],[F("AWS Lambda Docs","https://docs.aws.amazon.com/lambda/","Official Lambda docs"),F("AWS SAM","https://aws.amazon.com/serverless/sam/","Serverless Application Model")]),
    ("Google Cloud Run", "google-cloud-run.html", '''Serverless containers on Google Cloud — autoscaling, CI/CD, and pricing.''', "Cloud", "fab fa-google", [
        Q("Cloud Run Concepts", '''<p>Cloud Run runs stateless HTTP containers. Container must listen on $PORT. Max 4 vCPU, 32GB memory, 60min request timeout. Autoscaling: min/max instances (0 for scale-to-zero) — concurrency (80 concurrent requests per instance by default). Cold starts: min instances >0 avoids. CPU always on (paid) vs CPU throttled (free tier). Regions: multi-region deployment for HA. Custom domains mapped, managed SSL.</p>'''),
        Q("CI/CD & GCR", '''<p>Build: Cloud Build — cloudbuild.yaml with steps: docker build, docker push. gcloud run deploy. Artifact Registry: store container images. Cloud Deploy: promote across revisions (dev → staging → prod). Traffic splitting: gcloud run services update-traffic myservice --to-revisions=myservice-00001=50,myservice-00002=50. Service mesh: Cloud Run for Anthos (runs on GKE with Istio). Eventarc: event-driven invocations from Pub/Sub, Audit Logs, S3-compatible.</p>'''),
    ],[F("Cloud Run Documentation","https://cloud.google.com/run/docs","Official Cloud Run docs"),F("Google Cloud Skills Boost","https://www.cloudskillsboost.google/","Google Cloud labs")]),
    ("Azure Functions", "azure-functions.html", '''Serverless compute on Azure — triggers, bindings, Durable Functions.''', "Cloud", "fab fa-microsoft", [
        Q("Functions & Triggers", '''<p>Azure Functions: HTTP trigger (GET/POST, auth levels anonymous/function/admin), Timer trigger (CRON — "0 */5 * * * *"), Blob trigger (new blob), Queue trigger (Azure Storage Queue), Event Hub, Cosmos DB, Service Bus. Binding: input/output bindings connect to Azure services declaratively. function.json: { "type": "blob", "direction": "in", "path": "container/{name}" }. Consumption plan: pay-per-execution, scale-to-zero.</p>'''),
        Q("Durable Functions", '''<p>Durable Functions: stateful workflows in serverless. Orchestrator function: [FunctionName("OrderWorkflow")] public async Task<List<string>> RunOrchestrator([OrchestrationTrigger] IDurableOrchestrationContext ctx). Activity functions: single task steps. Patterns: function chaining (sequential steps), fan-out/fan-in (parallel processing), async HTTP APIs (long-running), human interaction (approval workflows). Monitor: durable timer for polling patterns.</p>'''),
    ],[F("Azure Functions Docs","https://learn.microsoft.com/en-us/azure/azure-functions/","Official Azure Functions docs"),F("Durable Functions","https://learn.microsoft.com/en-us/azure/azure-functions/durable/","Durable Functions guide")]),
    ("AWS ECS & Fargate", "aws-ecs-fargate.html", '''Container orchestration on AWS — ECS clusters, services, and Fargate serverless.''', "Cloud", "fab fa-aws", [
        Q("ECS Concepts", '''<p>Amazon ECS: run Docker containers at scale. Launch types: Fargate (serverless — no EC2 management, pay per task), EC2 (manage cluster instances, reserved capacity). Task definition: JSON describing containers (image, port, env vars, memory, CPU, IAM role). Service: maintains desired count of tasks behind ALB/NLB. Scheduling: service scheduler (long-running), daemon scheduler (one per instance), Fargate (automatic placement).</p>'''),
        Q("CI/CD & Service Discovery", '''<p>CI/CD: ECR (container registry), CodeBuild (build image), CodePipeline (deploy to ECS). Blue/green: CodeDeploy shifts traffic between task sets. Service discovery: AWS Cloud Map (DNS-based), Service Connect (envoy sidecar proxy, simplified connectivity). Auto scaling: target tracking (CPU/memory/ALB request count), step scaling, scheduled scaling. Capacity providers: manage scaling between Fargate and Fargate Spot.</p>'''),
    ],[F("Amazon ECS Docs","https://docs.aws.amazon.com/ecs/","Official ECS docs"),F("Fargate Documentation","https://docs.aws.amazon.com/AmazonECS/latest/userguide/what-is-fargate.html","AWS Fargate guide")]),
    ("Azure Kubernetes Service", "azure-kubernetes-service.html", '''Managed Kubernetes on Azure — AKS clusters, node pools, and Azure integration.''', "Cloud", "fab fa-microsoft", [
        Q("AKS Cluster Management", '''<p>AKS: managed Kubernetes — Azure handles control plane (API server, etcd), user manages worker nodes. az aks create --resource-group myRG --name myAKS --node-count 3 --enable-addons monitoring. Node pools: system (critical pods, tainted), user (application workloads). Spot node pools: up to 90% discount, evictable. Cluster autoscaler: automatically scales node pool size. Azure AD integration for Kubernetes RBAC.</p>'''),
        Q("Storage & Networking", '''<p>Azure Disk: ManagedDisk (SSD/HDD, ReadWriteOnce), Azure Files (SMB share, ReadWriteMany). CSI drivers: disk.csi.azure.com, file.csi.azure.com. Networking: Azure CNI (VNet integration, pod IPs from subnet), kubenet (private pod network, NAT). Ingress: Application Gateway Ingress Controller (AGIC), NGINX. Azure Policy: Gatekeeper (OPA) enforce policies (require labels, deny privileged containers). Azure Monitor: Container insights, Prometheus + Grafana.</p>'''),
    ],[F("AKS Documentation","https://learn.microsoft.com/en-us/azure/aks/","Official AKS docs"),F("Azure Architecture Center","https://learn.microsoft.com/en-us/azure/architecture/","Azure best practices")]),
    ("Google Kubernetes Engine", "google-kubernetes-engine.html", '''Managed Kubernetes on Google Cloud — GKE clusters, Workload Identity, and Autopilot.''', "Cloud", "fab fa-google", [
        Q("GKE Modes & Node Management", '''<p>GKE modes: Standard (manage node pools) and Autopilot (Google manages nodes, pay per pod). Node pools: node machine type, disk size/image type. Node auto-repair: health checks + automatic repair. Node auto-upgrade: auto update node version. Workload Identity: GCP service accounts per pod — gke-workload-binding, no static keys. gcloud container clusters create my-cluster --region us-central1 --num-nodes 3.</p>'''),
        Q("GKE Networking & Security", '''<p>VPC-native clusters: alias IP ranges, pod IPs directly on VPC. Dataplane V2: eBPF-based dataplane, improved performance. Cloud NAT: outbound connectivity for private nodes. GKE Sandbox: gVisor container sandbox for untrusted workloads. Binary Authorization: deploy only signed images. Config Connector: manage GCP resources via Kubernetes CRDs. Anthos Service Mesh: managed Istio — mTLS, traffic management, observability.</p>'''),
    ],[F("GKE Documentation","https://cloud.google.com/kubernetes-engine/docs","Official GKE docs"),F("Google Cloud Blog","https://cloud.google.com/blog/products/containers-kubernetes","GKE updates and tutorials")]),

    # === SECURITY ADVANCED (10) ===
    ("Zero Trust Architecture", "zero-trust-architecture.html", '''Security model: never trust, always verify — micro-segmentation, IAM, and continuous monitoring.''', "Security", "fas fa-shield-virus", [
        Q("Core Principles", '''<p>Zero Trust: no implicit trust based on network location. Verify explicitly (authenticate + authorize every request), least privilege (JIT/JEA — just-in-time, just-enough-access), assume breach (segment access, encrypt all, monitor continuously). BeyondCorp (Google): device + user identity determine access, not network. CISA ZT Maturity Model: traditional → advanced → optimal. NIST SP 800-207: Zero Trust Architecture guidelines.</p>'''),
        Q("Micro-Segmentation & SDP", '''<p>Micro-segmentation: granular firewall rules per workload — east-west traffic control. NSX/Tanzu: distributed firewall, application security groups. Illumio: adaptive segmentation based on application dependencies. SDP (Software-Defined Perimeter): dark cloud — no DNS, no open ports. Before connection: device posture check + user auth + application-level tunnel. MFA enforced at every access attempt. Continuous monitoring: user behavior analytics (UEBA).</p>'''),
    ],[F("NIST SP 800-207","https://www.nist.gov/publications/zero-trust-architecture","NIST Zero Trust document"),F("BeyondCorp","https://cloud.google.com/beyondcorp","Google BeyondCorp framework")]),
    ("IAM & Identity Management", "iam-identity-management.html", '''Identity and access management — SSO, SAML, OAuth 2.0, OIDC, and just-in-time access.''', "Security", "fas fa-key", [
        Q("IAM Fundamentals", '''<p>IAM: who can do what on which resource. Authentication (who you are) vs Authorization (what you can do). Federation: SSO across orgs — SAML 2.0 (XML-based, enterprise) vs OAuth 2.0 + OIDC (token-based, modern apps). SAML flow: IdP (identity provider) sends signed assertion to SP (service provider). OIDC: ID token (JWT) + access token + refresh token. /authorize → /token → /userinfo endpoints.</p>'''),
        Q("Just-in-Time Access", '''<p>JIT: temporary privilege elevation on demand. Okta: JIT group membership, approval workflows. Azure AD PIM: Privileged Identity Management — activation request, timebound, approval, audit. AWS IAM: role-based, Security Token Service (STS) for temporary credentials. Google Cloud: Privileged Access Manager (PAM), Temporal Access for service accounts. Tools: Teleport (SSO + SSH/K8s proxy), Boundary (HashiCorp session management).</p>'''),
    ],[F("OAuth 2.0 Spec","https://oauth.net/2/","OAuth 2.0 framework"),F("Okta IAM Guide","https://developer.okta.com/docs/guides/","Okta developer documentation")]),
    ("PKI & Certificate Management", "pki-certificate-management.html", '''Public Key Infrastructure — CA, certificates, ACME, cert-manager, and mTLS.''', "Security", "fas fa-certificate", [
        Q("PKI Components", '''<p>PKI (Public Key Infrastructure): Certificate Authority (CA — signs certificates), Registration Authority (RA — verifies identity), Certificate Revocation List (CRL — revoked certs), OCSP (online status check). X.509 certificate fields: subject, issuer, validity, public key, key usage (digitalSignature, keyEncipherment), SAN (Subject Alternative Name — DNS names, IPs). Certificate chain: root CA → intermediate CA → leaf cert.</p>'''),
        Q("ACME & cert-manager", '''<p>ACME protocol: automated certificate enrollment. Let's Encrypt: free 90-day certificates, automated renewal. certbot: certbot --nginx -d example.com. cert-manager (Kubernetes): Issuer (namespace-scoped), ClusterIssuer (cluster-wide). Certificate CRD: spec.dnsNames, secretName, issuerRef. mTLS: client sends certificate too — mutual authentication. Istio/Envoy: auto mTLS for service mesh. SPIFFE: workload identity via X.509 SVIDs.</p>'''),
    ],[F("Let's Encrypt Docs","https://letsencrypt.org/docs/","Free automated certificate authority"),F("cert-manager Docs","https://cert-manager.io/docs/","Kubernetes certificate manager")]),
    ("SIEM & SOAR", "siem-soar.html", '''Security information and event management — SIEM correlation, SOAR automation, and incident response.''', "Security", "fas fa-chart-line", [
        Q("SIEM Architecture", '''<p>SIEM collects, normalizes, and correlates security logs. Data sources: Windows Event Log (via WinRM/WEC), syslog (Linux — auth.log, syslog), cloud (CloudTrail, GuardDuty, Azure Monitor), network (Zeek, Suricata, firewall). Correlation rules: "10 failed logins in 5 minutes from same IP → alert". Popular SIEMs: Splunk ES (enterprise), Elastic Security (open), Wazuh (open), Azure Sentinel (cloud SIEM + SOAR).</p>'''),
        Q("SOAR Playbooks", '''<p>SOAR automates incident response. Playbooks: trigger → action → decision → response. Example playbook: Phishing email reported → auto-extract URLs → scan with VirusTotal → block on firewall if malicious → notify SOC. Tools: Splunk SOAR (Phantom), Palo Alto Cortex XSOAR, TheHive (open, case management). Metrics: MTTR (mean time to respond), false positive reduction, automation rate (manual vs automated actions).</p>'''),
    ],[F("Wazuh Documentation","https://documentation.wazuh.com/","Open source SIEM"),F("Splunk ES","https://www.splunk.com/en_us/software/siem.html","Splunk Enterprise Security")]),
    ("Honeypots & Deception", "honeypots-deception-tech.html", '''Deception technology — honeypots, honeytokens, and threat intelligence gathering.''', "Security", "fas fa-jar", [
        Q("Honeypot Types", '''<p>Honeypots: decoy systems appearing as legitimate targets. Low-interaction: simulated services (SSH, HTTP) — Dionaea, Cowrie (SSH/telnet). Medium-interaction: more realistic services with limited shell. High-interaction: real OS/application, fully monitored. Honeynet: network of honeypots. Honeytokens: fake credentials, files, API keys. Canary tokens: unique URLs/emails/API keys that alert when used.</p>'''),
        Q("Deployment & Analysis", '''<p>Deploy: T-Pot (multi-honeypot platform, Docker-based), MHN (Modern Honey Network — management, sensor deployment). Place: DMZ, inside network (detect lateral movement), cloud (detect cloud scanning). Analysis: log all attacker activity (keystrokes, commands, file downloads), identify TTPs (MITRE ATT&CK mapping), gather IoCs (IPs, malware hashes, domains). Legal: ensure honey systems don't entrap — clearly separate from production.</p>'''),
    ],[F("T-Pot Honeypot","https://github.com/telekom-security/tpotce","Multi-honeypot platform"),F("CanaryTokens","https://canarytokens.org/","Free honeytoken generator")]),
    ("Wi-Fi Penetration Testing", "wifi-pentesting.html", '''Assess wireless security — WPA2/WPA3 cracking, evil twin, and deauthentication attacks.''', "Security", "fas fa-wifi", [
        Q("Wi-Fi Security Assessment", '''<p>Wi-Fi pentesting: assess WPA2/WPA3/Enterprise networks. Tools: aircrack-ng (packet capture, injection), aireplay-ng (deauth, ARP replay), airodump-ng (scan, capture handshake), airmon-ng (monitor mode). Capture WPA2 handshake: airodump-ng -c <channel> --bssid <AP> -w capture wlan0mon, deauth client to force reconnection. Crack: aircrack-ng -w wordlist.txt capture-01.cap or hashcat (GPU accelerated).</p>'''),
        Q("Enterprise & WPA3", '''<p>WPA2-Enterprise: RADIUS server (FreeRADIUS), EAP methods (PEAP, TTLS, TLS). Attack: hostapd-wpe — fake RADIUS, capture MSCHAPv2 challenge/response, crack with asleap. WPA3: SAE (Simultaneous Authentication of Equals) handshake — resistant to dictionary attacks, but still vulnerable to downgrade attacks (downgrade to WPA2). PMKID attack: capture PMKID from AP beacon without client. EAPHammer: targeted EAP attacks.</p>'''),
    ],[F("Aircrack-ng Documentation","https://www.aircrack-ng.org/doku.php","Wireless security tools"),F("Wifi-Pumpkin","https://github.com/P0cL4bs/WiFi-Pumpkin","Wi-Fi pentesting framework")]),
    ("Web Application Firewall", "web-application-firewall.html", '''WAF configuration — ModSecurity, Cloudflare WAF, rate limiting, and rule tuning.''', "Security", "fas fa-fire", [
        Q("WAF Fundamentals", '''<p>WAF filters HTTP traffic between client and web server. Detection: signature-based (known attack patterns), anomaly-based (ML, baseline deviation), rule-based (custom rules — IP, URL, header, body). Rule engines: ModSecurity (open source), OWASP CRS (Core Rule Set — SQLi, XSS, LFI, RCE). CRS paranoia levels: 1 (low false positives) to 4 (high security, high false positives).</p>'''),
        Q("Cloud WAF & Tuning", '''<p>Cloud WAF: Cloudflare WAF (managed rulesets — OWASP, Cloudflare Managed), AWS WAF (ACL rules — rate-based, IP match, regex), Azure WAF (Front Door/Application Gateway), Google Cloud Armor (pre-configured rules, geoblocking). Tuning: start in log mode, review false positives, create exception rules (allow trusted IPs/user-agents), whitelist/blacklist specific URIs, adjust CRS paranoia level. Rule profiling: analyze blocked requests monthly.</p>'''),
    ],[F("OWASP CRS","https://coreruleset.org/","OWASP Core Rule Set"),F("ModSecurity Reference","https://github.com/SpiderLabs/ModSecurity/wiki","ModSecurity wiki and reference")]),
    ("Hardware Security Module", "hardware-security-module.html", '''HSM for cryptographic key management — PKCS#11, AWS CloudHSM, and key ceremonies.''', "Security", "fas fa-microchip", [
        Q("HSM Concepts", '''<p>HSM (Hardware Security Module): tamper-resistant hardware for cryptographic operations. Keys generated inside HSM — never leave in plaintext. Standards: FIPS 140-2/140-3 Level 2-4 (security certification), PKCS#11 (Cryptoki API — open standard for HSM access). Operations: key generation (RSA, ECC, AES), signing (code signing, document signing), encryption/decryption, key wrapping, true random number generation (TRNG).</p>'''),
        Q("Cloud HSM & Key Ceremonies", '''<p>Cloud HSM: AWS CloudHSM (dedicated HSM, VPC), AWS KMS (managed, automatic key rotation), Azure Key Vault (HSM-backed, BYOK), Google Cloud HSM (Cloud KMS with FIPS 140-2 Level 3). Key ceremonies: process for creating master keys — multi-person authorization (m of n), crypto officer + crypto user roles, tamper-evident seals, video recording, paper audit trail. PKCS#11 CLI: pkcs11-tool --module libcloudhsm.so --login --list-objects.</p>'''),
    ],[F("AWS CloudHSM Docs","https://docs.aws.amazon.com/cloudhsm/","AWS CloudHSM documentation"),F("PKCS#11 Standard","https://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/","PKCS#11 standard")]),
    ("OSINT Deep Dive", "osint-deep-dive.html", '''Advanced open-source intelligence techniques — passive reconnaissance, tools, and automation.''', "Security", "fas fa-search", [
        Q("Passive Reconnaissance", '''<p>OSINT gathers information from public sources without contacting the target. Passive recon: search engines (Google dorks — site:example.com intitle:"login"), Shodan (internet-connected devices — port, service, banner), Censys (certificates, services), Have I Been Pwned (breached accounts), DNS records (dig, nslookup, dnsrecon), WHOIS (domain registration details). Subdomain enumeration: crt.sh (certificate transparency logs), sublist3r, amass.</p>'''),
        Q("Social & Automation", '''<p>Social OSINT: Sherlock (username search across 400+ platforms), theHarvester (email, vhost discovery), SpiderFoot (automated OSINT — 200+ modules, correlation). Geolocation: EXIF data extraction (exiftool), Google Maps geocoding, street view analysis. Automation: SpiderFoot HX (web UI + scan schedules), recon-ng (framework with workspaces, modules). Maltego (graph-based link analysis — transforms show relationships).</p>'''),
    ],[F("OSINT Framework","https://osintframework.com/","OSINT tool tree"),F("SpiderFoot","https://www.spiderfoot.net/","Automated OSINT tool")]),
    ("Dark Web & Anonymity", "dark-web-anonymity.html", '''Dark web — Tor, I2P, Onion services, and anonymity best practices.''', "Security", "fas fa-mask", [
        Q("The Onion Router", '''<p>Tor: onion routing — three layers of encryption (guard, middle, exit). Entry guard: known to you, changes periodically. Middle relay: encrypted tunnel. Exit relay: decrypts final layer, makes request. Onion services (formerly hidden services): .onion addresses — no exit node, end-to-end encrypted. v3 onions: 56-char address, improved encryption (ED25519 + SHA3). Tor Browser: hardened Firefox — noUnique, letterboxing, HTTPS-only.</p>'''),
        Q("I2P & Anonymity Hygiene", '''<p>I2P (Invisible Internet Project): garlic routing — multiple messages bundled (garlic cloves). Destination-based addressing: .i2p base32 addresses. Native I2P apps: BitTorrent (I2PSnark), email (Susimail), IRC, web hosting. Anonymity hygiene: never log into personal accounts from Tor, disable JavaScript (or use NoScript), avoid browser fingerprinting (use Tor Browser defaults, no extensions), compartmentalize identities. Threat model: decide what/who you're hiding from.</p>'''),
    ],[F("Tor Project","https://www.torproject.org/docs/","Tor documentation"),F("I2P Documentation","https://geti2p.net/en/docs","I2P documentation")]),
]

# Generate all tutorials
for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials!")
