#!/usr/bin/env python3
"""Generate tutorials for piracy and survival 'Learn more' tiles that don't exist yet."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === PIRACY GUIDES (12) ===
    ("Safe Piracy & VPN Guide", "safe-piracy.html",
     '''Stay safe while pirating — VPNs, opsec, malware scanning, and legal awareness.''',
     "Piracy", "fas fa-shield-alt", [
        Q("VPN Essentials", '''<p>A VPN encrypts all traffic and hides your IP address. Essential for torrenting: your IP is visible to everyone in the swarm. Choose a no-log VPN: Mullvad (anonymous, €5/mo), ProtonVPN (free tier, Swiss), AirVPN (port forwarding for private trackers), IVPN (audited no-log). Kill switch: bind your torrent client to the VPN interface (qBittorrent: Settings > Advanced > Network Interface) — if the VPN drops, your traffic stops.</p>'''),
        Q("Operational Security", '''<p>Opsec: use a separate browser profile for piracy (Firefox Multi-Account Containers), enable uBlock Origin (block malware ads), don't log into personal accounts, use a fake email for forum registrations, avoid clicking "download" buttons on shady sites — use JDownloader2 instead. Scan every downloaded .exe/.msi on VirusTotal before running. Real-Debrid: cached torrents stream from their servers, your IP never hits the swarm.</p>'''),
        Q("Legal Awareness", '''<p>Laws vary by country: US (DMCA notices, ISP forwarding, possible lawsuits), Germany (strict enforcement, heavy fines), Netherlands (tolerated for personal use), Canada (notice-and-notice system), UK (blocks pirate sites, VPN required). DMCA notices: ISPs forward them, most ignore after first few. Threat: copyright trolls who sue for settlement. Defense: don't seed indefinitely, use a blocklist, bind VPN to client always, never admit guilt.</p>'''),
    ],[F("That One Privacy Site","https://thatoneprivacysite.net/","VPN comparison charts"),F("r/Piracy Megathread","https://www.reddit.com/r/Piracy/wiki/megathread/","Community piracy wiki")]),
    ("Streaming Sites Guide", "streaming-sites-guide.html",
     '''Find working streaming sites for movies and TV — safe links, ad blocking, and troubleshooting.''',
     "Piracy", "fas fa-film", [
        Q("Finding Working Sites", '''<p>Streaming sites get taken down regularly. Current working options: Hurawatch, Fmovies (mirrors), Sflix, Lookmovie, MoviesJoy, 123movies (mirrors), Soap2day (many mirrors via Google). Best source: FMHY (fmhy.net/videopiracyguide) — updated constantly. Always use uBlock Origin! Many sites have fake "play" buttons that lead to malware. Use keyboard shortcut Ctrl+Click to open in new tab if unsure.</p>'''),
        Q("Stremio + Torrentio", '''<p>Stremio with Torrentio addon: install Stremio desktop app, add Torrentio addon (configure quality filters, provider list), and browse content in a Netflix-like interface. For best experience: add Real-Debrid integration to Torrentio — streams from cached premium servers, no buffering, no VPN needed for streaming (your IP never directly contacts peers). Available on Windows, macOS, Linux, Android, iOS.</p>'''),
        Q("Troubleshooting Buffering", '''<p>Buffering fixes: lower quality to 720p/480p, use a wired connection (Ethernet), enable hardware acceleration in browser, try a different site (some have better CDN), use Stremio + Real-Debrid for 4K direct streams. If a site is down: check fmhy.net for active alternatives, search Reddit (r/FREEMEDIAHECKYEAH), or use the site's .to/.sx/.art mirror variant.</p>'''),
    ],[F("FMHY Video","https://fmhy.net/videopiracyguide","Curated streaming site list"),F("Stremio","https://www.stremio.com/","Media center app")]),
    ("Music Piracy Guide", "music-piracy-guide.html",
     '''Download and stream music — Spotify tools, FLAC downloads, and P2P music clients.''',
     "Piracy", "fas fa-headphones", [
        Q("Spotify Tools", '''<p>Free Spotify Premium: BlockTheSpot (Windows — blocks ads, unlocks skip), SpotX (same, open-source), Spicetify (themes + extensions). Song downloaders: Spotube (open-source, downloads from YouTube as fallback), Soggfy (Spotify downloader), Lucida (download from Spotify, Apple Music, Deezer, Tidal in original quality). Use Deemix for FLAC downloads from Deezer (highest quality, ~1000kbps).</p>'''),
        Q("Downloading Music", '''<p>Soulseek: P2P music client with massive library — search by artist, album, bitrate, format. Nicotine+ is a modern Soulseek client (cross-platform). Lucida: downloads from multiple services — supports Spotify, Apple Music, Deezer, Tidal. Deemix: Deezer downloader — FLAC (lossless), MP3 320kbps. Sliderkz: download from YouTube as MP3 (good for rare tracks). Orpheus: private tracker for FLAC music.</p>'''),
        Q("Music Identification", '''<p>Identify songs: Shazam (mobile), AHA Music (browser extension, identifies from any tab). Audiotaggers: MusicBrainz Picard (auto-tag from acoustic fingerprint), MP3tag (bulk tag editor), Kid3. Organize: Lidarr (Sonarr for music — auto-download, organize, rename). Subsonic/Navidrome: self-hosted music streaming server (like Plex for music).</p>'''),
    ],[F("Soulseek","https://www.slsknet.org/","P2P music sharing client"),F("Deemix","https://deemix.app/","Deezer music downloader")]),
    ("Direct Download Guide", "direct-download-guide.html",
     '''Download files directly (no torrenting) — DDL sites, JDownloader2, and debrid services.''',
     "Piracy", "fas fa-download", [
        Q("DDL Sites", '''<p>Direct Download (DDL) sites host files on cloud storage (MEGA, MediaFire, Zippyshare successors, Google Drive, 1fichier). Popular DDL sites: FileCR (software + games), DDoSecrets (data leaks), Archive.org (old software, abandonware), Rezi (movies, TV), WAREZ (software, games). DDL pros: no seeding required, no IP exposure, faster downloads with premium host accounts.</p>'''),
        Q("JDownloader2 Mastery", '''<p>JDownloader2: automatic download manager for DDL sites. Features: clipboard monitoring (copy link → auto-add), automatic captcha solving (via 9kw or manual), batch downloading (entire folders), premium host support (Real-Debrid, AllDebrid), link extraction (scrape pages for all downloadable links), scheduling, extraction (auto-unzip). Install: jdownloader.org — available for Windows, macOS, Linux.</p>'''),
        Q("Debrid Services", '''<p>Debrid services provide premium access to file hosts and cached torrents. Real-Debrid (most popular — €3/mo, cached torrents + premium DDL), AllDebrid (€3/mo, similar), Premiumize (€4/mo, VPN included). Benefits: direct download at max speed, no waiting, multi-host access (100+ hosts). Real-Debrid + Stremio: stream cached torrents instantly in Netflix-like UI. No VPN needed for cached torrents (IP masked by debrid server).</p>'''),
    ],[F("JDownloader","https://jdownloader.org/","Cross-platform download manager"),F("Real-Debrid","https://real-debrid.com/","Premium host and torrent caching")]),
    ("Torrenting Guide", "torrenting-guide.html",
     '''Torrent safely — clients, sites, private trackers, port forwarding, and ratio management.''',
     "Piracy", "fas fa-magnet", [
        Q("Clients & Setup", '''<p>Torrent clients: qBittorrent (best — free, no ads, full features), Transmission (Linux, lightweight), Deluge (customizable). Avoid: uTorrent (bundled malware, ads). Essential setup: bind VPN interface (Settings > Advanced > Network Interface), enable encryption (Settings > BitTorrent > Encryption mode: Required), limit upload speed (leave 20% bandwidth free), set download location, enable sequential download for streaming.</p>'''),
        Q("Public vs Private Trackers", '''<p>Public trackers (The Pirate Bay, 1337x, RuTracker, Nyaa): easy access, no account needed, but leechers may not seed and DMCA monitoring is common. Always use a VPN. Private trackers (TorrentLeech, IPTorrents, Filelist, RED, MAM, GGn): invite-only, require ratio (upload/download), better speeds (seedboxes), rare content, no DMCA. Build ratio: cross-seed (download freeleech torrents, seed to multiple trackers), use seedboxes (feralhosting, ultra.cc).</p>'''),
        Q("Ratio & Seeding", '''<p>Private tracker ratio: maintain minimum ratio (usually 1.0) or risk getting banned. Strategies: download freeleech torrents (don't count against download), seed everything for as long as possible, use a seedbox (10Gbps+ upload), auto-cross-seed across trackers. Tools: qBittorrent auto-seed, autobrr (IRC announce snatcher), cross-seed (find same torrents on other trackers). RSS: set up autodl-irssi or autobrr for new releases.</p>'''),
    ],[F("qBittorrent","https://www.qbittorrent.org/","Open-source torrent client"),F("r/trackers","https://www.reddit.com/r/trackers/","Private tracker community")]),
    ("Gaming Piracy Guide", "gaming-piracy-guide.html",
     '''Download games — repacks, DLC unlockers, emulators, and ROMs.''',
     "Piracy", "fas fa-gamepad", [
        Q("Game Download Sites", '''<p>FitGirl Repacks: most popular — highly compressed installers (50-80% smaller), reliable, pre-cracked. DODI Repacks: similar to FitGirl, alternative selection. SteamRIP: Steam games unpacked from Steam files (no crack needed for some). GOG-games: DRM-free GOG releases. Online-Fix: cracked multiplayer for popular games. ElAmigos: clean, uncompressed releases. CS.RIN.RU: forum with game releases, updates, DLC unlocks.</p>'''),
        Q("Emulators & ROMs", '''<p>Emulators: RetroArch (all systems), Ryujinx/Yuzu (Switch), RPCS3 (PS3), Xenia (Xbox 360), PCSX2 (PS2), DuckStation (PS1), Citra (3DS — development stopped but works), mGBA (GBA), PPSSPP (PSP). ROMs: Vimm's Lair (safe, curated), CDRomance (retro), Edge Emulation (direct play in browser), Nyaa (for Switch games), Internet Archive (abandonware, ROM sets). BIOS files are legally required for PS1/PS2 emulation.</p>'''),
        Q("DLC Unlockers & Tools", '''<p>Steam DLC unlockers: CreamAPI (add DLC entries to Steam emulator), ScreamAPI (for Epic Games), Steam-Account-Manager (manage alt accounts). Goldberg Emulator: bypass Steam for LAN/online play with friends (supports Steamworks). Koalageddon: Universal DLC unlocker for Steam, Epic, Origin. Tools: Steamless (unpack SteamStub DRM), rePACK by ElAmigos. FitGirl repacks include all DLC and updates pre-installed.</p>'''),
    ],[F("FitGirl Repacks","https://fitgirl-repacks.site/","Compressed game repacks"),F("CS.RIN.RU","https://cs.rin.ru/forum/","Game piracy forum")]),
    ("Ebook & Audiobook Piracy", "ebook-piracy-guide.html",
     '''Download books, audiobooks, comics, and academic texts — sources, tools, and organization.''',
     "Piracy", "fas fa-book-open", [
        Q("Ebook Sources", '''<p>Anna's Archive: meta-search engine across LibGen, Z-Library, Sci-Hub — single search for books, papers, comics. Z-Library: via Tor (z-lib.io) or clearweb mirrors — massive collection of fiction and non-fiction. Library Genesis (LibGen): mirrors via .gs, .rs, .st domains — textbooks, fiction, scientific. Mobilism: forum with curated ebook releases. MyAnonaMouse: private tracker dedicated to books (best quality, requires interview).</p>'''),
        Q("Audiobooks & Comics", '''<p>Audiobooks: AudiobookBay (largest public tracker), MyAnonaMouse (high quality), LibriVox (free public domain audiobooks), XePlayer (bypasses Audible). Comics: GetComics (DDL, well-organized), ReadComicsOnline (web reader), Nyaa (.si for manga), Comixology downloads (DeDRM with Calibre plugin). Manga: MangaDex (reader), Batoto, Nyaa for batch downloads.</p>'''),
        Q("Tools & Organization", '''<p>Calibre: ebook library manager — convert between formats (EPUB, MOBI, PDF, AZW3), edit metadata, auto-download covers, send to Kindle. DeDRM tools: Calibre plugin to remove DRM from Kindle/Adobe EPUB purchases. Organize: Readarr (Sonarr for books — auto-download, organize). Readers: Kindle (ecosystem), Kobo (open format support), Moon+ Reader (Android), FBReader (cross-platform), Thorium Reader (EPUB).</p>'''),
    ],[F("Anna's Archive","https://annas-archive.org/","Meta-search for books and papers"),F("Calibre","https://calibre-ebook.com/","Ebook management software")]),
    ("Software Piracy Guide", "software-piracy-guide.html",
     '''Download cracked software — sources, activation tools, and safety checks.''',
     "Piracy", "fas fa-cog", [
        Q("Software Download Sites", '''<p>Reliable software sites: FileCR (extensive collection, verified), GetIntoPC (clean downloads), LRepacks (Russian repacker, good quality), Nsane Forums (activators, cracks), AyuCollection (design software), Rutracker (Russian tracker — massive software library). Always check comments and uploader reputation. Avoid "pre-activated" software from unknown sources — they often bundle malware.</p>'''),
        Q("Windows & Office Activation", '''<p>MAS (Microsoft Activation Scripts): open-source, HWID (permanent digital license for Windows 10/11), Ohook (for Office), KMS38 (activate until 2038). Safe, audited by the community. KMS_VL_ALL: alternative KMS activator for VL editions. Microsoft Toolkit: older but still works for Office 2010-2021. Use PowerShell: irm https://get.activated.win | iex (official MAS script). Always verify the checksum.</p>'''),
        Q("Adobe & Creative Software", '''<p>Adobe: Monkrus repacks (most popular — pre-cracked, Russian), Adobe CC cracker (genuine installer + crack). Guide: PainteR's Adobe Guide on cs.rin.ru. Alternatives (free): GIMP (Photoshop), Inkscape (Illustrator), Krita (painting), DaVinci Resolve (Premiere), Blender (3D/Maya), Audacity (audio), Darktable (Lightroom). Anti-virus false positives: cracks/keygens trigger AV — temporarily disable real-time protection during installation, then re-enable.</p>'''),
    ],[F("MAS (Microsoft Activation)","https://massgrave.dev/","Open-source Windows/Office activator"),F("FileCR","https://filecr.com/","Software and games download site")]),
    ("Anime & Cartoon Piracy", "anime-piracy-guide.html",
     '''Stream and download anime, cartoons, and animated content — sites, torrents, and subtitles.''',
     "Piracy", "fas fa-dragon", [
        Q("Anime Streaming", '''<p>Current streaming sites: Aniwave (best UI, fastest updates), Zoro.to (large library), 9anime (mirrors — .to, .id, .me), AnimePahe (compressed downloads), GoGoAnime (old reliable), Marin.moe (direct downloads, highest quality). Use uBlock Origin — anime sites have aggressive popup ads. For mobile: Saikou (Android app, aggregates multiple sources), Aniyomi (Anime + manga reader, extension-based).</p>'''),
        Q("Anime Torrenting", '''<p>Best quality comes from fansub groups on Nyaa.si (the essential anime tracker — .si domain). Quality levels: 720p x265 (small files, good quality — 200-300MB per episode), 1080p x265 (best quality/size ratio), 1080p x264 (maximum compatibility). Recommended groups: SubsPlease (720p/1080p batches, consistent quality), Erai-Raws, Judas, AnimeTime. SubsPlease batches are release-date-ordered and properly named — ideal for Sonarr/Radarr.</p>'''),
        Q("Subtitle Management", '''<p>Subtitle sources: kitsunekko.net (large subtitle archive), AB-Subscene, Anime Subtitles (GitHub). Automation: Bazarr (auto-download subtitles for Sonarr/Radarr library), supports multiple languages. Fansub vs official: fansubs often have better translation notes, official subs are licensed and removed. Dual audio: many releases include Japanese + English audio. Tools: MKVToolNix (remux MKV audio/subtitle tracks), ffmpeg (extract/convert subs).</p>'''),
    ],[F("Nyaa.si","https://nyaa.si/","Largest anime torrent tracker"),F("AniWave","https://aniwave.to/","Anime streaming site")]),
    ("Android Piracy Guide", "android-piracy-guide.html",
     '''Modded apps, cracked games, and tools for Android — safety and best sources.''',
     "Piracy", "fab fa-android", [
        Q("Modded Apps", '''<p>Best sources: Mobilism (forum with modded apps and games — check comments), LiteApks (modded/patched APKs), Sbenny (gaming + apps), HappyMod (modded APK marketplace), APKHome (clean APKs). YouTube mods: ReVanced (no ads, background play, download — use ReVanced Manager, patch official APK), NewPipe (privacy-focused YouTube frontend, no Google account needed). Instagram mods: MyInsta, Instander, AeroInsta.</p>'''),
        Q("Cracked Games & Emulators", '''<p>Game sources: Mobilism Games section, PlatinMods, AndroPalace, 4PDA (Russian forum). Emulators: Yuzu (Switch — runs on powerful Snapdragon 8 Gen 2+ devices), AetherSX2 (PS2 development stopped but last version works), Citra (3DS), PPSSPP (PSP — excellent, runs on most devices), Dolphin (GameCube/Wii), DuckStation (PS1). BIOS files: legally required for some emulators, available on archive.org.</p>'''),
        Q("App Stores & Tools", '''<p>F-Droid: FOSS app store, no tracking, auto-updates. Aurora Store: anonymous Google Play client — download apps without Google account, spoof device info. APKMirror: safe APK downloads (verified signatures). Obtainium: auto-update apps from GitHub releases. Lucky Patcher: remove ads, bypass license verification, modify app permissions. Shizuku: grant ADB-level permissions without root — used by Hail (freeze/uninstall system apps).</p>'''),
    ],[F("Mobilism","https://forum.mobilism.org/","Modded apps and games forum"),F("ReVanced","https://revanced.app/","YouTube mod without ads")]),
    ("iOS Piracy Guide", "ios-piracy-guide.html",
     '''Sideload apps, music, and content on iOS — AltStore, TrollStore, and jailbreaking.''',
     "Piracy", "fab fa-apple", [
        Q("AltStore & Sideloading", '''<p>AltStore: sideload IPA files without jailbreaking. Install AltServer on desktop (Windows/macOS), connect iPhone via USB, AltStore installs as a development app. Sideload up to 3 apps (free Apple ID) or 10 with paid developer account ($99/yr). Popular IPAs: uYouPlus (no-ads YouTube), Delta (multi-system emulator), iTorrent, Spotify++, Instagram++. Sources: AltStore repos add third-party app catalogs.</p>'''),
        Q("TrollStore & Jailbreaking", '''<p>TrollStore: permanent app signing via CoreTrust bug (iOS 14-16.6.1). Install IPAs forever without re-signing, no Apple ID needed. Jailbreaking: Dopamine (iOS 15-16.5, arm64e — rootless, semi-untethered), Palera1n (iOS 15-17, checkm8 devices — iPhone X and older). Cydia/Sileo package managers — tweaks mod the system UI, add features. Warning: jailbreaking reduces security, can brick if done incorrectly.</p>'''),
        Q("Music & Media", '''<p>Spotify mods: Spotilife (free Premium via jailbreak/TrollStore), SpotiC++ (no ads, unlimited skips). YouTube: uYouPlus (AltStore — combines YouTube++, iSponsorBlock, YTABConfig). Torrents: iTorrent (iOS torrent client). VLC for iOS: play downloaded media files. Files app: download and manage files locally. iCloud bypass: tools like iRemove, Checkm8-based for old devices — beware of scams. Always check subreddits for current working methods.</p>'''),
    ],[F("AltStore","https://altstore.io/","iOS sideloading app store"),F("r/sideloaded","https://www.reddit.com/r/sideloaded/","iOS sideloading community")]),
    ("Media Server Automation", "media-server-piracy.html",
     '''Automate your media library — Sonarr, Radarr, Lidarr, Readarr, and Prowlarr setup.''',
     "Piracy", "fas fa-server", [
        Q("The *Arr Stack", '''<p>The *Arr stack automates media downloading and organization. Sonarr (TV shows — search, download, organize, rename), Radarr (movies — same as Sonarr for films), Lidarr (music), Readarr (books), Bazarr (subtitles), Prowlarr (indexer manager — syncs to all *Arrs). Installation: Docker-compose is easiest — linuxserver.io maintains all *Arr images. Each app has a web UI on a different port (e.g., :8989 for Sonarr).</p>'''),
        Q("Configuration Guide", '''<p>Setup flow: 1) Install Docker + docker-compose, 2) Create media directory structure (/data/tv, /data/movies, /data/music, /data/books), 3) Deploy *Arrs with docker-compose, 4) Add indexers in Prowlarr (public + private trackers), 5) Connect indexers to Sonarr/Radarr/etc, 6) Add download client (qBittorrent, SABnzbd), 7) Configure quality profiles (1080p Bluray, 4K Remux), 8) Add shows/movies to monitor. Optional: set up Usenet (NZBGet/SABnzbd + NZBGeek) as alternative to torrents.</p>'''),
        Q("Hardware & Remote Access", '''<p>Hardware: Intel QuickSync (8th gen+ for hardware transcoding), NVIDIA GPU (for Plex transcoding), or a cheap mini PC (Beelink, Intel NUC) with large HDDs (12TB+). Remote access: Tailscale (wireguard mesh — secure, no port forwarding), Cloudflare Tunnel (reverse proxy + WAF), Nginx Proxy Manager (SSL, domain). Overseerr/Jellyseerr: request management — users request media, you approve, automation downloads it. Ombi: alternative request system.</p>'''),
    ],[F("Sonarr","https://sonarr.tv/","TV show automation"),F("Radarr","https://radarr.video/","Movie automation")]),

    # === SURVIVAL GUIDES (16) ===
    ("Emergency USB Toolkit", "emergency-usb.html",
     '''Build a multi-boot emergency USB drive for system rescue, diagnostics, and recovery.''',
     "Survival", "fas fa-suitcase-medical", [
        Q("Choosing Your USB", '''<p>USB 3.0+ 64GB+ drive recommended. Brands: SanDisk, Samsung, Kingston durable models. Label and store in a safe place. Ventoy is the best tool: install once, then simply drop .iso files onto the drive. Boot order: set USB first in BIOS (F2/F12/Del on boot). UEFI vs Legacy: most modern systems use UEFI — ensure your rescue ISOs support it. Secure Boot: disable in BIOS if some tools won't boot.</p>'''),
        Q("Essential Rescue ISOs", '''<p>Essential ISOs for your emergency USB: Hiren's Boot CD PE (Windows PE with tools), SystemRescue (Linux rescue environment), Ubuntu Desktop/Mint (full Linux desktop), GParted Live (partition management), Memtest86+ (RAM testing), Clonezilla (disk imaging). Boot all ISOs at least once at home — nothing worse than a non-booting USB in an emergency. Update ISOs every 6 months (distros release security patches).</p>'''),
        Q("Portable Apps to Include", '''<p>In addition to ISOs, keep portable app packages: antivirus (Malwarebytes, Emsisoft Emergency Kit), data recovery (Recuva, TestDisk/PhotoRec), password tools (chntpw, Ophcrack), network tools (Wireshark portable, PuTTY, FileZilla), browsers (Firefox Portable with extensions), encryption (VeraCrypt Portable). Organize in folders on the drive's remaining space. Create a README.txt with tool descriptions and instructions.</p>'''),
    ],[F("Ventoy","https://www.ventoy.net/","Multi-boot USB tool"),F("Hiren's Boot CD","https://www.hirensbootcd.org/","Windows PE rescue environment")]),
    ("Emergency Prep Checklist", "emergency-prep-checklist.html",
     '''A step-by-step checklist to prepare your digital life for emergencies — before disaster strikes.''',
     "Survival", "fas fa-list-check", [
        Q("Digital Prep Checklist", '''<p>Monthly: backup critical files (cloud + local), update emergency USB ISOs, test VPN connection, verify backups are restorable. Quarterly: update password manager vault, review 2FA recovery codes, check emergency contacts in Bitwarden/LastPass, test system restore points. Annually: replace aging USB drives (they wear out), update Kiwix ZIM archives, review digital will/emergency access setup, practice restoring from backup.</p>'''),
        Q("Physical Prep", '''<p>Print and store in a fireproof safe: 2FA recovery codes for every account, password manager master password, bank helpline numbers, insurance policy details, VPN provider credentials, emergency contact list. USB drives: two copies — one in your bag (daily carry), one in a safe (home). Encrypt with VeraCrypt (container or full disk). Label everything clearly — "EMERGENCY USB — [DATE]" with a list of contents on the label.</p>'''),
        Q("Communication Plan", '''<p>Emergency communication: agree on a family communication tree (who calls whom), set up a Signal group chat for urgent notifications, share location via Google Maps/Signal, keep a prepaid phone for emergencies (always charged). Offline comms: install Briar (Bluetooth mesh), set up Meshtastic nodes if available, learn basic HAM radio (technician license is easy to obtain). Dead drop: agreed-upon physical location for USB swaps.</p>'''),
    ],[F("Ready.gov","https://www.ready.gov/kit","US emergency preparedness guide"),F("Digital Emergency Kit Guide","https://digitalemergencykit.com/","Comprehensive digital prep")]),
    ("Essential Rescue Tools", "tools.html",
     '''Curated list of essential offline rescue tools for every scenario.''',
     "Survival", "fas fa-tools", [
        Q("Top 10 Must-Have Tools", '''<p>1. Hiren's Boot CD PE (Windows rescue), 2. Ventoy (multi-boot USB), 3. Kiwix + ZIM archives (offline Wikipedia), 4. VeraCrypt (full-disk encryption), 5. KeePassXC (offline passwords), 6. Clonezilla (disk imaging), 7. TestDisk/PhotoRec (data recovery), 8. Malwarebytes (malware removal), 9. Process Explorer/Autoruns (Sysinternals), 10. Signal (encrypted comms). These ten cover 95% of emergency scenarios from system failure to security breach.</p>'''),
        Q("Tool Selection by OS", '''<p>Windows: Sysinternals Suite (Process Explorer, Autoruns, TCPView), NirSoft utilities (password recovery, network monitoring), Hiren's Boot CD PE. Linux: ddrescue (data recovery), fsck (filesystem repair), systemd journalctl (log analysis), htop/btop (process monitoring), netstat/ss (network). Cross-platform: VeraCrypt, KeePassXC, WireGuard, Firefox, VLC, 7-Zip, Python (for custom scripts). Keep both 32-bit and 64-bit versions.</p>'''),
        Q("Building Your Kit", '''<p>Build your kit in stages. Stage 1 (basic): 64GB USB with Ventoy, Hiren's Boot CD, Ubuntu ISO, portable apps. Stage 2 (intermediate): add SystemRescue, Memtest86, GParted, Clonezilla. Stage 3 (advanced): add network equipment (spare router, Ethernet cables, Wi-Fi adapter), SBC (Raspberry Pi with pre-configured SD card), LoRa radio (Meshtastic). Stage 4 (complete): multiple USBs (different OS rescue versions), external backup drive, offline maps, printed documentation.</p>'''),
    ],[F("Sysinternals Suite","https://learn.microsoft.com/en-us/sysinternals/","Windows system utilities"),F("NirSoft","https://www.nirsoft.net/","Windows password and network tools")]),
    ("Setting Up Offline Servers", "servers.html",
     '''Run local servers for offline use — DHCP, DNS, file sharing, and media streaming without internet.''',
     "Survival", "fas fa-server", [
        Q("Local Network Services", '''<p>Offline servers run on a LAN without internet. DHCP server: assign IPs automatically (dnsmasq or your router), DNS server: resolve local hostnames (dnsmasq with /etc/hosts or Pi-hole), NTP server: keep devices' clocks synchronized (chrony). File sharing: Samba (Windows file shares), NFS (Linux), SFTP/SSH (cross-platform). Media streaming: Jellyfin (open-source Plex alternative) serves your movie/TV/music library offline.</p>'''),
        Q("Raspberry Pi as Server", '''<p>Raspberry Pi 4/5: the perfect offline server. Power consumption: ~5W (runs 24/7). Services to run: Pi-hole (DNS-level ad blocking and caching), Samba (file server with external HDD), Jellyfin (media server with hardware transcoding on Pi 5), Syncthing (offline file sync between devices), Kiwix-serve (serve ZIM content over LAN). Install with Raspberry Pi OS Lite (no desktop — saves resources). Use PoE (Power over Ethernet) for single-cable deployment.</p>'''),
        Q("Mesh Networking", '''<p>When infrastructure fails, mesh networks keep devices connected. BATMAN-adv: kernel-level mesh protocol for Wi-Fi — nodes relay data for each other. Yggdrasil: IPv6 mesh network with end-to-end encryption — auto-configures, can route over the internet too. CJDNS: encrypted IPv6 mesh. Setup: flash LibreMesh on compatible routers (TP-Link, Ubiquiti), configure mesh interfaces, and deploy multiple nodes for coverage. Each new node strengthens the network.</p>'''),
    ],[F("Raspberry Pi Documentation","https://www.raspberrypi.com/documentation/","Official Pi setup guides"),F("LibreMesh","https://libremesh.org/","Open-source mesh networking firmware")]),
    ("Offline Knowledge Bases", "knowledge-bases.html",
     '''Download and serve offline knowledge bases — Wikipedia, Stack Exchange, and technical docs.''',
     "Survival", "fas fa-book", [
        Q("Kiwix & ZIM Archives", '''<p>Kiwix is an offline reader for ZIM files (compressed web content). Download ZIMs from download.kiwix.org/zim/ or via the Kiwix library within the app. Essential ZIMs: Wikipedia (full EN ~100GB, or no-images ~40GB), Wikibooks, WikiHow, Wiktionary, Stack Exchange (programming Q&A), Project Gutenberg (public domain books). Install Kiwix-serve to serve ZIMs over the local network — any device with a browser can access them.</p>'''),
        Q("Zeal & Dev Docs", '''<p>Zeal (Windows/Linux) or Dash (macOS) download offline API documentation. Docsets: Python, JavaScript, React, Docker, Kubernetes, Linux man pages, PostgreSQL, Redis, Nginx, and 200+ more. Download via the app's docsets browser. Use offline: search is instant, full-text. Combine with Kiwix for a complete offline development environment. DevDocs.io: web-based alternative with same concept — cache docs locally via service worker.</p>'''),
        Q("Stack Exchange Archives", '''<p>Stack Exchange releases quarterly data dumps under CC-BY-SA. Download from archive.org/details/stackexchange. Contains: Stack Overflow (Q&A, ~80GB compressed), Server Fault, Super User, Unix & Linux, and all other Stack Exchange sites. Kiwix has pre-built ZIMs for the most popular sites. For searching: Stack Overflow offline with full-text search via Kiwix. Keep updated: download new quarterly dumps or wait for Kiwix to publish updated ZIMs.</p>'''),
    ],[F("Kiwix","https://www.kiwix.org/","Offline Wikipedia and content reader"),F("Zeal Docs","https://zealdocs.org/","Offline API documentation browser")]),
    ("Offline Maps & Navigation", "maps.html",
     '''Download offline maps for navigation when there's no data connection.''',
     "Survival", "fas fa-map", [
        Q("Offline Map Apps", '''<p>Organic Maps: open-source offline maps based on OpenStreetMap data — walking, driving, cycling, public transit navigation. Download entire countries, no internet needed for routing. Maps.me: popular alternative with hotel/restaurant listings. OsmAnd: most feature-rich OSM app — contour lines, hiking trails, GPX track recording. All three: download maps per-country, offline search, offline turn-by-turn navigation.</p>'''),
        Q("Download Strategy", '''<p>Download maps before travel or while on Wi-Fi. Strategy: home country (full detail), neighboring countries (road networks), destinations (city detail). Map sizes: USA ~5GB (full), Europe ~10GB (full), state/province ~200MB-1GB. Storage: download to SD card on Android (256GB+ recommended for global coverage). Update every 3-6 months (OpenStreetMap is updated continuously). Enable automatic updates on Wi-Fi in app settings.</p>'''),
        Q("Satellite & Topographic", '''<p>Satellite imagery offline: Google Maps allows caching 30mi² per download, but requires periodic refresh. Organic Maps: no satellite imagery but has detailed terrain. Topographic maps: OsmAnd with contour lines plugin — elevation data for hiking, off-road navigation. GPS without data: all offline maps use the device's GPS chip (works without internet). Download GPX tracks for specific hikes/routes from AllTrails or Komoot before going offline.</p>'''),
    ],[F("Organic Maps","https://organicmaps.app/","Free offline maps app"),F("OsmAnd","https://osmand.net/","Feature-rich offline maps")]),
    ("Offline Wikivoyage & Travel Guides", "offline-wikis.html",
     '''Carry travel guides, phrasebooks, and survival knowledge offline — Kiwix ZIMs for travelers.''',
     "Survival", "fas fa-wikipedia-w", [
        Q("Essential Travel ZIMs", '''<p>Wikivoyage: free worldwide travel guide — attractions, restaurants, accommodation, safety tips for every destination (~2GB). WikiHow: survival how-to guides — first aid, shelter, navigation, outdoor skills (~5GB). Wiktionary: dictionary in any language for offline phrase translation (~30GB for EN). Stack Exchange travel: travel.stackexchange.com Q&A archive. Download these before travel for a complete offline trip companion.</p>'''),
        Q("Kiwix Serving", '''<p>Kiwix-serve: serve ZIM archives over local Wi-Fi. Install kiwix-serve on a Raspberry Pi or portable server, connect via travel router, and access all knowledge bases from any device with a browser. Perfect for group travel or educational settings in areas with limited internet. Battery-powered Pi + portable battery = mobile library. kiwix-serve supports full-text search across all ZIMs. Port 8080 default, accessible at http://kiwix.local:8080.</p>'''),
        Q("Phrasebooks & Language", '''<p>Offline language tools: Wiktionary ZIM (etymology, translations), Kiwix phrasebooks (pre-made compilations), Google Translate offline (download language packs in advance — 50+ languages available). Organic Maps: offline search supports local language place names. Survival phrases: print essential phrases for regions you visit (medical emergencies, directions, police, help). Self-hosted LibreTranslate for private machine translation.</p>'''),
    ],[F("Kiwix Download","https://download.kiwix.org/zim/","ZIM archive library"),F("Wikivoyage","https://wikivoyage.org/","Free travel guide")]),
    ("Encrypted Communication Tools", "encrypted-comms.html",
     '''End-to-end encrypted messaging and calling — Signal, Matrix, Briar, and protocol comparison.''',
     "Survival", "fas fa-comment-dots", [
        Q("Signal Protocol", '''<p>Signal: gold standard for E2E encrypted messaging. Protocol: Double Ratchet (forward secrecy + future secrecy), X3DH (extended triple Diffie-Hellman key agreement). Features: disappearing messages (custom timers), sealed sender (metadata protection), screen security (prevent screenshots), voice/video calls encrypted end-to-end. Requires phone number. Open-source, publicly audited. Recommended by Snowden, EFF, and security experts worldwide.</p>'''),
        Q("Matrix & Element", '''<p>Matrix: open, decentralized protocol for encrypted communication. Element is the flagship client. Decentralized: anyone can host their own homeserver (Synapse). Bridges: connect to Slack, Discord, Telegram, WhatsApp, Signal from one interface. E2EE: enabled per-room, Olm/Megolm ratchet. VoIP and video calls via WebRTC. Spaces: group rooms into organizations. Self-hosting: install Synapse + Element Web on a VPS and control your data entirely.</p>'''),
        Q("Offline & Mesh Messaging", '''<p>Briar: Android app that works over Bluetooth, Wi-Fi direct, and Tor — no internet required for local communication. Messages sync when devices are in proximity. Briar Mailbox: relay server stores messages for offline delivery. Session: Signal-like encryption but no phone number, no metadata — uses onion routing (oxen service nodes). SimpleX: no user identifiers at all — uses ephemeral queue addresses. Covers extreme privacy and offline scenarios.</p>'''),
    ],[F("Signal","https://signal.org/docs/","Signal protocol documentation"),F("Matrix","https://matrix.org/","Open decentralized communication protocol")]),
    ("Offline Communication Mesh", "offline-communication.html",
     '''Communicate without internet — mesh networks, LoRa radio, and emergency broadcast tools.''',
     "Survival", "fas fa-broadcast-tower", [
        Q("LoRa & Meshtastic", '''<p>Meshtastic: open-source LoRa mesh messaging. Devices: ESP32 + SX1262 LoRa radio (Heltec, LilyGO, RAK Wireless). Range: 2-10km urban, 10-30km+ line of sight. No infrastructure needed — each node relays messages. Battery life: weeks on 18650 battery. MQTT gateway: bridge Meshtastic to the internet if available. Apps: Android, iOS, Web. Use: group chat, GPS location sharing, private channels with AES encryption. Ideal for hiking, emergencies, events.</p>'''),
        Q("Wi-Fi Mesh Protocols", '''<p>802.11s: standard wireless mesh networking — supported by Linux and many router firmwares. BATMAN-adv: kernel-level mesh protocol (better than 802.11s in dense environments). OLSR: IPv4 mesh routing protocol. Yggdrasil: IPv6 mesh with end-to-end encryption — auto-peering, works over any connection. Setup: flash OpenWrt on compatible routers (TP-Link, Xiaomi), install mesh packages, configure. Community networks: NYC Mesh, Freifunk (Berlin), Guifi.net (Spain).</p>'''),
        Q("Emergency Broadcast", '''<p>RTL-SDR: $20 USB dongle — receive police, fire, weather radio, aircraft (ADS-B), satellite imagery (NOAA APT), and more. Transmit requires HAM license. HAM radio: technician license (US) is 35-question multiple choice. Baofeng UV-5R: $25 handheld — 5W, 2m/70cm bands. APRS: send text messages and GPS position over HAM radio without internet. Winlink: send emails via HAM radio. Both SHARES and MARS provide government emergency communications.</p>'''),
    ],[F("Meshtastic","https://meshtastic.org/","Open-source LoRa mesh platform"),F("RTL-SDR","https://www.rtl-sdr.com/","Software-defined radio resources")]),
    ("Data Recovery & Forensics", "data-recovery.html",
     '''Recover deleted files, repair corrupted drives, and salvage data from failing storage.''',
     "Survival", "fas fa-hard-drive", [
        Q("Imaging Failing Drives", '''<p>First rule of data recovery: work on a copy. Tools: ddrescue (Linux) reads failing drives, skips bad sectors on first pass, retries later. Creates an image file you can safely work on. ddrescue -d -r3 /dev/sda image.img mapfile.log. Clonezilla: bit-for-bit disk cloning for healthy drives. Never attempt recovery on the original drive — further damage is almost certain. Bad sectors multiply as the drive is used.</p>'''),
        Q("File Recovery Tools", '''<p>Recuva (Windows, free): recover files from recently deleted, formatted drives. Deep scan mode finds older files. Good for NTFS, FAT, exFAT. PhotoRec (cross-platform, free): recovers 480+ file types, ignores filesystem (works on formatted/corrupted drives). TestDisk: repair partition tables, recover deleted partitions. R-Studio (paid, powerful): RAID reconstruction, network recovery, advanced algorithms. For SSDs: less chance of recovery due to TRIM — stop using the drive immediately.</p>'''),
        Q("Data Rescue Scenarios", '''<p>Deleted files (not overwritten yet) → run Recuva/PhotoRec immediately. Formatted drive → TestDisk to recover partition, then recover files. Corrupted filesystem → fsck (Linux), chkdsk (Windows) — may make things worse, image first. Physical damage → send to professional recovery service ($500-$3000+). Water damage → remove power immediately, dry for 72+ hours in silica gel. Ransomware → backup is the only reliable recovery — decryption tools exist for some variants (nomoreransom.org).</p>'''),
    ],[F("ddrescue Guide","https://www.gnu.org/software/ddrescue/","GNU ddrescue documentation"),F("PhotoRec","https://www.cgsecurity.org/wiki/PhotoRec","Free file recovery tool")]),
    ("Deep Backup Strategies", "backup-strategies-deep.html",
     '''Comprehensive backup strategies beyond 3-2-1 — automation, verification, and disaster recovery.''',
     "Survival", "fas fa-copy", [
        Q("Backup Methodologies", '''<p>3-2-1 rule: 3 copies, 2 different media types, 1 off-site. Enhancements: 3-2-1-1-0 (3 copies, 2 media, 1 off-site, 1 offline/air-gapped, 0 errors after verify). GFS (Grandfather-Father-Son): daily (7 days), weekly (4 weeks), monthly (12 months). Incremental Forever: one full backup, then only changed data forever. Differential: full backup + all changes since last full. Modern approach: Borg/Restic (deduplicated, encrypted, versioned backups).</p>'''),
        Q("Tools & Automation", '''<p>Restic: fast, encrypted, deduplicated — supports local, SFTP, S3, Backblaze B2, REST server. One command: restic -r s3:s3.amazonaws.com/bucket backup /home — uses snapshots, prune old ones. Borg: similar but Python-based, better deduplication, supports append-only mode (protects backups from ransomware). Borg + Vorta: GUI frontend. Duplicati: web UI, supports cloud targets, AES-256 encryption. Duplicacy: commercial alternative to Restic with web UI.</p>'''),
        Q("Disaster Recovery Testing", '''<p>Untested backups are worthless. Test quarterly: restore a random file (check integrity), restore a full server (time how long), verify encrypted backups (test decryption), test off-site access (can you reach your cloud/remote backup?). Practice scenarios: SSD failure (restore from cloud), ransomware (restore from offline backup), house fire (restore from off-site), accidental deletion (restore single file). Log test results and fix failures.</p>'''),
    ],[F("Restic","https://restic.net/","Fast encrypted backups"),F("Borg Backup","https://www.borgbackup.org/","Deduplicating backup tool")]),
    ("System Rescue Deep Dive", "system-rescue.html",
     '''Boot and repair broken systems — bootloaders, filesystem repair, and offline malware removal.''',
     "Survival", "fas fa-life-ring", [
        Q("Bootloader Repair", '''<p>GRUB repair (Linux): boot from live USB, chroot into broken system: mount /dev/sda1 /mnt, mount --bind /dev /mnt/dev, mount --bind /proc /mnt/proc, chroot /mnt, grub-install /dev/sda, update-grub. Windows Boot Manager: boot from Windows install media, open command prompt: bootrec /fixmbr, bootrec /fixboot, bootrec /rebuildbcd. UEFI: bootrec /fixboot may not work — try bcdedit /export, bcdedit /import, or rebuild BCD store manually.</p>'''),
        Q("Filesystem Repair", '''<p>Linux filesystem check: umount /dev/sda1, fsck.ext4 -f /dev/sda1 (-f = force even if clean). Check bad sectors: badblocks -sv /dev/sda. Windows: chkdsk /f /r C: (/f fixes errors, /r finds bad sectors). Repair tool: TestDisk for partition table repair. If filesystem is beyond repair: use ddrescue to image the drive, then try recovery tools on the image. For ZFS: zpool import -f, zpool scrub, zpool clear errors.</p>'''),
        Q("Offline Malware Removal", '''<p>Boot from rescue USB (Hiren's, SystemRescue) — malware can't run in a live environment. Scan from offline: use Malwarebytes portable (Windows PE), ClamAV (Linux live), Emsisoft Emergency Kit. Key steps: mount infected volume (read-only!), scan, delete threats, check startup entries (Autoruns), verify system files (sfc /scannow). For rootkits: use GMER, Kaspersky TDSSKiller, or boot with anti-rootkit rescue disc. Ransomware: do NOT pay — check nomoreransom.org for free decryption tools.</p>'''),
    ],[F("SystemRescue","https://www.system-rescue.org/","Arch-based Linux rescue environment"),F("Hiren's Boot CD","https://www.hirensbootcd.org/","Windows PE rescue disk")]),
    ("BIOS/UEFI Recovery & Firmware", "bios-recovery.html",
     '''Recover from failed BIOS updates, corrupt firmware, and unbrick motherboards.''',
     "Survival", "fas fa-motherboard", [
        Q("BIOS Recovery Methods", '''<p>Most modern motherboards have BIOS recovery. Asus: USB Flashback — specific USB port, rename firmware to .CAP/.ROM, press Flashback button. Gigabyte: DualBIOS — backup chip auto-recovers. MSI: BIOS Flashback + button on I/O panel. ASRock: Instant Flash — power on holding CTRL+Home. General SPI flash recovery: use CH341A programmer ($5) with SOIC8 clip — direct flash the BIOS chip. Always match motherboard model exactly.</p>'''),
        Q("Chromebook Firmware", '''<p>Chromebook firmware recovery: write-protect screw, flash custom firmware (mrchromebox.tech — UEFI or Legacy BIOS). Allows installing Windows/Linux on ChromeOS hardware. Tools: flashrom — open-source firmware flashing utility. Backup original firmware before flashing: flashrom -p internal -r backup.rom. Restore for warranty: flashrom -p internal -w stock.rom. Warning: flashing the wrong firmware bricks the device — recovery requires hardware programmer.</p>'''),
        Q("Embedded & IoT Firmware", '''<p>ESP32/ESP8266: OTA updates, esptool.py for serial flashing. Recovery: GPIO0 button during power-up = flash mode. Raspberry Pi: EEPROM updates via rpi-eeprom-update (recovery if Pi won't boot — reflash SD card with Raspberry Pi Imager). Routers: DD-WRT, OpenWrt, FreshTomato — TFTP recovery if flash fails (static IP + tftp binary upload on boot). For completely bricked devices: JTAG/SWD debug headers with JLink/ST-Link programmers.</p>'''),
    ],[F("CH341A Programmer Guide","https://github.com/georgehill/CH341A-Guide","SPI flash programming guide"),F("MrChromebox","https://mrchromebox.tech/","Chromebook firmware tools")]),
    ("Password Reset & Recovery", "password-reset.html",
     '''Reset forgotten passwords, bypass lock screens, and recover credentials — legally and safely.''',
     "Survival", "fas fa-key", [
        Q("Windows Password Reset", '''<p>chntpw: reset Windows local passwords from Linux live USB. Boot Ubuntu live, mount Windows partition, sudo apt install chntpw, cd /mnt/Windows/System32/config, chntpw SAM. Interactive menu: clear password, promote to admin, or blank. Works on all Windows up to Windows 11. Limitations: Microsoft account (online) passwords can't be reset — you need to reset the Microsoft password online. Utility: Hiren's Boot CD includes chntpw GUI.</p>'''),
        Q("Linux Password Reset", '''<p>Single user mode: boot GRUB, press 'e' on kernel line, add init=/bin/bash or rd.break at end, Ctrl+X to boot, mount -o remount,rw /, passwd, new password. Live USB: boot Ubuntu, chroot into system: mount /dev/sda1 /mnt, mount --bind /dev /mnt/dev, chroot /mnt, passwd username. LUKS encryption: you need the passphrase — no bypass. Emergency: if LUKS header is corrupt, backup header (if you made one).</p>'''),
        Q("macOS & Mobile Recovery", '''<p>macOS: boot into Recovery Mode (Cmd+R), open Terminal, resetpassword command resets login password. Apple ID: if FileVault is enabled, you need recovery key or Apple ID. iOS: recovery mode (Volume Up, Volume Down, Power button combo) — connect to computer, restore via Finder/iTunes — erases data. Android: Google account recovery (after multiple failed attempts). Samsung: Find My Mobile — unlock remotely. ADB: if USB debugging was enabled, adb shell to bypass lock.</p>'''),
    ],[F("chntpw","https://pogostick.net/~pnh/ntpasswd/","Windows password reset tool"),F("Apple Recovery","https://support.apple.com/guide/mac-help/recover-mac-options-mchlp1039","macOS recovery options")]),
    ("Ransomware Response", "ransomware-response.html",
     '''Immediate steps during a ransomware attack — isolate, assess, and recover without paying.''',
     "Survival", "fas fa-bug-slash", [
        Q("Immediate Isolation", '''<p>Step 1: disconnect from all networks immediately. Pull ethernet cable, disable Wi-Fi, turn on airplane mode. Step 2: disconnect external drives and network shares — ransomware spreads through mapped drives. Step 3: power down the infected machine (hold power button 10 seconds). Step 4: boot from a clean rescue USB — do not boot from the infected drive. Step 5: image the infected drive with ddrescue (for forensic analysis).</p>'''),
        Q("Decryption & Recovery", '''<p>Check nomoreransom.org: submit a ransom note or encrypted file sample — they have decryption tools for 150+ ransomware variants. ID Ransomware: upload ransom note or encrypted file to identify the variant. Check BleepingComputer's ransomware forum for current help threads. Restore from backup: this is why offline/air-gapped backups are critical. Do NOT pay the ransom: paying funds criminals, and you may not get your data back (20%+ don't). Report to law enforcement (IC3, local cybercrime).</p>'''),
        Q("Post-Attack Hardening", '''<p>After recovery: change EVERY password (start with email, then critical services), enable 2FA on all accounts, review and clean up user accounts (remove unused/admin accounts), apply all security patches, enable RDP via VPN only (or disable RDP entirely), implement backup 3-2-1-1-0 strategy, install EDR (CrowdStrike, SentinelOne, or free: Wazuh), conduct phishing training for employees, create an incident response plan and test it.</p>'''),
    ],[F("No More Ransom","https://www.nomoreransom.org/","Free ransomware decryption tools"),F("ID Ransomware","https://id-ransomware.malwarehunterteam.com/","Ransomware identification tool")]),
    ("Malware Removal Guide", "malware-removal.html",
     '''Detect and remove malware — from adware to rootkits, using both automated and manual techniques.''',
     "Survival", "fas fa-broom", [
        Q("Automated Scanning", '''<p>Offline scanners (boot from rescue USB): Malwarebytes portable (Windows PE), Emsisoft Emergency Kit (portable + second opinion scanner), Kaspersky Virus Removal Tool (free, updated definitions), ESET Online Scanner (portable, cloud-assisted). Online scanners (use from clean device): VirusTotal (file hash lookup), Hybrid Analysis (deep behavioral analysis), Joe Sandbox (automated sandbox). Adware clean: AdwCleaner (targeted PUP/adware removal), RogueKiller (PUP + basic malware).</p>'''),
        Q("Manual Investigation", '''<p>Process analysis: Process Explorer (Sysinternals) — check for suspicious processes (unsigned, fake names like scvhost.exe), check VirusTotal column. Startup entries: Autoruns — disable suspicious entries, check scheduled tasks, services, drivers, browser extensions. Network: TCPView — suspicious outbound connections, unknown IPs/domains. Registry: Autoruns also checks registry run keys. Browser: check extensions, proxy settings (FoxyProxy, PAC file hijacking).</p>'''),
        Q("Rootkit & Stealth Malware", '''<p>Rootkits hide from the OS — detected by boot-time scanners. GMER: scans for hidden processes, threads, modules, services, files, disk sectors. Kaspersky TDSSKiller: targets bootkits and rootkits. Sophos Rootkit Removal: free boot-time scanner. Microsoft Defender Offline: built-in offline scanner (Settings > Windows Security > Virus & Threat > Microsoft Defender Offline Scan). Malwarebytes Anti-Rootkit: specialized anti-rootkit tool. If rootkit persists: backup data, nuke and reinstall OS.</p>'''),
    ],[F("Malwarebytes","https://www.malwarebytes.com/","Anti-malware software"),F("Sysinternals Suite","https://learn.microsoft.com/en-us/sysinternals/","Windows system internals tools")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} piracy + survival tutorials!")
