#!/usr/bin/env python3
"""Generate ~8 tutorials — Architecture, Data, DevOps, Security fill-ins."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tutorial_helpers import build_page

Q = lambda l, b: (l, b)
F = lambda n, u, d: (n, u, d)

TUTORIALS = [
    # === ARCHITECTURE (1) ===
    ("Microfrontends", "microfrontends.html", "Microfrontends — compose frontends from independent teams, frameworks, and deployments.", "Architecture", "fas fa-puzzle-piece", [
        Q("Integration & Composition", "<p>Microfrontends: extend microservice thinking to frontend. Each feature owned by one team (UI + API + DB). Integration strategies: iframe (simple but SEO/accessibility issues), Web Components (framework-agnostic, shadow DOM), client-side composition (JS at runtime), server-side composition (Edge Side Includes, Tailor), module federation (Webpack 5 — share modules at runtime). Build-time composition: monorepo with shared libs. Module federation: exposes/remotes — App shell exposes nav, remote apps register. Single-SPA: meta-framework — routing between frameworks (React, Vue, Angular, Svelte). Qiankun: Alibaba's single-SPA wrapper, sandbox. Piral: portal-based microfrontends. Composition patterns: router-based (each route = different app), widget-based (page = widgets from different teams).</p>"),
        Q("Team & Cross-Cutting", "<p>Team structure: each team owns feature(s), deploys independently. Conway's law: frontend mirrors team boundaries. Shared dependencies: avoid duplication — peer dependencies, import maps (ES modules), Module Federation shared config. Design system: shared UI component library, design tokens (CSS variables). Communication: custom events (window.dispatchEvent), shared event bus, cross-frame messaging (postMessage). State management: shared via events, not direct coupling. Shared auth: each microfrontend gets JWT from shell. Testing: integration tests between microfrontends, contract tests. Deployment: independent pipelines (each microfrontend deployed separately), feature flags for rollout. CI/CD: verify integration but deploy independently. Challenges: bundle size (avoid duplicate deps), consistent UX, cross-team coordination, performance (multiple frameworks), testing at integration points. MFE discovery: registry (static or dynamic) so shell knows available apps. When NOT to use: small team, simple app, no independent deploys needed.</p>"),
    ],[F("Micro Frontends by Martin Fowler","https://martinfowler.com/articles/micro-frontends.html","Martinfowler.com article"),F("Module Federation Docs","https://webpack.js.org/concepts/module-federation/","Webpack 5 Module Federation")]),

    # === DATA (3) ===
    ("NoSQL Databases Overview", "nosql-databases-overview.html", "NoSQL — document, key-value, wide-column, graph databases and use cases.", "Data", "fas fa-database", [
        Q("Document & Key-Value", "<p>Document stores: MongoDB (BSON, flexible schema, indexes, aggregation pipeline, replica sets, sharding), Couchbase (N1QL, SQL-like queries), CouchDB (replication-focused, REST API), Firebase Firestore (serverless, real-time). Use: catalogs, content management, user profiles, JSON-heavy data. Key-value stores: Redis (in-memory, persistence, pub/sub, streams, sorted sets, Lua scripting), Memcached (simple, distributed cache), DynamoDB (AWS, managed, auto-scaling, DAX), Etcd (distributed config, Raft consensus). Use: caching, session storage, real-time leaderboards, distributed locks, config storage. Consistency: DynamoDB (eventual or strongly consistent), Redis (master-replica, persistence configurable). CAP theorem: partition tolerance + availability (AP) or consistency (CP). MongoDB: CP (by default). Cassandra: AP.</p>"),
        Q("Wide-Column & Graph", "<p>Wide-column (column-family): Apache Cassandra (AP, peer-to-peer, no single point of failure, CQL, tunable consistency, compaction strategies), ScyllaDB (C++ rewrite, faster), HBase (CP, Hadoop ecosystem, strong consistency, region servers), Google Bigtable (managed, spanner-based). Data model: row key -> column families -> columns. Use: time-series data, IoT, recommendation engines, event logging, large-scale analytics. Graph databases: Neo4j (property graph, Cypher query language, ACID, graph algorithms, Bloom visualization), Amazon Neptune (managed, property graph/RDF), ArangoDB (multi-model, native graph), JanusGraph (open-source, distributed). Use cases: social networks, fraud detection, knowledge graphs (Google Knowledge Graph), recommendation engines, network/infra topology, supply chain, identity resolution. RDF vs Property graph: RDF (W3C standard, semantic web, SPARQL), property graph (label+property, Neo4j, Gremlin). Multi-model: ArangoDB (documents + graph + key-value). Time-series: InfluxDB (purpose-built), TimescaleDB (SQL-based), Prometheus (monitoring metrics). Search: Elasticsearch (full-text search, analytics, aggregation). Choosing: data model drives choice.</p>"),
    ],[F("MongoDB Docs","https://www.mongodb.com/docs/","MongoDB official docs"),F("Cassandra Docs","https://cassandra.apache.org/doc/latest/","Apache Cassandra documentation")]),

    ("Data Engineering & ETL", "data-engineering-etl.html", "Data engineering — ETL/ELT, pipelines, data warehousing, and orchestration.", "Data", "fas fa-code-branch", [
        Q("ETL/ELT & Pipelines", "<p>ETL (Extract, Transform, Load): extract from sources, transform (clean, reshape), load to warehouse. ELT (Extract, Load, Transform): load raw data first, transform in warehouse (modern cloud approach). Extraction: batch (scheduled pulls) vs streaming (real-time — Kafka, Kinesis). CDC: change data capture (Debezium for Postgres/MySQL, AWS DMS). Transformation: dbt (data build tool — SQL-based transformation, testing, documentation, Jinja templates). Spark: distributed processing — DataFrames, SQL, MLlib, structured streaming. Airflow: DAG-based orchestration — tasks, dependencies, sensors, XCom. Prefect: Python-native orchestration. Dagster: data-aware orchestration, asset-oriented. Data pipelines: source -> ingestion -> staging -> transformation -> serving. Data lake: raw/curated zones (S3/ADLS), open formats (Parquet, Avro, ORC). Delta Lake: ACID transactions on data lake, time travel, schema enforcement. Apache Iceberg: table format for huge datasets. Data catalog: AWS Glue, Apache Atlas, Amundsen, DataHub. Data quality: Great Expectations (expectations, suites, data docs), dbt tests. Schema evolution: add/drop columns, backward/forward compatibility. Idempotency: rerun safely, upsert logic. Backfill: replay historical data.</p>"),
        Q("Warehousing & Streaming", "<p>Data warehouses: Snowflake (cloud-native, compute/storage separation, cloning, zero-copy, time travel), BigQuery (serverless, columnar, partitioned tables, clustering, BI Engine), Redshift (columnar, sort keys, distribution styles, RA3 nodes). Star schema: fact table (measures, foreign keys) + dimension tables (attributes). Snowflake schema: normalized dimensions. Data marts: subset for specific domain. Streaming: Kafka (topics, partitions, producer, consumer, exactly-once semantics, Kafka Connect for source/sink connectors, KStreams/KSQL for stream processing). Flink: true streaming with event time, exactly-once, SQL. Spark Streaming: micro-batches. Real-time vs batch: latency requirements. Lambda architecture: batch + speed + serving layers. Kappa architecture: all events, all streaming, reprocess for different views. Data mesh: domain ownership, data as product, self-serve platform, federated governance. PII handling: masking, tokenization, encryption at rest/transit. Monitoring: data freshness, row counts, schema drift, latency. Cost: storage vs compute, partitioning for query pruning. Orchestration: Airflow (DAGs, operators, connections, pools, SLAs), Prefect (2.0 — flows, tasks, caching, notifications), Dagster (assets, ops, graphs, sensors).</p>"),
    ],[F("Apache Airflow Docs","https://airflow.apache.org/docs/","Workflow orchestration documentation"),F("dbt Docs","https://docs.getdbt.com/","Data transformation tool docs")]),

    # === DEVOPS (4) ===
    ("Observability & Telemetry", "observability-telemetry.html", "Observability — logs, metrics, traces, OpenTelemetry, and alerting.", "DevOps", "fas fa-chart-line", [
        Q("Logs & Metrics", "<p>Observability: ability to infer system state from external outputs. Three pillars: logs (discrete events), metrics (aggregated time-series), traces (request flow). Logging: structured logs (JSON — timestamp, level, service, message, trace_id). Log levels: DEBUG, INFO, WARN, ERROR, FATAL. Log aggregation: ELK (Elasticsearch, Logstash, Kibana), Loki (Grafana, Promtail — logQL, cheap), Splunk (enterprise). Metrics: Prometheus (pull model, time-series database, PromQL queries, Alertmanager). Metric types: counter (requests total, always increases), gauge (CPU, memory, current value), histogram (latency buckets, quantiles), summary (pre-computed quantiles). RED method: Rate (requests/sec), Errors (failed requests/sec), Duration (latency). USE method: Utilization, Saturation, Errors (for resources — CPU, memory, disk, network). Grafana: dashboards, panels (time series, stat, table, bar gauge), alerts, annotations, variables. Grafana Cloud or self-hosted. Loki: log aggregation like Prometheus but for logs, label-based, cost-effective. Promtail: agent to ship logs. LogQL: query logs with filters, parsers, metrics from logs.</p>"),
        Q("Tracing & OpenTelemetry", "<p>Distributed tracing: trace a request across services. Trace: tree of spans. Span: operation with name, start time, duration, attributes, status. Trace context: trace ID + span ID propagated via W3C Trace Context headers (traceparent, tracestate). OpenTelemetry (OTel): vendor-neutral standard — APIs, SDKs, Collector, semantic conventions. Instrumentation: automatic (auto-instrumentation agents for Java, Python, Node.js, .NET, Go) and manual (create spans, add attributes/events). OTel Collector: receiver (OTLP, Jaeger, Prometheus), processor (batch, filter, attributes, sampling), exporter (to backend: Jaeger, Zipkin, Prometheus, Loki, Tempo, Datadog, Honeycomb). Sampling: head-based (decision at start of trace), tail-based (decision after full trace, based on content). Jaeger: open-source tracing backend (UI, storage backend — Elasticsearch, Cassandra, Kafka). Grafana Tempo: tracing backend integrated with Grafana, object storage (S3/GCS). Service maps: visualize dependencies. Alerting: based on metrics (high error rate, latency SLO), logs (error patterns), traces (slow traces). SLOs: service level objectives, error budgets. On-call: PagerDuty, OpsGenie, Grafana OnCall. Observability patterns: health check endpoints, /metrics endpoint, /health endpoint. Logs vs Metrics vs Traces: logs for detailed debugging, metrics for trends/alerts, traces for request flow.</p>"),
    ],[F("OpenTelemetry Docs","https://opentelemetry.io/docs/","Vendor-neutral observability framework"),F("Grafana Docs","https://grafana.com/docs/","Grafana observability docs")]),

    ("Load & Performance Testing", "load-performance-testing.html", "Performance testing — load, stress, spike, soak tests, and tooling.", "DevOps", "fas fa-tachometer-alt", [
        Q("Test Types & Metrics", "<p>Performance testing types: load testing (expected traffic), stress testing (beyond peak to find breaking point), spike testing (sudden surge), soak/endurance testing (sustained over time, detect memory leaks), scalability testing (increasing load to find scaling limits). Key metrics: latency (p50, p95, p99, p999 — tail latency), throughput (requests/sec, transactions/sec), error rate (%, HTTP 5xx), concurrency (active users/connections), resource usage (CPU, memory, disk I/O, network). Response time components: network latency, processing time, queue time, I/O wait. Think time: realistic pauses between user actions. Pacing: rate of requests. Virtual users (VUs): simulated users performing actions. Little's Law: L = λ * W (concurrent users = throughput * response time). Degradation curve: how latency increases with load. Saturation point: where throughput stops increasing with load.</p>"),
        Q("Tools & Practice", "<p>k6: modern load testing (Grafana) — JavaScript scripting, lifecycle (setup, VU, teardown), thresholds, checks, metrics, browser mode. k6 Cloud: distributed execution. Scenarios: ramping VUs, constant VUs, shared iterations. JMeter: GUI test plans, thread groups, samplers (HTTP, JDBC, gRPC), listeners (reports, graphs), distributed testing. Locust: Python scripting, Web UI, distributed. Artillery: YAML/JS config, HTTP, WebSocket, Socket.io. wrk/httpie: quick HTTP benchmarking. Vegeta: Go-based, CLI. Gatling: Scala/Java, high performance. Performance in CI: k6 in GitHub Actions, GitLab CI, Jenkins. Thresholds: p95 < 500ms, error rate < 1%. Performance regression: compare with baseline. Ramp-up: gradual increase to find breaking point. Test data: realistic data, avoid caching effects. Warm-up: run before measuring. Non-functional requirements: define SLOs — API response < 200ms p95. Common issues: connection pool exhaustion, DB query N+1, memory leak, GC pauses, thread contention, slow external calls, serialization bottlenecks. Bottleneck identification: use flamegraphs, profilers, distributed tracing. Frontend perf: Lighthouse, WebPageTest, Core Web Vitals (LCP, FID, CLS). Mobile: network throttling, device simulation.</p>"),
    ],[F("k6 Docs","https://k6.io/docs/","Grafana k6 documentation"),F("JMeter Docs","https://jmeter.apache.org/","Apache JMeter documentation")]),

    ("Feature Flags & A/B Testing", "feature-flags-testing.html", "Feature flags, canary releases, A/B testing, and experimentation.", "DevOps", "fas fa-toggle-on", [
        Q("Feature Flags", "<p>Feature flags (toggles): boolean conditions wrapping features. Types: release toggles (gradual rollout), experiment toggles (A/B tests), ops toggles (operational controls), permission toggles (premium features). Flag management: LaunchDarkly (full-featured, targeting rules, SDKs, audit log), Flagsmith (open-source), Unleash (open-source), Split.io, ConfigCat. Strategy: two-tier — kill switch (emergency off) + targeting rules (user segments, percentage rollout). Flag lifecycle: create -> evaluate -> remove (clean up to avoid tech debt). Code: if (flags.isEnabled('new-checkout')) { ... } else { ... } . SDK patterns: server-side (evaluate from cache, webhooks for updates), client-side (frontend flags — user targeting). Flag values: boolean, string, number, JSON. Targeting: user attributes (email, plan, region, beta group). Gradual rollout: 5%, 25%, 50%, 100%. Canary release: deploy to subset of instances, shift traffic. Auto-rollback: flag off if errors spike. A/A test: verify metrics before running A/B. Kill switch: flag to disable a feature immediately without deploy.</p>"),
        Q("A/B Testing & Experimentation", "<p>A/B testing (split testing): show different versions to different users, measure metrics. Statistical significance: p-value < 0.05 (95% confidence), power > 80%. Minimum sample size: size needed to detect effect. Metrics: primary (conversion rate, revenue), secondary (click-through, engagement), guardrail (page load time must not degrade). Randomization: user-level (same user sees same variant), session-level, event-level. Bucketing: hash user ID for deterministic assignment. Anti-fragmentation: ensure consistent experience. Multi-armed bandit: dynamically allocate traffic to better-performing variant. Experiment platforms: Google Optimize, Optimizely, VWO, LaunchDarkly experimentation. Bayesian vs frequentist: Bayesian (probability of being better, no p-value), frequentist (hypothesis testing). Tracking: events pipeline (client -> server -> warehouse). Metrics computation: daily/weekly aggregation, delta method for ratios. Long-term effects: holdout groups (always control), carryover effects. Network effects: social/marketplace experiments are hard (user affects other users). Peeking problem avoid: sequential testing, fixed horizon. Segment analysis: does treatment affect power users differently? Cultural bias: what works in one market may not in another.</p>"),
    ],[F("LaunchDarkly Docs","https://docs.launchdarkly.com/","Feature management platform"),F("Optimizely Docs","https://docs.developers.optimizely.com/","A/B testing platform docs")]),

    ("Platform Engineering", "platform-engineering.html", "Platform engineering — internal developer platforms, Backstage, and golden paths.", "DevOps", "fas fa-layer-group", [
        Q("IDPs & Golden Paths", "<p>Platform engineering: build internal developer platform (IDP) to improve developer experience (DevEx) and reduce cognitive load. Golden paths: paved roads for common tasks (deploy service, add database, set up CI/CD). Developer portals: Backstage (Spotify's open-source — software catalog, scaffolder (templates), TechDocs, plugins), Port, Humanitec (internal developer platform), Cortex, Firestartr. Software catalog: register components (services, libraries, websites, APIs) with metadata (owner, lifecycle, system, dependsOn). Backstage scaffolder: YAML templates (steps: fetch template, create PR, register in catalog). Backstage plugins: CI/CD (Jenkins, GitHub Actions), monitoring (Datadog, Grafana), security (Snyk), cost (CloudCost). Scorecards: check ownership, docs, CI/CD coverage. IDP architecture: control plane (orchestration) + data plane (compute). Provisioning: Terraform, Pulumi, Crossplane for infrastructure. Self-service: developers request resources via portal. Environment management: ephemeral environments (review apps). Platform team: product mindset — treat developers as customers, OKRs for adoption. Scorecard metrics: service ownership %, documentation %, CI/CD %.</p>"),
        Q("Platform Components", "<p>CI/CD: unified pipeline platform — builds, tests, deploys. Feature: pipeline templates, promotion gates. Kubernetes: namespace per service, RBAC, resource quotas, network policies. Argo CD: GitOps (app of apps pattern). Crossplane: control plane — managed resources (RDS, S3, IAM). Terraform: modules for infrastructure. Service mesh: Istio (mTLS, traffic routing, observability). Gateways: Kong (API gateway for north-south traffic). Secret management: external-secrets-operator (sync secrets from Vault/AWS Secrets Manager/Google Secret Manager). Observability stack: Prometheus + Grafana + Loki + Tempo (or Datadog/Honeycomb). Cost showback: track infrastructure cost per team/service. Backstage TechDocs: docs-as-code (MkDocs, material theme). Error tracking: Sentry. Backstage integrations: GitHub, GitLab, Jenkins, Argo CD, SonarQube, Snyk, Datadog, PagerDuty. Score: portal to measure DORA metrics (deployment frequency, lead time, MTTR, change failure rate). Platform maturity: level 0 (no platform), level 1 (scripts/manuals), level 2 (automated CI/CD), level 3 (self-service portal), level 4 (developer platform with guardrails). Internal market: platform team = provider, dev teams = consumers. Focus on: reducing time from commit to production. Measure: developer satisfaction (surveys), onboarding time (hours to first deploy).</p>"),
    ],[F("Backstage Docs","https://backstage.io/docs/","Spotify's developer portal"),F("CNCF Platform Engineering","https://tag-app-delivery.cncf.io/whitepapers/platform-eng/","Cloud Native platform engineering")]),

    # === SECURITY (1) ===
    ("Cryptography Fundamentals", "cryptography-fundamentals.html", "Cryptography — symmetric, asymmetric, hashing, digital signatures, and PKI.", "Security", "fas fa-lock", [
        Q("Symmetric & Asymmetric", "<p>Symmetric encryption: same key for encrypt/decrypt. AES (Advanced Encryption Standard) — 128/192/256 bit keys, modes (ECB — not safe, CBC, GCM — authenticated encryption, CTR, CCM). GCM: AES-GCM recommended (encryption + authentication tag). ChaCha20-Poly1305: modern stream cipher (mobile-friendly). Key exchange problem: how to share the secret key? Asymmetric (public-key) cryptography: public key (encrypt, verify) + private key (decrypt, sign). RSA: factoring large numbers, key sizes 2048/4096 bits, slow, use for key exchange or signing. ECC (Elliptic Curve Cryptography): smaller keys for same security (256-bit ECC = 3072-bit RSA). ECDH: Elliptic Curve Diffie-Hellman — key agreement. Ed25519: modern EdDSA signature scheme (fast, secure). Hybrid encryption: ECDH key exchange + AES-GCM for data (TLS does this). Key generation: random enough entropy, secure random generator /dev/urandom. Key storage: HSM (hardware security module), TPM, secure enclave, secrets manager. Key rotation: regular rotation, versioned keys (KMS). Post-quantum: algorithms (CRYSTALS-Kyber, Dilithium), NIST standardization. TLS: hybrid key exchange (ECDH + Kyber).</p>"),
        Q("Hashing & Signatures", "<p>Cryptographic hash: one-way, collision-resistant, deterministic. SHA-2: SHA-256, SHA-512 (secure). SHA-3: Keccak-based. BLAKE2/BLAKE3: faster than SHA-2. HMAC: keyed-hash message authentication (verify integrity + authenticity). PBKDF2, bcrypt, scrypt, Argon2: key derivation functions (password hashing) — slow, salt, memory-hard (Argon2id recommended). Use: password storage (Argon2id, bcrypt), data integrity checks, file deduplication. Digital signatures: sign with private key, verify with public key. RSA signature: RSASSA-PKCS1-v1_5 (legacy), RSASSA-PSS (probabilistic). ECDSA: Elliptic Curve Digital Signature Algorithm (used by Bitcoin, TLS). EdDSA: Ed25519 (modern, deterministic). Use: code signing, document signing, email (S/MIME), blockchain identities. PKI (Public Key Infrastructure): Certificate Authority (CA), intermediate CAs, end-entity certificates. X.509 certificates: subject, issuer, validity, public key, extensions (SAN, key usage, extended key usage). Certificate chain: root CA -> intermediate CA -> server cert. TLS/SSL: server certificate authentication. Mutual TLS (mTLS): both sides present certificates. ACME protocol (Let's Encrypt): automated certificate issuance. Certificate pinning: constraint-check cert (risky). Certificate transparency: public logs of issued certs. CRL/OCSP: certificate revocation checking. GPG: OpenPGP for email/file encryption and signing. Web of trust: decentralized trust model (GPG).</p>"),
    ],[F("NIST Cryptography","https://csrc.nist.gov/topics/cryptography","NIST cryptography standards"),F("Cryptography Engineering","https://www.schneier.com/books/cryptography-engineering/","Schneier's book on applied crypto")]),
]

for i, (title, filename, desc, badge, icon, sections, further) in enumerate(TUTORIALS):
    build_page(title, filename, desc, badge, icon, sections, further)
    print(f"  [{i+1}/{len(TUTORIALS)}] Created: {filename}")

print(f"\nGenerated {len(TUTORIALS)} tutorials (p3g)!")
